# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# ===================================================================

#' @title List layers of a PDF dataset
#' @description
#' Auto-generated GDAL CLI wrapper.
#' List layers of a PDF dataset
#' @param input GDAL argument
#' @param output_format GDAL argument
#' @return A [gdal_job] object.
#' @family gdal_driver_utilities
#' @examples
#' \dontrun{
#' gdal_driver_pdf_list_layers(...) |> gdal_run()
#' }

#' @export
gdal_driver_pdf_list_layers <- function(input = NULL,
  output_format = NULL) {
  # Collect arguments
  args <- list()
  if (!missing(input)) args[["input"]] <- input
  if (!missing(output_format)) args[["output_format"]] <- output_format

  new_gdal_job(command_path = c("gdal", "driver", "pdf", "list-layers"), arguments = args)
}

