# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# ===================================================================

#' @title reproject: Reproject a raster dataset
#' @description
#' Reproject a raster dataset.
#' 
#' See \url{https://gdal.org/en/stable/programs/gdal_raster_reproject.html} for detailed GDAL documentation.
#' @param job A gdal_job object from a piped operation, or NULL
#' @param input Input raster dataset (Dataset path) (required)
#' @param output Output raster dataset (Dataset path) (required)
#' @param input_format Input formats (Character vector). `0` to `2147483647` value(s) (Advanced)
#' @param output_format Output format ("GDALG" allowed)
#' @param target_aligned_pixels Round target extent to target resolution (Logical) (Advanced)
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s) (Advanced)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s)
#' @param overwrite Whether overwriting existing output is allowed (Logical) (Default: `false`)
#' @param src_crs Source CRS
#' @param dst_crs Destination CRS
#' @param resampling Resampling method. Choices: nearest, bilinear, cubic, cubicspline, lanczos, ... (Default: `nearest`)
#' @param resolution Target resolution (in destination CRS units). Format: `<xres>,<yres>`. Minimum: `0`. Exactly `2` value(s)
#' @param size Target size in pixels (Integer vector). Format: `<width>,<height>`. Minimum: `0`. Exactly `2` value(s)
#' @param bbox Target bounding box (in destination CRS units). Exactly `4` value(s)
#' @param bbox_crs CRS of target bounding box
#' @param src_nodata Set nodata values for input bands ('None' to unset). (Character vector). `1` to `2147483647` value(s) (Advanced)
#' @param dst_nodata Set nodata values for output bands ('None' to unset). (Character vector). `1` to `2147483647` value(s) (Advanced)
#' @param add_alpha Adds an alpha mask band to the destination when the source raster have none. (Logical) (Advanced)
#' @param warp_option Warping option(s) (Character vector). Format: `<NAME>=<VALUE>`. `0` to `2147483647` value(s) (Advanced)
#' @param transform_option Transform option(s) (Character vector). Format: `<NAME>=<VALUE>`. `0` to `2147483647` value(s) (Advanced)
#' @param error_threshold Error threshold (Advanced)
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples
#' @export
gdal_raster_reproject <- function(job = NULL,
  input,
  output,
  input_format = NULL,
  output_format = NULL,
  target_aligned_pixels = FALSE,
  open_option = NULL,
  creation_option = NULL,
  overwrite = FALSE,
  src_crs = NULL,
  dst_crs = NULL,
  resampling = NULL,
  resolution = NULL,
  size = NULL,
  bbox = NULL,
  bbox_crs = NULL,
  src_nodata = NULL,
  dst_nodata = NULL,
  add_alpha = FALSE,
  warp_option = NULL,
  transform_option = NULL,
  error_threshold = NULL) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(target_aligned_pixels)) new_args[["target_aligned_pixels"]] <- target_aligned_pixels
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(src_crs)) new_args[["src_crs"]] <- src_crs
  if (!missing(dst_crs)) new_args[["dst_crs"]] <- dst_crs
  if (!missing(resampling)) new_args[["resampling"]] <- resampling
  if (!missing(resolution)) new_args[["resolution"]] <- resolution
  if (!missing(size)) new_args[["size"]] <- size
  if (!missing(bbox)) new_args[["bbox"]] <- bbox
  if (!missing(bbox_crs)) new_args[["bbox_crs"]] <- bbox_crs
  if (!missing(src_nodata)) new_args[["src_nodata"]] <- src_nodata
  if (!missing(dst_nodata)) new_args[["dst_nodata"]] <- dst_nodata
  if (!missing(add_alpha)) new_args[["add_alpha"]] <- add_alpha
  if (!missing(warp_option)) new_args[["warp_option"]] <- warp_option
  if (!missing(transform_option)) new_args[["transform_option"]] <- transform_option
  if (!missing(error_threshold)) new_args[["error_threshold"]] <- error_threshold
  job_input <- handle_job_input(job, new_args, c("raster", "reproject"))
  if (job_input$should_extend) {
    return(extend_gdal_pipeline(job_input$job, c("raster", "reproject"), new_args))
  } else {
    merged_args <- job_input$merged_args
  }

  new_gdal_job(command_path = c("raster", "reproject"), arguments = merged_args)
}

