# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.13.3
# ===================================================================

#' @title create: Create a A.TOC index from CADRG frames
#' @description
#' Create a A.TOC index from CADRG frames.
#' 
#' See \url{https://gdal.org/en/release-3.13/programs/gdal_driver_rpftoc_create.html} for detailed GDAL documentation.
#' @param input Input directory (required). Can also be a [gdal_job] object to extend a pipeline
#' @param output Output filename
#' @param scale (Reciprocal) scale (e.g. 1000000) (Integer). Minimum: `0`
#' @param producer_id Producer (short) identification
#' @param producer_name Producer name
#' @param country_code ISO country code for security
#' @param classification Index classification. Choices: "U", "R", "C", "S", "T" (Default: `U`)
#' @param ... Parameter aliases and synonyms for backward compatibility. See `?gdal_parameter_aliases` for details.
#' @return A [gdal_job] object.
#' @family gdal_driver_utilities
#' @examples
#' \dontrun{
#' # TODO: No examples available for gdal_driver_rpftoc_create.
#' # See GDAL documentation at:
#' https://gdal.org/en/release-3.13/programs/gdal_driver_rpftoc_create.html
#' job <- gdal_driver_rpftoc_create()
#' # gdal_job_run(job)
#' }
#' @export
gdal_driver_rpftoc_create <- function(input,
  output = NULL,
  scale = NULL,
  producer_id = NULL,
  producer_name = NULL,
  country_code = NULL,
  classification = NULL,
  ...) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(scale)) new_args[["scale"]] <- scale
  if (!missing(producer_id)) new_args[["producer_id"]] <- producer_id
  if (!missing(producer_name)) new_args[["producer_name"]] <- producer_name
  if (!missing(country_code)) new_args[["country_code"]] <- country_code
  if (!missing(classification)) new_args[["classification"]] <- classification


  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("driver", "rpftoc", "create"), new_args))
  }


  merged_args <- .merge_alias_parameters(list(...), new_args)
  .update_intent_mapping <- NULL
  .update_intent <- infer_update_intent("gdal_driver_rpftoc_create", merged_args, .update_intent_mapping)

  .arg_mapping <- list(
    input = list(min_count = 0, max_count = 1),
    output = list(min_count = 0, max_count = 1),
    scale = list(min_count = 0, max_count = 1),
    producer_id = list(min_count = 0, max_count = 1),
    producer_name = list(min_count = 0, max_count = 1),
    country_code = list(min_count = 0, max_count = 1),
    classification = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("driver", "rpftoc", "create"), arguments = merged_args, arg_mapping = .arg_mapping, update_intent = .update_intent)
}

