# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.12.0
# Generation date: 2025-12-14
# ===================================================================

#' @title refresh: Refresh overviews
#' @description
#' Refresh overviews.
#' 
#' See \url{https://gdal.org/en/3.12.0/programs/gdal_raster_overview_refresh.html} for detailed GDAL documentation.
#' @param dataset Dataset (to be updated in-place, unless --external) (Dataset path) (required). Can also be a [gdal_job] object to extend a pipeline
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s) (Advanced)
#' @param external Refresh external overviews (Logical)
#' @param resampling Resampling method. Choices: nearest, average, cubic, cubicspline, lanczos, ...
#' @param levels Levels / decimation factors (Integer vector). Minimum: `2`. `0` to `2147483647` value(s)
#' @param bbox Bounding box to refresh. Exactly `4` value(s)
#' @param like Use extent of dataset(s) (Character vector). `0` to `2147483647` value(s)
#' @param use_source_timestamp Use timestamp of VRT or GTI sources as refresh criterion (Logical)
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples
#' \dontrun{
#' # TODO: No examples available for gdal_raster_overview_refresh.
#' # See GDAL documentation: https://gdal.org/programs/gdal-raster-overview-refresh.html
#' job <- gdal_raster_overview_refresh()
#' # gdal_job_run(job)
#' }
#' @export
gdal_raster_overview_refresh <- function(dataset,
  open_option = NULL,
  external = FALSE,
  resampling = NULL,
  levels = NULL,
  bbox = NULL,
  like = NULL,
  use_source_timestamp = FALSE) {
  new_args <- list()
  if (!missing(dataset)) new_args[["dataset"]] <- dataset
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(external)) new_args[["external"]] <- external
  if (!missing(resampling)) new_args[["resampling"]] <- resampling
  if (!missing(levels)) new_args[["levels"]] <- levels
  if (!missing(bbox)) new_args[["bbox"]] <- bbox
  if (!missing(like)) new_args[["like"]] <- like
  if (!missing(use_source_timestamp)) new_args[["use_source_timestamp"]] <- use_source_timestamp

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(dataset) && inherits(dataset, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- dataset
    new_args[["dataset"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("raster", "overview", "refresh"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    dataset = list(min_count = 0, max_count = 1),
    open_option = list(min_count = 0, max_count = 2147483647),
    external = list(min_count = 0, max_count = 1),
    resampling = list(min_count = 0, max_count = 1),
    levels = list(min_count = 0, max_count = 2147483647),
    bbox = list(min_count = 4, max_count = 4),
    like = list(min_count = 0, max_count = 2147483647),
    use_source_timestamp = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("raster", "overview", "refresh"), arguments = merged_args, arg_mapping = .arg_mapping)
}

