# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.12.0
# Generation date: 2025-12-14
# ===================================================================

#' @title proximity: Produces a raster proximity map
#' @description
#' Produces a raster proximity map.
#' 
#' See \url{https://gdal.org/en/3.12.0/programs/gdal_raster_proximity.html} for detailed GDAL documentation.
#' @param input Input raster datasets (required). Exactly `1` value(s). Can also be a [gdal_job] object to extend a pipeline
#' @param input_format Input formats (Character vector). `0` to `2147483647` value(s) (Advanced)
#' @param output Output raster dataset (Dataset path) (required)
#' @param output_format Output format ("GDALG" allowed)
#' @param output_data_type Output data type. Choices: Byte, Int8, UInt16, Int16, UInt32, ... (Default: `Float32`)
#' @param target_values Target pixel values. `0` to `2147483647` value(s)
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s) (Advanced)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s)
#' @param overwrite Whether overwriting existing output is allowed (Logical) (Default: `false`)
#' @param append Append as a subdataset to existing output (Logical) (Default: `false`)
#' @param band Input band (1-based index) (Integer)
#' @param distance_units Distance units. Choices: pixel, geo (Default: `pixel`)
#' @param max_distance Maximum distance. The nodata value will be used for pixels beyond this distance (Default: `0`)
#' @param fixed_value Fixed value for the pixels that are beyond the maximum distance (instead of the actual distance) (Default: `0`). Minimum: `0`
#' @param nodata Specify a nodata value to use for pixels that are beyond the maximum distance
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples

#' job <- gdal_raster_proximity(input = "input.tif", output = "output.tif", max_distance = 3)
#' \dontrun{
#'   result <- gdal_job_run(job)
#' }
#' @export
gdal_raster_proximity <- function(input,
  input_format = NULL,
  output,
  output_format = NULL,
  output_data_type = NULL,
  target_values = NULL,
  open_option = NULL,
  creation_option = NULL,
  overwrite = FALSE,
  append = FALSE,
  band = NULL,
  distance_units = NULL,
  max_distance = NULL,
  fixed_value = NULL,
  nodata = NULL) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(output_data_type)) new_args[["output_data_type"]] <- output_data_type
  if (!missing(target_values)) new_args[["target_values"]] <- target_values
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(append)) new_args[["append"]] <- append
  if (!missing(band)) new_args[["band"]] <- band
  if (!missing(distance_units)) new_args[["distance_units"]] <- distance_units
  if (!missing(max_distance)) new_args[["max_distance"]] <- max_distance
  if (!missing(fixed_value)) new_args[["fixed_value"]] <- fixed_value
  if (!missing(nodata)) new_args[["nodata"]] <- nodata

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("raster", "proximity"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    input = list(min_count = 1, max_count = 1),
    input_format = list(min_count = 0, max_count = 2147483647),
    output = list(min_count = 0, max_count = 1),
    output_format = list(min_count = 0, max_count = 1),
    output_data_type = list(min_count = 0, max_count = 1),
    target_values = list(min_count = 0, max_count = 2147483647),
    open_option = list(min_count = 0, max_count = 2147483647),
    creation_option = list(min_count = 0, max_count = 2147483647),
    overwrite = list(min_count = 0, max_count = 1),
    append = list(min_count = 0, max_count = 1),
    band = list(min_count = 0, max_count = 1),
    distance_units = list(min_count = 0, max_count = 1),
    max_distance = list(min_count = 0, max_count = 1),
    fixed_value = list(min_count = 0, max_count = 1),
    nodata = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("raster", "proximity"), arguments = merged_args, arg_mapping = .arg_mapping)
}

