# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.12.0
# Generation date: 2025-12-14
# ===================================================================

#' @title rgb-to-palette: Convert a RGB image into a pseudo-color / paletted image
#' @description
#' Convert a RGB image into a pseudo-color / paletted image.
#' 
#' See \url{https://gdal.org/en/3.12.0/programs/gdal_raster_rgb-to-palette.html} for detailed GDAL documentation.
#' @param input Input raster datasets (required). Exactly `1` value(s). Can also be a [gdal_job] object to extend a pipeline
#' @param input_format Input formats (Character vector). `0` to `2147483647` value(s) (Advanced)
#' @param output Output raster dataset (Dataset path) (required)
#' @param output_format Output format ("GDALG" allowed)
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s) (Advanced)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s)
#' @param overwrite Whether overwriting existing output is allowed (Logical) (Default: `false`)
#' @param append Append as a subdataset to existing output (Logical) (Default: `false`)
#' @param color_count Select the number of colors in the generated color table (Integer) (Default: `256`). Range: (`2` to `256`)
#' @param color_map Color map filename
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples

#' job <- gdal_raster_rgb_to_palette(input = "input.tif", output = "output.png")
#' \dontrun{
#'   result <- gdal_job_run(job)
#' }
#' @export
gdal_raster_rgb_to_palette <- function(input,
  input_format = NULL,
  output,
  output_format = NULL,
  open_option = NULL,
  creation_option = NULL,
  overwrite = FALSE,
  append = FALSE,
  color_count = NULL,
  color_map = NULL) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(append)) new_args[["append"]] <- append
  if (!missing(color_count)) new_args[["color_count"]] <- color_count
  if (!missing(color_map)) new_args[["color_map"]] <- color_map

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("raster", "rgb-to-palette"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    input = list(min_count = 1, max_count = 1),
    input_format = list(min_count = 0, max_count = 2147483647),
    output = list(min_count = 0, max_count = 1),
    output_format = list(min_count = 0, max_count = 1),
    open_option = list(min_count = 0, max_count = 2147483647),
    creation_option = list(min_count = 0, max_count = 2147483647),
    overwrite = list(min_count = 0, max_count = 1),
    append = list(min_count = 0, max_count = 1),
    color_count = list(min_count = 0, max_count = 1),
    color_map = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("raster", "rgb-to-palette"), arguments = merged_args, arg_mapping = .arg_mapping)
}

