# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.12.2
# Generation date: 2026-03-19
# ===================================================================

#' @title zonal-stats: Calculate raster zonal statistics
#' @description
#' Calculate raster zonal statistics
#' 
#' See \url{https://gdal.org/en/3.12.2/programs/gdal_raster_zonal-stats.html} for detailed GDAL documentation.
#' @param input Input raster datasets. Format: `NA`. Choices: NULL (Default: `NULL`) (required). Minimum: `NA`. Exactly `1` value(s). Can also be a [gdal_job] object to extend a pipeline
#' @param input_format Input formats (Character vector). Format: `NA`. Choices: NULL (Default: `NULL`). Minimum: `NA`. `0` to `2147483647` value(s) (Advanced)
#' @param output Output vector dataset (Dataset path) (required)
#' @param output_format Output format ("GDALG" allowed). Format: `NA`. Choices: NULL (Default: `NULL`). Minimum: `NA`
#' @param output_open_option Output open options (Character vector). Format: `<KEY>=<VALUE>`. Choices: NULL (Default: `NULL`). Minimum: `NA`. `0` to `2147483647` value(s) (Advanced)
#' @param output_layer Output layer name. Format: `NA`. Choices: NULL (Default: `NULL`). Minimum: `NA`
#' @param zones Dataset containing zone definitions (Dataset path). Format: `NA`. Choices: NULL (Default: `NULL`) (required). Minimum: `NA`
#' @param stat Statistic(s) to compute for each zone (Character vector). Format: `NA`. Choices: c("center_x", "center_y", "count", "coverage", "frac", "max", "max_center_x", "max_center_y", "mean", "median", "min", "minority", "min_center_x", "min_center_y", "mode", "stdev", "sum", "unique", "values", "variance", "variety", "weighted_mean", "weighted_stdev", "weighted_sum", "weighted_variance", "weights") (Default: `NULL`) (required). Minimum: `1`. `0` to `2147483647` value(s)
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>`. Choices: NULL (Default: `NULL`). Minimum: `NA`. `0` to `2147483647` value(s) (Advanced)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`. Choices: NULL (Default: `NULL`). Minimum: `NA`. `0` to `2147483647` value(s)
#' @param layer_creation_option Layer creation option (Character vector). Format: `<KEY>=<VALUE>`. Choices: NULL (Default: `NULL`). Minimum: `NA`. `0` to `2147483647` value(s)
#' @param overwrite Whether overwriting existing output is allowed (Logical). Format: `NA`. Choices: NULL (Default: `FALSE`). Minimum: `NA`
#' @param update Whether to open existing dataset in update mode (Logical). Format: `NA`. Choices: NULL (Default: `FALSE`). Minimum: `NA`
#' @param overwrite_layer Whether overwriting existing output is allowed (Logical). Format: `NA`. Choices: NULL (Default: `FALSE`). Minimum: `NA`
#' @param append Whether appending to existing layer is allowed (Logical). Format: `NA`. Choices: NULL (Default: `FALSE`). Minimum: `NA`
#' @param upsert Upsert features (implies 'append') (Logical). Format: `NA`. Choices: NULL (Default: `NULL`). Minimum: `NA` (Advanced)
#' @param skip_errors Skip errors when writing features (Logical). Format: `NA`. Choices: NULL (Default: `NULL`). Minimum: `NA`
#' @param band Input band(s) (1-based index) (Integer vector). Format: `NA`. Choices: NULL (Default: `NULL`). Minimum: `NA`. `0` to `2147483647` value(s)
#' @param zones_band Band from which zones should be read (Integer). Format: `NA`. Choices: NULL (Default: `NULL`). Minimum: `NA`
#' @param zones_layer Layer from which zones should be read. Format: `NA`. Choices: NULL (Default: `NULL`). Minimum: `NA`
#' @param weights Weighting raster dataset (Dataset path). Format: `NA`. Choices: NULL (Default: `NULL`). Minimum: `NA`
#' @param weights_band Band from which weights should be read (Integer). Format: `NA`. Choices: NULL (Default: `1`). Minimum: `NA`
#' @param pixels Method to determine which pixels are included in stat calculation.. Format: `NA`. Choices: c("default", "fractional", "all-touched") (Default: `NULL`). Minimum: `NA`
#' @param include_field Fields from polygon zones to include in output (Character vector). Format: `NA`. Choices: NULL (Default: `NULL`). Minimum: `NA`. `0` to `2147483647` value(s)
#' @param strategy For polygon zones, whether to iterate over input features or raster chunks. Format: `NA`. Choices: c("feature", "raster") (Default: `feature`). Minimum: `NA`
#' @param chunk_size Maximum size of raster chunks read into memory. Format: `NA`. Choices: NULL (Default: `5%`). Minimum: `NA`
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples
#' \dontrun{
#' # TODO: No examples available for gdal_raster_zonal_stats.
#' # See GDAL documentation: https://gdal.org/programs/gdal-raster-zonal-stats.html
#' job <- gdal_raster_zonal_stats()
#' # gdal_job_run(job)
#' }
#' @export
gdal_raster_zonal_stats <- function(input,
  input_format = NULL,
  output,
  output_format = NULL,
  output_open_option = NULL,
  output_layer = NULL,
  zones,
  stat,
  open_option = NULL,
  creation_option = NULL,
  layer_creation_option = NULL,
  overwrite = FALSE,
  update = FALSE,
  overwrite_layer = FALSE,
  append = FALSE,
  upsert = FALSE,
  skip_errors = FALSE,
  band = NULL,
  zones_band = NULL,
  zones_layer = NULL,
  weights = NULL,
  weights_band = NULL,
  pixels = NULL,
  include_field = NULL,
  strategy = NULL,
  chunk_size = NULL) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(output_open_option)) new_args[["output_open_option"]] <- output_open_option
  if (!missing(output_layer)) new_args[["output_layer"]] <- output_layer
  if (!missing(zones)) new_args[["zones"]] <- zones
  if (!missing(stat)) new_args[["stat"]] <- stat
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(layer_creation_option)) new_args[["layer_creation_option"]] <- layer_creation_option
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(update)) new_args[["update"]] <- update
  if (!missing(overwrite_layer)) new_args[["overwrite_layer"]] <- overwrite_layer
  if (!missing(append)) new_args[["append"]] <- append
  if (!missing(upsert)) new_args[["upsert"]] <- upsert
  if (!missing(skip_errors)) new_args[["skip_errors"]] <- skip_errors
  if (!missing(band)) new_args[["band"]] <- band
  if (!missing(zones_band)) new_args[["zones_band"]] <- zones_band
  if (!missing(zones_layer)) new_args[["zones_layer"]] <- zones_layer
  if (!missing(weights)) new_args[["weights"]] <- weights
  if (!missing(weights_band)) new_args[["weights_band"]] <- weights_band
  if (!missing(pixels)) new_args[["pixels"]] <- pixels
  if (!missing(include_field)) new_args[["include_field"]] <- include_field
  if (!missing(strategy)) new_args[["strategy"]] <- strategy
  if (!missing(chunk_size)) new_args[["chunk_size"]] <- chunk_size

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("raster", "zonal-stats"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    input = list(min_count = 1, max_count = 1),
    input_format = list(min_count = 0, max_count = 2147483647),
    output = list(min_count = 0, max_count = 1),
    output_format = list(min_count = NA, max_count = NA),
    output_open_option = list(min_count = 0, max_count = 2147483647),
    output_layer = list(min_count = NA, max_count = NA),
    zones = list(min_count = NA, max_count = NA),
    stat = list(min_count = 0, max_count = 2147483647),
    open_option = list(min_count = 0, max_count = 2147483647),
    creation_option = list(min_count = 0, max_count = 2147483647),
    layer_creation_option = list(min_count = 0, max_count = 2147483647),
    overwrite = list(min_count = NA, max_count = NA),
    update = list(min_count = NA, max_count = NA),
    overwrite_layer = list(min_count = NA, max_count = NA),
    append = list(min_count = NA, max_count = NA),
    upsert = list(min_count = NA, max_count = NA),
    skip_errors = list(min_count = NA, max_count = NA),
    band = list(min_count = 0, max_count = 2147483647),
    zones_band = list(min_count = NA, max_count = NA),
    zones_layer = list(min_count = NA, max_count = NA),
    weights = list(min_count = NA, max_count = NA),
    weights_band = list(min_count = NA, max_count = NA),
    pixels = list(min_count = NA, max_count = NA),
    include_field = list(min_count = 0, max_count = 2147483647),
    strategy = list(min_count = NA, max_count = NA),
    chunk_size = list(min_count = NA, max_count = NA)
  )

  new_gdal_job(command_path = c("raster", "zonal-stats"), arguments = merged_args, arg_mapping = .arg_mapping)
}

