# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.13.2
# ===================================================================

#' @title validate: Validate conformance of a GeoPackage dataset against the GeoPackage...
#' @description
#' Validate if GeoPackage dataset conforms to the GeoPackage specification.
#' 
#' See \url{https://gdal.org/en/release-3.13/programs/gdal_driver_gpkg_validate.html} for detailed GDAL documentation.
#' @param dataset GeoPackage dataset (Dataset path) (required). Can also be a [gdal_job] object to extend a pipeline
#' @param full_check Whether to perform full check (Logical) (Default: `false`)
#' @param verbose Turn on verbose mode (Logical)
#' @param quiet Quiet mode (no progress bar or warning message) (Logical) (Common)
#' @param ... Parameter aliases and synonyms for backward compatibility. See `?gdal_parameter_aliases` for details.
#' @return A [gdal_job] object.
#' @family gdal_driver_utilities
#' @examples

#' job <- gdal_driver_gpkg_validate(dataset = "my.gpkg")
#' \dontrun{
#'   result <- gdal_job_run(job)
#' }
#' @export
gdal_driver_gpkg_validate <- function(dataset,
  full_check = FALSE,
  verbose = FALSE,
  quiet = FALSE,
  ...) {
  new_args <- list()
  if (!missing(dataset)) new_args[["dataset"]] <- dataset
  if (!missing(full_check)) new_args[["full_check"]] <- full_check
  if (!missing(verbose)) new_args[["verbose"]] <- verbose
  if (!missing(quiet)) new_args[["quiet"]] <- quiet


  if (!missing(dataset) && inherits(dataset, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- dataset
    new_args[["dataset"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("driver", "gpkg", "validate"), new_args))
  }


  merged_args <- .merge_alias_parameters(list(...), new_args)
  .update_intent_mapping <- NULL
  .update_intent <- infer_update_intent("gdal_driver_gpkg_validate", merged_args, .update_intent_mapping)

  .arg_mapping <- list(
    dataset = list(min_count = 0, max_count = 1),
    full_check = list(min_count = 0, max_count = 1),
    verbose = list(min_count = 0, max_count = 1),
    quiet = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("driver", "gpkg", "validate"), arguments = merged_args, arg_mapping = .arg_mapping, update_intent = .update_intent)
}

