# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# ===================================================================

#' @title Generate a slope map
#' @description
#' Auto-generated GDAL CLI wrapper.
#' Generate a slope map
#' 
#' See \url{https://gdal.org/en/stable/programs/gdal_raster_slope.html} for detailed GDAL documentation.
#' @param job A gdal_job object from a piped operation, or NULL
#' @param input Input raster dataset (Dataset path) (required)
#' @param input_format Input formats (Character vector). `0` to `2147483647` value(s) (Advanced)
#' @param output Output raster dataset (Dataset path) (required)
#' @param output_format Output format ("GDALG" allowed)
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s) (Advanced)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s)
#' @param overwrite Whether overwriting existing output is allowed (Logical) (Default: `false`)
#' @param band Input band (1-based index) (Integer) (Default: `1`)
#' @param unit Unit in which to express slopes. Choices: degree, percent (Default: `degree`)
#' @param xscale Ratio of vertical units to horizontal X axis units. Minimum: `0`
#' @param yscale Ratio of vertical units to horizontal Y axis units. Minimum: `0`
#' @param gradient_alg Algorithm used to compute terrain gradient. Choices: Horn, ZevenbergenThorne (Default: `Horn`)
#' @param no_edges Do not try to interpolate values at dataset edges or close to nodata values (Logical)
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples
#' # Create a GDAL job (not executed)
#' job <- gdal_raster_slope(input = "data.tif")
#' #
#' # Inspect the job (optional)
#' # print(job)

#' @export
gdal_raster_slope <- function(job = NULL,
  input = NULL,
  input_format = NULL,
  output = NULL,
  output_format = NULL,
  open_option = NULL,
  creation_option = NULL,
  overwrite = FALSE,
  band = NULL,
  unit = NULL,
  xscale = NULL,
  yscale = NULL,
  gradient_alg = NULL,
  no_edges = FALSE) {
  # Collect function arguments
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(band)) new_args[["band"]] <- band
  if (!missing(unit)) new_args[["unit"]] <- unit
  if (!missing(xscale)) new_args[["xscale"]] <- xscale
  if (!missing(yscale)) new_args[["yscale"]] <- yscale
  if (!missing(gradient_alg)) new_args[["gradient_alg"]] <- gradient_alg
  if (!missing(no_edges)) new_args[["no_edges"]] <- no_edges
  job_input <- handle_job_input(job, new_args, c("raster", "slope"))
  if (job_input$should_extend) {
    # Extend pipeline from existing job
    return(extend_gdal_pipeline(job_input$job, c("raster", "slope"), new_args))
  } else {
    # Create new job with merged arguments
    merged_args <- job_input$merged_args
  }

  new_gdal_job(command_path = c("raster", "slope"), arguments = merged_args)
}

