# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.12.0
# Generation date: 2025-12-14
# ===================================================================

#' @title pipeline: Process a dataset applying several steps
#' @description
#' Process a dataset applying several steps.
#' 
#' See \url{https://gdal.org/en/3.12.0/programs/gdal_pipeline.html} for detailed GDAL documentation.
#' @param input Input raster or vector datasets. `1` to `2147483647` value(s). Can also be a [gdal_job] object to extend a pipeline
#' @param output Output raster or vector dataset (Dataset path)
#' @param output_format Output format ("GDALG" allowed)
#' @param pipeline Pipeline string or filename
#' @return A [gdal_job] object.
#' @family gdal_pipeline_utilities
#' @examples
#' \dontrun{
#' # TODO: No examples available for gdal_pipeline.
#' # See GDAL documentation: https://gdal.org/programs/gdal-pipeline.html
#' job <- gdal_pipeline()
#' # gdal_job_run(job)
#' }
#' @export
gdal_pipeline <- function(input = NULL,
  output = NULL,
  output_format = NULL,
  pipeline = NULL) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(pipeline)) new_args[["pipeline"]] <- pipeline

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("pipeline"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    input = list(min_count = 1, max_count = 2147483647),
    output = list(min_count = 0, max_count = 1),
    output_format = list(min_count = 0, max_count = 1),
    pipeline = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("pipeline"), arguments = merged_args, arg_mapping = .arg_mapping)
}

