# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# ===================================================================

#' @title Simplify geometries of a vector dataset.
#' @description
#' Auto-generated GDAL CLI wrapper.
#' Simplify geometries of a vector dataset.
#' @param input_format GDAL argument
#' @param open_option GDAL argument
#' @param input GDAL argument
#' @param input_layer GDAL argument
#' @param output_format GDAL argument
#' @param creation_option GDAL argument
#' @param layer_creation_option GDAL argument
#' @param overwrite GDAL argument
#' @param update GDAL argument
#' @param overwrite_layer GDAL argument
#' @param append GDAL argument
#' @param output_layer GDAL argument
#' @param active_layer GDAL argument
#' @param active_geometry GDAL argument
#' @param tolerance GDAL argument
#' @return A [gdal_job] object.
#' @family gdal_vector_utilities
#' @examples
#' \dontrun{
#' gdal_vector_geom_simplify(...) |> gdal_run()
#' }

#' @export
gdal_vector_geom_simplify <- function(input_format = NULL,
  open_option = NULL,
  input,
  input_layer = NULL,
  output_format = NULL,
  creation_option = NULL,
  layer_creation_option = NULL,
  overwrite = FALSE,
  update = FALSE,
  overwrite_layer = FALSE,
  append = FALSE,
  output_layer = NULL,
  active_layer = NULL,
  active_geometry = NULL,
  tolerance = NULL) {
  # Collect arguments
  args <- list()
  if (!missing(input_format)) args[["input_format"]] <- input_format
  if (!missing(open_option)) args[["open_option"]] <- open_option
  if (!missing(input)) args[["input"]] <- input
  if (!missing(input_layer)) args[["input_layer"]] <- input_layer
  if (!missing(output_format)) args[["output_format"]] <- output_format
  if (!missing(creation_option)) args[["creation_option"]] <- creation_option
  if (!missing(layer_creation_option)) args[["layer_creation_option"]] <- layer_creation_option
  if (!missing(overwrite)) args[["overwrite"]] <- overwrite
  if (!missing(update)) args[["update"]] <- update
  if (!missing(overwrite_layer)) args[["overwrite_layer"]] <- overwrite_layer
  if (!missing(append)) args[["append"]] <- append
  if (!missing(output_layer)) args[["output_layer"]] <- output_layer
  if (!missing(active_layer)) args[["active_layer"]] <- active_layer
  if (!missing(active_geometry)) args[["active_geometry"]] <- active_geometry
  if (!missing(tolerance)) args[["tolerance"]] <- tolerance

  new_gdal_job(command_path = c("gdal", "vector", "geom", "simplify"), arguments = args)
}

