# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.12.0
# Generation date: 2025-12-14
# ===================================================================

#' @title blend: Blend/compose two raster datasets
#' @description
#' Blend/compose two raster datasets
#' 
#' See \url{https://gdal.org/en/3.12.0/programs/gdal_raster_blend.html} for detailed GDAL documentation.
#' @param input Input raster dataset. Format: `COLOR-INPUT` (required). Exactly `1` value(s). Can also be a [gdal_job] object to extend a pipeline
#' @param input_format Input formats (Character vector). `0` to `2147483647` value(s) (Advanced)
#' @param output Output raster dataset (Dataset path) (required)
#' @param output_format Output format ("GDALG" allowed)
#' @param overlay Overlay dataset (Dataset path) (required)
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s) (Advanced)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s)
#' @param overwrite Whether overwriting existing output is allowed (Logical) (Default: `false`)
#' @param append Append as a subdataset to existing output (Logical) (Default: `false`)
#' @param operator Composition operator. Choices: src-over, hsv-value (Default: `src-over`)
#' @param opacity Opacity percentage to apply to the overlay dataset (0=fully transparent, 100=full use of overlay opacity) (Integer) (Default: `100`). Range: (`0` to `100`)
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples
#' \dontrun{
#' # TODO: No examples available for gdal_raster_blend.
#' # See GDAL documentation: https://gdal.org/programs/gdal-raster-blend.html
#' job <- gdal_raster_blend()
#' # gdal_job_run(job)
#' }
#' @export
gdal_raster_blend <- function(input,
  input_format = NULL,
  output,
  output_format = NULL,
  overlay,
  open_option = NULL,
  creation_option = NULL,
  overwrite = FALSE,
  append = FALSE,
  operator = NULL,
  opacity = NULL) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(overlay)) new_args[["overlay"]] <- overlay
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(append)) new_args[["append"]] <- append
  if (!missing(operator)) new_args[["operator"]] <- operator
  if (!missing(opacity)) new_args[["opacity"]] <- opacity

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("raster", "blend"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    input = list(min_count = 1, max_count = 1),
    input_format = list(min_count = 0, max_count = 2147483647),
    output = list(min_count = 0, max_count = 1),
    output_format = list(min_count = 0, max_count = 1),
    overlay = list(min_count = 0, max_count = 1),
    open_option = list(min_count = 0, max_count = 2147483647),
    creation_option = list(min_count = 0, max_count = 2147483647),
    overwrite = list(min_count = 0, max_count = 1),
    append = list(min_count = 0, max_count = 1),
    operator = list(min_count = 0, max_count = 1),
    opacity = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("raster", "blend"), arguments = merged_args, arg_mapping = .arg_mapping)
}

