# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# ===================================================================

#' @title Remove small polygons from a raster dataset.
#' @description
#' Auto-generated GDAL CLI wrapper.
#' Remove small polygons from a raster dataset.
#' @param open_option GDAL argument
#' @param input_format GDAL argument
#' @param input GDAL argument
#' @param output_format GDAL argument
#' @param creation_option GDAL argument
#' @param overwrite GDAL argument
#' @param mask GDAL argument
#' @param band GDAL argument
#' @param size_threshold GDAL argument
#' @param connect_diagonal_pixels GDAL argument
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples
#' \dontrun{
#' gdal_raster_sieve(...) |> gdal_run()
#' }

#' @export
gdal_raster_sieve <- function(open_option = NULL,
  input_format = NULL,
  input = NULL,
  output_format = NULL,
  creation_option = NULL,
  overwrite = FALSE,
  mask = NULL,
  band = NULL,
  size_threshold = NULL,
  connect_diagonal_pixels = FALSE) {
  # Collect arguments
  args <- list()
  if (!missing(open_option)) args[["open_option"]] <- open_option
  if (!missing(input_format)) args[["input_format"]] <- input_format
  if (!missing(input)) args[["input"]] <- input
  if (!missing(output_format)) args[["output_format"]] <- output_format
  if (!missing(creation_option)) args[["creation_option"]] <- creation_option
  if (!missing(overwrite)) args[["overwrite"]] <- overwrite
  if (!missing(mask)) args[["mask"]] <- mask
  if (!missing(band)) args[["band"]] <- band
  if (!missing(size_threshold)) args[["size_threshold"]] <- size_threshold
  if (!missing(connect_diagonal_pixels)) args[["connect_diagonal_pixels"]] <- connect_diagonal_pixels

  new_gdal_job(command_path = c("gdal", "raster", "sieve"), arguments = args)
}

