# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.13.3
# ===================================================================

#' @title add: Adding overviews
#' @description
#' `gdal raster overview add` can be used to build or rebuild overview images for most supported file formats with one of several downsampling algorithms. Starting with GDAL 3.12, gdal raster overview add can be used as a step of a pipeline. In that case virtual overviews are generated at the output of the step, and can potentially be materialized in the final write step, when writing a GeoTIFF file with the COPY_SRC_OVERVIEWS creation option, or when writing to a COG (Cloud Optimized GeoTIFF) file.
#' 
#' See \url{https://gdal.org/en/release-3.13/programs/gdal_raster_overview_add.html} for detailed GDAL documentation.
#' @param input Dataset (to be updated in-place, unless --external) (required). `0` to `1` value(s). Can also be a [gdal_job] object to extend a pipeline
#' @param quiet Quiet mode (no progress bar or warning message) (Logical) (Common)
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>` (Advanced)
#' @param overview_src Source overview dataset
#' @param external Add external overviews (Logical)
#' @param resampling Resampling method. Choices: "nearest", "average", "cubic", "cubicspline", "lanczos", ...
#' @param levels Levels / decimation factors (Integer vector). Minimum: `2`
#' @param min_size Maximum width or height of the smallest overview level. (Integer). Minimum: `1`
#' @param creation_option Overview creation option (Character vector). Format: `<KEY>=<VALUE>`
#' @param ... Parameter aliases and synonyms for backward compatibility. See `?gdal_parameter_aliases` for details.
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples
#' \dontrun{
#' # TODO: No examples available for gdal_raster_overview_add.
#' # See GDAL documentation at:
#' https://gdal.org/en/release-3.13/programs/gdal_raster_overview_add.html
#' job <- gdal_raster_overview_add()
#' # gdal_job_run(job)
#' }
#' @export
gdal_raster_overview_add <- function(input,
  quiet = FALSE,
  open_option = NULL,
  overview_src = NULL,
  external = FALSE,
  resampling = NULL,
  levels = NULL,
  min_size = NULL,
  creation_option = NULL,
  ...) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(quiet)) new_args[["quiet"]] <- quiet
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(overview_src)) new_args[["overview_src"]] <- overview_src
  if (!missing(external)) new_args[["external"]] <- external
  if (!missing(resampling)) new_args[["resampling"]] <- resampling
  if (!missing(levels)) new_args[["levels"]] <- levels
  if (!missing(min_size)) new_args[["min_size"]] <- min_size
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option


  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("raster", "overview", "add"), new_args))
  }


  merged_args <- .merge_alias_parameters(list(...), new_args)
  .update_intent_mapping <- list(dataset = list(by_default = TRUE, unless_any_of = "external"))
  .update_intent <- infer_update_intent("gdal_raster_overview_add", merged_args, .update_intent_mapping)

  .arg_mapping <- list(
    input = list(min_count = 0, max_count = 1),
    quiet = list(min_count = 0, max_count = 1),
    open_option = list(min_count = 0, max_count = 2147483647),
    overview_src = list(min_count = 0, max_count = 2147483647),
    external = list(min_count = 0, max_count = 1),
    resampling = list(min_count = 0, max_count = 1),
    levels = list(min_count = 0, max_count = 2147483647),
    min_size = list(min_count = 0, max_count = 1),
    creation_option = list(min_count = 0, max_count = 2147483647)
  )

  new_gdal_job(command_path = c("raster", "overview", "add"), arguments = merged_args, arg_mapping = .arg_mapping, update_intent = .update_intent)
}

