# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# ===================================================================

#' @title scale: Scale the values of the bands of a raster dataset
#' @description
#' Scale the values of the bands of a raster dataset.
#' 
#' See \url{https://gdal.org/en/stable/programs/gdal_raster_scale.html} for detailed GDAL documentation.
#' @param job A gdal_job object from a piped operation, or NULL
#' @param input Input raster dataset (Dataset path) (required)
#' @param output Output raster dataset (Dataset path) (required)
#' @param input_format Input formats (Character vector). `0` to `2147483647` value(s) (Advanced)
#' @param output_format Output format ("GDALG" allowed)
#' @param output_data_type Output data type. Choices: Byte, Int8, UInt16, Int16, UInt32, ...
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s) (Advanced)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s)
#' @param overwrite Whether overwriting existing output is allowed (Logical) (Default: `false`)
#' @param band Select band to restrict the scaling (1-based index) (Integer)
#' @param src_min Minimum value of the source range
#' @param src_max Maximum value of the source range
#' @param dst_min Minimum value of the destination range
#' @param dst_max Maximum value of the destination range
#' @param exponent Exponent to apply non-linear scaling with a power function
#' @param no_clip Do not clip input values to \[srcmin, srcmax\] (Logical)
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples
#' @export
gdal_raster_scale <- function(job = NULL,
  input,
  output,
  input_format = NULL,
  output_format = NULL,
  output_data_type = NULL,
  open_option = NULL,
  creation_option = NULL,
  overwrite = FALSE,
  band = NULL,
  src_min = NULL,
  src_max = NULL,
  dst_min = NULL,
  dst_max = NULL,
  exponent = NULL,
  no_clip = FALSE) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(output_data_type)) new_args[["output_data_type"]] <- output_data_type
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(band)) new_args[["band"]] <- band
  if (!missing(src_min)) new_args[["src_min"]] <- src_min
  if (!missing(src_max)) new_args[["src_max"]] <- src_max
  if (!missing(dst_min)) new_args[["dst_min"]] <- dst_min
  if (!missing(dst_max)) new_args[["dst_max"]] <- dst_max
  if (!missing(exponent)) new_args[["exponent"]] <- exponent
  if (!missing(no_clip)) new_args[["no_clip"]] <- no_clip
  job_input <- handle_job_input(job, new_args, c("raster", "scale"))
  if (job_input$should_extend) {
    return(extend_gdal_pipeline(job_input$job, c("raster", "scale"), new_args))
  } else {
    merged_args <- job_input$merged_args
  }

  new_gdal_job(command_path = c("raster", "scale"), arguments = merged_args)
}

