# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# ===================================================================

#' @title Compute the footprint of a raster dataset.
#' @description
#' Auto-generated GDAL CLI wrapper.
#' Compute the footprint of a raster dataset.
#' @param open_option GDAL argument
#' @param input_format GDAL argument
#' @param input GDAL argument
#' @param output_format GDAL argument
#' @param output_layer GDAL argument
#' @param creation_option GDAL argument
#' @param layer_creation_option GDAL argument
#' @param append GDAL argument
#' @param overwrite GDAL argument
#' @param band GDAL argument
#' @param combine_bands GDAL argument
#' @param overview GDAL argument
#' @param src_nodata GDAL argument
#' @param coordinate_system GDAL argument
#' @param dst_crs GDAL argument
#' @param split_multipolygons GDAL argument
#' @param convex_hull GDAL argument
#' @param densify_distance GDAL argument
#' @param simplify_tolerance GDAL argument
#' @param min_ring_area GDAL argument
#' @param max_points GDAL argument
#' @param location_field GDAL argument
#' @param no_location_field GDAL argument
#' @param absolute_path GDAL argument
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples
#' \dontrun{
#' gdal_raster_footprint(...) |> gdal_run()
#' }

#' @export
gdal_raster_footprint <- function(open_option = NULL,
  input_format = NULL,
  input = NULL,
  output_format = NULL,
  output_layer = NULL,
  creation_option = NULL,
  layer_creation_option = NULL,
  append = FALSE,
  overwrite = FALSE,
  band = NULL,
  combine_bands = NULL,
  overview = NULL,
  src_nodata,
  coordinate_system = NULL,
  dst_crs = NULL,
  split_multipolygons = FALSE,
  convex_hull = FALSE,
  densify_distance = NULL,
  simplify_tolerance = NULL,
  min_ring_area = NULL,
  max_points = NULL,
  location_field = NULL,
  no_location_field = FALSE,
  absolute_path = FALSE) {
  # Collect arguments
  args <- list()
  if (!missing(open_option)) args[["open_option"]] <- open_option
  if (!missing(input_format)) args[["input_format"]] <- input_format
  if (!missing(input)) args[["input"]] <- input
  if (!missing(output_format)) args[["output_format"]] <- output_format
  if (!missing(output_layer)) args[["output_layer"]] <- output_layer
  if (!missing(creation_option)) args[["creation_option"]] <- creation_option
  if (!missing(layer_creation_option)) args[["layer_creation_option"]] <- layer_creation_option
  if (!missing(append)) args[["append"]] <- append
  if (!missing(overwrite)) args[["overwrite"]] <- overwrite
  if (!missing(band)) args[["band"]] <- band
  if (!missing(combine_bands)) args[["combine_bands"]] <- combine_bands
  if (!missing(overview)) args[["overview"]] <- overview
  if (!missing(src_nodata)) args[["src_nodata"]] <- src_nodata
  if (!missing(coordinate_system)) args[["coordinate_system"]] <- coordinate_system
  if (!missing(dst_crs)) args[["dst_crs"]] <- dst_crs
  if (!missing(split_multipolygons)) args[["split_multipolygons"]] <- split_multipolygons
  if (!missing(convex_hull)) args[["convex_hull"]] <- convex_hull
  if (!missing(densify_distance)) args[["densify_distance"]] <- densify_distance
  if (!missing(simplify_tolerance)) args[["simplify_tolerance"]] <- simplify_tolerance
  if (!missing(min_ring_area)) args[["min_ring_area"]] <- min_ring_area
  if (!missing(max_points)) args[["max_points"]] <- max_points
  if (!missing(location_field)) args[["location_field"]] <- location_field
  if (!missing(no_location_field)) args[["no_location_field"]] <- no_location_field
  if (!missing(absolute_path)) args[["absolute_path"]] <- absolute_path

  new_gdal_job(command_path = c("gdal", "raster", "footprint"), arguments = args)
}

