# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.13.1
# ===================================================================

#' @title scale: Scale the values of the bands of a raster dataset
#' @description
#' `gdal raster scale` can be used to rescale the input pixels values from the range --input-min to --input-max to the range --output-min to --output-max. It is also often necessary to reset the output datatype with the --ot switch. If omitted the output range is from the minimum value to the maximum value allowed for integer data types (for example from 0 to 255 for Byte output) or from 0 to 1 for floating-point data types. If omitted the input range is automatically computed from the source dataset. This may be a slow operation on a large source dataset, and if using it multiple times for several gdal_translate invocation, it might be beneficial to call ``gdal raster edit --stats \{source_dataset\}`` priorly to precompute statistics, for formats that support serializing statistics computations (GeoTIFF, VRT...) Source values are clipped to the range defined by ``srcmin`` and ``srcmax``, unless --no-clip is set. By default, the scaling is applied to all bands. It is possible to restrict it to a single band with --band and leave values of other bands unmodified. This command is the reverse operation of gdal_raster_unscale. This subcommand is also available as a potential step of gdal_raster_pipeline
#' 
#' See \url{https://gdal.org/en/release-3.13/programs/gdal_raster_scale.html} for detailed GDAL documentation.
#' @param input Input raster datasets (required). Exactly `1` value(s). Can also be a [gdal_job] object to extend a pipeline
#' @param input_format Input formats (Character vector) (Advanced)
#' @param input_min Minimum value of the source range
#' @param input_max Maximum value of the source range
#' @param output Output raster dataset (Dataset path) (required)
#' @param output_format Output format ("GDALG" allowed)
#' @param output_data_type Output data type. Choices: "UInt8", "Int8", "UInt16", "Int16", "UInt32", ...
#' @param output_min Minimum value of the destination range
#' @param output_max Maximum value of the destination range
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>` (Advanced)
#' @param quiet Quiet mode (no progress bar or warning message) (Logical) (Common)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`
#' @param overwrite Whether overwriting existing output dataset is allowed (Logical) (Default: `false`)
#' @param append Append as a subdataset to existing output (Logical) (Default: `false`)
#' @param band Select band to restrict the scaling (1-based index) (Integer)
#' @param exponent Exponent to apply non-linear scaling with a power function
#' @param no_clip Do not clip input values to \[innput-min, input-max\] (Logical)
#' @param ... Parameter aliases and synonyms for backward compatibility. See `?gdal_parameter_aliases` for details.
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples

#' job <- gdal_raster_scale(input = "uint16.tif", output = "byte.tif", overwrite = TRUE, 
#'     input_min = 0, input_max = 4095)
#' \dontrun{
#'   result <- gdal_job_run(job)
#' }
#' @export
gdal_raster_scale <- function(input,
  input_format = NULL,
  input_min = NULL,
  input_max = NULL,
  output,
  output_format = NULL,
  output_data_type = NULL,
  output_min = NULL,
  output_max = NULL,
  open_option = NULL,
  quiet = FALSE,
  creation_option = NULL,
  overwrite = FALSE,
  append = FALSE,
  band = NULL,
  exponent = NULL,
  no_clip = FALSE,
  ...) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(input_min)) new_args[["input_min"]] <- input_min
  if (!missing(input_max)) new_args[["input_max"]] <- input_max
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(output_data_type)) new_args[["output_data_type"]] <- output_data_type
  if (!missing(output_min)) new_args[["output_min"]] <- output_min
  if (!missing(output_max)) new_args[["output_max"]] <- output_max
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(quiet)) new_args[["quiet"]] <- quiet
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(append)) new_args[["append"]] <- append
  if (!missing(band)) new_args[["band"]] <- band
  if (!missing(exponent)) new_args[["exponent"]] <- exponent
  if (!missing(no_clip)) new_args[["no_clip"]] <- no_clip


  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("raster", "scale"), new_args))
  }


  merged_args <- .merge_alias_parameters(list(...), new_args)
  .update_intent_mapping <- NULL
  .update_intent <- infer_update_intent("gdal_raster_scale", merged_args, .update_intent_mapping)

  .arg_mapping <- list(
    input = list(min_count = 1, max_count = 1),
    input_format = list(min_count = 0, max_count = 2147483647),
    input_min = list(min_count = 0, max_count = 1),
    input_max = list(min_count = 0, max_count = 1),
    output = list(min_count = 0, max_count = 1),
    output_format = list(min_count = 0, max_count = 1),
    output_data_type = list(min_count = 0, max_count = 1),
    output_min = list(min_count = 0, max_count = 1),
    output_max = list(min_count = 0, max_count = 1),
    open_option = list(min_count = 0, max_count = 2147483647),
    quiet = list(min_count = 0, max_count = 1),
    creation_option = list(min_count = 0, max_count = 2147483647),
    overwrite = list(min_count = 0, max_count = 1),
    append = list(min_count = 0, max_count = 1),
    band = list(min_count = 0, max_count = 1),
    exponent = list(min_count = 0, max_count = 1),
    no_clip = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("raster", "scale"), arguments = merged_args, arg_mapping = .arg_mapping, update_intent = .update_intent)
}

