# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# ===================================================================

#' @title delete: Delete files located on GDAL Virtual System Interface (VSI)
#' @description
#' `gdal vsi delete` delete files and directories located on GDAL Virtual File Systems (compressed, network hosted, etc...): /vsimem, /vsizip, /vsitar, /vsicurl, ....
#' 
#' See \url{https://gdal.org/en/stable/programs/gdal_vsi_delete.html} for detailed GDAL documentation.
#' @param filename File or directory name to delete (required). Can also be a [gdal_job] object to extend a pipeline
#' @param recursive Delete directories recursively (Logical)
#' @return A [gdal_job] object.
#' @family gdal_vsi_utilities
#' @examples
#' \dontrun{
#' # TODO: Convert this GDAL CLI example to R parameters:
#' # Original: gdal vsi delete -r /vsis3/bucket/my_dir
#' # For help on available parameters, run: ?gdal_vsi_delete
#' job <- gdal_vsi_delete()
#' # gdal_job_run(job)
#' }
#' @export
gdal_vsi_delete <- function(filename,
  recursive = FALSE) {
  new_args <- list()
  if (!missing(filename)) new_args[["filename"]] <- filename
  if (!missing(recursive)) new_args[["recursive"]] <- recursive

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(filename) && inherits(filename, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- filename
    new_args[["filename"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("vsi", "delete"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    filename = list(min_count = 0, max_count = 1),
    recursive = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("vsi", "delete"), arguments = merged_args, arg_mapping = .arg_mapping)
}

