# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.12.2
# ===================================================================

#' @title Process a raster dataset applying several steps
#' @description
#' `gdal raster pipeline` can be used to process a raster dataset and perform various processing steps that accept raster and generate raster. For pipelines mixing raster and vector, consult gdal_pipeline. Most steps proceed in on-demand evaluation of raster blocks, unless otherwise stated in their documentation, without "materializing" the resulting dataset of the operation of each step. It may be desirable sometimes for performance purposes to proceed to materializing an intermediate dataset to disk using gdal_raster_materialize.
#' 
#' See \url{https://gdal.org/en/release-3.12/programs/gdal_raster_pipeline.html} for detailed GDAL documentation.
#' @param jobs A vector of gdal_job objects to execute in sequence, or NULL to use pipeline string
#' @param input Input raster datasets. `1` to `2147483647` value(s)
#' @param input_format Input formats (Character vector) (Advanced)
#' @param output Output raster dataset (Dataset path)
#' @param output_format Output format ("GDALG" allowed)
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>` (Advanced)
#' @param pipeline Pipeline string (ignored if jobs is provided)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`
#' @param overwrite Whether overwriting existing output is allowed (Logical) (Default: `false`)
#' @param append Append as a subdataset to existing output (Logical) (Default: `false`)
#' @param ... Parameter aliases and synonyms for backward compatibility. See `?gdal_parameter_aliases` for details.
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples

#' job <- gdal_raster_pipeline(
#'     input = c("in.tif", "!", "reproject", "!", "edit", "!", "write"), output = "out.tif", 
#'     overwrite = TRUE)
#' \dontrun{
#'   result <- gdal_job_run(job)
#' }
#' @export
gdal_raster_pipeline <- function(jobs = NULL,
  input = NULL,
  input_format = NULL,
  output = NULL,
  output_format = NULL,
  open_option = NULL,
  pipeline = NULL,
  creation_option = NULL,
  overwrite = FALSE,
  append = FALSE,
  ...) {

  if (!is.null(jobs)) {
    if (!is.list(jobs) && !is.vector(jobs)) {
      rlang::abort('jobs must be a list or vector of gdal_job objects')
    }
    for (i in seq_along(jobs)) {
      if (!inherits(jobs[[i]], 'gdal_job')) {
        rlang::abort(sprintf('jobs[[%d]] must be a gdal_job object', i))
      }
    }
    pipeline <- .build_pipeline_from_jobs(jobs)
  }


  args <- list()
  if (!missing(input)) args[["input"]] <- input
  if (!missing(input_format)) args[["input_format"]] <- input_format
  if (!missing(output)) args[["output"]] <- output
  if (!missing(output_format)) args[["output_format"]] <- output_format
  if (!missing(open_option)) args[["open_option"]] <- open_option
  if (!missing(pipeline)) args[["pipeline"]] <- pipeline
  if (!missing(creation_option)) args[["creation_option"]] <- creation_option
  if (!missing(overwrite)) args[["overwrite"]] <- overwrite
  if (!missing(append)) args[["append"]] <- append
  .update_intent <- "SAFE"

  .arg_mapping <- list(
    input = list(min_count = 1, max_count = 2147483647),
    input_format = list(min_count = 0, max_count = 2147483647),
    output = list(min_count = 0, max_count = 1),
    output_format = list(min_count = 0, max_count = 1),
    open_option = list(min_count = 0, max_count = 2147483647),
    pipeline = list(min_count = 0, max_count = 1),
    creation_option = list(min_count = 0, max_count = 2147483647),
    overwrite = list(min_count = 0, max_count = 1),
    append = list(min_count = 0, max_count = 1)
  )

  args <- .merge_alias_parameters(list(...), args)
  new_gdal_job(command_path = c("raster", "pipeline"), arguments = args, arg_mapping = .arg_mapping, update_intent = .update_intent)
}

