# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# ===================================================================

#' @title list: List content of a ZIP file, with SOZIP related information
#' @description
#' The gdal vsi sozip utility can be used to:
#' 
#' See \url{https://gdal.org/en/stable/programs/gdal_vsi_sozip_list.html} for detailed GDAL documentation.
#' @param job A gdal_job object from a piped operation, or NULL
#' @param input Input ZIP filename (required)
#' @return A [gdal_job] object.
#' @family gdal_vsi_utilities
#' @examples
#' @export
gdal_vsi_sozip_list <- function(job = NULL,
  input) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  job_input <- handle_job_input(job, new_args, c("vsi", "sozip", "list"))
  if (job_input$should_extend) {
    return(extend_gdal_pipeline(job_input$job, c("vsi", "sozip", "list"), new_args))
  } else {
    merged_args <- job_input$merged_args
  }

  new_gdal_job(command_path = c("vsi", "sozip", "list"), arguments = merged_args)
}

