# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# ===================================================================

#' @title Edit a raster dataset.
#' @description
#' Auto-generated GDAL CLI wrapper.
#' Edit a raster dataset.
#' @param dataset GDAL argument
#' @param auxiliary GDAL argument
#' @param crs GDAL argument
#' @param bbox GDAL argument
#' @param nodata GDAL argument
#' @param metadata GDAL argument
#' @param unset_metadata GDAL argument
#' @param stats GDAL argument
#' @param approx_stats GDAL argument
#' @param hist GDAL argument
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples
#' \dontrun{
#' gdal_raster_edit(...) |> gdal_run()
#' }

#' @export
gdal_raster_edit <- function(dataset = NULL,
  auxiliary = FALSE,
  crs = NULL,
  bbox,
  nodata = NULL,
  metadata = NULL,
  unset_metadata = NULL,
  stats = FALSE,
  approx_stats = FALSE,
  hist = FALSE) {
  # Collect arguments
  args <- list()
  if (!missing(dataset)) args[["dataset"]] <- dataset
  if (!missing(auxiliary)) args[["auxiliary"]] <- auxiliary
  if (!missing(crs)) args[["crs"]] <- crs
  if (!missing(bbox)) args[["bbox"]] <- bbox
  if (!missing(nodata)) args[["nodata"]] <- nodata
  if (!missing(metadata)) args[["metadata"]] <- metadata
  if (!missing(unset_metadata)) args[["unset_metadata"]] <- unset_metadata
  if (!missing(stats)) args[["stats"]] <- stats
  if (!missing(approx_stats)) args[["approx_stats"]] <- approx_stats
  if (!missing(hist)) args[["hist"]] <- hist

  new_gdal_job(command_path = c("gdal", "raster", "edit"), arguments = args)
}

