# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# ===================================================================

#' @title Convert a multidimensional dataset.
#' @description
#' Auto-generated GDAL CLI wrapper.
#' Convert a multidimensional dataset.
#' 
#' See \url{https://gdal.org/en/stable/programs/gdal_mdim_convert.html} for detailed GDAL documentation.
#' @param job A gdal_job object from a piped operation, or NULL
#' @param input Input raster or multidimensional raster dataset (Dataset path) (required)
#' @param input_format Input formats (Character vector). `0` to `2147483647` value(s) (Advanced)
#' @param output Output multidimensional raster dataset (Dataset path) (required)
#' @param output_format Output format
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s) (Advanced)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s)
#' @param overwrite Whether overwriting existing output is allowed (Logical) (Default: `false`)
#' @param array Select a single array instead of converting the whole dataset. (Character vector). Format: `ARRAY-SPEC`. `0` to `2147483647` value(s)
#' @param array_option Option passed to GDALGroup::GetMDArrayNames() to filter arrays. (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s)
#' @param group Select a single group instead of converting the whole dataset. (Character vector). Format: `GROUP-SPEC`. `0` to `2147483647` value(s)
#' @param subset Select a subset of the data. (Character vector). Format: `SUBSET-SPEC`. `0` to `2147483647` value(s)
#' @param scale_axes Applies a integral scale factor to one or several dimensions (Character vector). Format: `SCALEAXES-SPEC`. `0` to `2147483647` value(s)
#' @param strict Turn warnings into failures. (Logical)
#' @return A [gdal_job] object.
#' @family gdal_mdim_utilities
#' @examples
#' # Create a GDAL job (not executed)
#' job <- gdal_mdim_convert(input = "data.tif")
#' #
#' # Inspect the job (optional)
#' # print(job)

#' @export
gdal_mdim_convert <- function(job = NULL,
  input = NULL,
  input_format = NULL,
  output = NULL,
  output_format = NULL,
  open_option = NULL,
  creation_option = NULL,
  overwrite = FALSE,
  array = NULL,
  array_option = NULL,
  group = NULL,
  subset = NULL,
  scale_axes = NULL,
  strict = FALSE) {
  # Collect function arguments
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(array)) new_args[["array"]] <- array
  if (!missing(array_option)) new_args[["array_option"]] <- array_option
  if (!missing(group)) new_args[["group"]] <- group
  if (!missing(subset)) new_args[["subset"]] <- subset
  if (!missing(scale_axes)) new_args[["scale_axes"]] <- scale_axes
  if (!missing(strict)) new_args[["strict"]] <- strict
  job_input <- handle_job_input(job, new_args, c("mdim", "convert"))
  if (job_input$should_extend) {
    # Extend pipeline from existing job
    return(extend_gdal_pipeline(job_input$job, c("mdim", "convert"), new_args))
  } else {
    # Create new job with merged arguments
    merged_args <- job_input$merged_args
  }

  new_gdal_job(command_path = c("mdim", "convert"), arguments = merged_args)
}

