# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# ===================================================================

#' @title Creates a vector contour from a raster elevation model (DEM).
#' @description
#' Auto-generated GDAL CLI wrapper.
#' Creates a vector contour from a raster elevation model (DEM).
#' @param output_format GDAL argument
#' @param open_option GDAL argument
#' @param input_format GDAL argument
#' @param input GDAL argument
#' @param creation_option GDAL argument
#' @param layer_creation_option GDAL argument
#' @param band GDAL argument
#' @param layer GDAL argument
#' @param elevation_name GDAL argument
#' @param min_name GDAL argument
#' @param max_name GDAL argument
#' @param X3d GDAL argument
#' @param src_nodata GDAL argument
#' @param interval GDAL argument
#' @param levels GDAL argument
#' @param exp_base GDAL argument
#' @param offset GDAL argument
#' @param polygonize GDAL argument
#' @param group_transactions GDAL argument
#' @param overwrite GDAL argument
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples
#' \dontrun{
#' gdal_raster_contour(...) |> gdal_run()
#' }

#' @export
gdal_raster_contour <- function(output_format = NULL,
  open_option = NULL,
  input_format = NULL,
  input = NULL,
  creation_option = NULL,
  layer_creation_option = NULL,
  band = NULL,
  layer = NULL,
  elevation_name = NULL,
  min_name = NULL,
  max_name = NULL,
  X3d = FALSE,
  src_nodata = NULL,
  interval = NULL,
  levels = NULL,
  exp_base = NULL,
  offset = NULL,
  polygonize = FALSE,
  group_transactions = NULL,
  overwrite = FALSE) {
  # Collect arguments
  args <- list()
  if (!missing(output_format)) args[["output_format"]] <- output_format
  if (!missing(open_option)) args[["open_option"]] <- open_option
  if (!missing(input_format)) args[["input_format"]] <- input_format
  if (!missing(input)) args[["input"]] <- input
  if (!missing(creation_option)) args[["creation_option"]] <- creation_option
  if (!missing(layer_creation_option)) args[["layer_creation_option"]] <- layer_creation_option
  if (!missing(band)) args[["band"]] <- band
  if (!missing(layer)) args[["layer"]] <- layer
  if (!missing(elevation_name)) args[["elevation_name"]] <- elevation_name
  if (!missing(min_name)) args[["min_name"]] <- min_name
  if (!missing(max_name)) args[["max_name"]] <- max_name
  if (!missing(X3d)) args[["X3d"]] <- X3d
  if (!missing(src_nodata)) args[["src_nodata"]] <- src_nodata
  if (!missing(interval)) args[["interval"]] <- interval
  if (!missing(levels)) args[["levels"]] <- levels
  if (!missing(exp_base)) args[["exp_base"]] <- exp_base
  if (!missing(offset)) args[["offset"]] <- offset
  if (!missing(polygonize)) args[["polygonize"]] <- polygonize
  if (!missing(group_transactions)) args[["group_transactions"]] <- group_transactions
  if (!missing(overwrite)) args[["overwrite"]] <- overwrite

  new_gdal_job(command_path = c("gdal", "raster", "contour"), arguments = args)
}

