# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# ===================================================================

#' @title repack: Repack a FileGeoDatabase dataset
#' @description
#' Repack a FileGeoDatabase dataset
#' 
#' See \url{https://gdal.org/en/stable/programs/gdal_driver_openfilegdb_repack.html} for detailed GDAL documentation.
#' @param job A gdal_job object from a piped operation, or NULL
#' @param dataset FileGeoDatabase dataset (Dataset path) (required)
#' @return A [gdal_job] object.
#' @family gdal_driver_utilities
#' @examples
#' # Example usage
#' job <- gdal_driver_openfilegdb_repack(dataset = "my.gdb")
#' @export
gdal_driver_openfilegdb_repack <- function(job = NULL,
  dataset) {
  new_args <- list()
  if (!missing(dataset)) new_args[["dataset"]] <- dataset
  job_input <- handle_job_input(job, new_args, c("driver", "openfilegdb", "repack"))
  if (job_input$should_extend) {
    return(extend_gdal_pipeline(job_input$job, c("driver", "openfilegdb", "repack"), new_args))
  } else {
    merged_args <- job_input$merged_args
  }

  new_gdal_job(command_path = c("driver", "openfilegdb", "repack"), arguments = merged_args)
}

