# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.13.0
# ===================================================================

#' @title combine: Combine features into collections
#' @description
#' `gdal vector combine` combines geometries into geometry collections. The --group-by argument can be used to determine which features are combined. By default, the parts of multipart geometries will be combined into an un-nested collection of the most specific type possible (e.g., ``MultiPolygon`` rather than ``GeometryCollection``). For example, a Polygon and a two-part MultiPolygon would be combined into a three-part MultiPoygon. This is done because many GIS file formats and software packages do not handle nested GeometryCollections types. If the nested representation in the manner of PostGIS' ``ST_Collect`` is preferred (a two-component GeometryCollection containing the Polygon and MultiPolygon), then --keep-nested can be used. ``combine`` can be used as a step of gdal_vector_pipeline.
#' 
#' See \url{https://gdal.org/en/release-3.13/programs/gdal_vector_combine.html} for detailed GDAL documentation.
#' @param input Input vector datasets (required). Exactly `1` value(s). Can also be a [gdal_job] object to extend a pipeline
#' @param input_format Input formats (Character vector) (Advanced)
#' @param input_layer Input layer name(s) (Character vector)
#' @param output Output vector dataset (Dataset path) (required)
#' @param output_format Output format ("GDALG" allowed)
#' @param output_open_option Output open options (Character vector). Format: `<KEY>=<VALUE>` (Advanced)
#' @param output_layer Output layer name
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>` (Advanced)
#' @param quiet Quiet mode (no progress bar or warning message) (Logical) (Common)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`
#' @param layer_creation_option Layer creation option (Character vector). Format: `<KEY>=<VALUE>`
#' @param overwrite Whether overwriting existing output dataset is allowed (Logical) (Default: `false`)
#' @param update Whether to open existing dataset in update mode (Logical) (Default: `false`)
#' @param overwrite_layer Whether overwriting existing output layer is allowed (Logical) (Default: `false`)
#' @param append Whether appending to existing layer is allowed (Logical) (Default: `false`)
#' @param upsert Upsert features (implies 'append') (Logical) (Advanced)
#' @param skip_errors Skip errors when writing features (Logical)
#' @param group_by Names of field(s) by which inputs should be grouped (Character vector)
#' @param keep_nested Avoid combining the components of multipart geometries (Logical)
#' @param add_extra_fields Whether to add extra fields, depending on if they have identical values within each group. Choices: "no", "sometimes-identical", "always-identical" (Default: `no`)
#' @param ... Parameter aliases and synonyms for backward compatibility. See `?gdal_parameter_aliases` for details.
#' @return A [gdal_job] object.
#' @family gdal_vector_utilities
#' @examples
#' \dontrun{
#' # TODO: No examples available for gdal_vector_combine.
#' # See GDAL documentation at:
#' https://gdal.org/en/release-3.13/programs/gdal_vector_combine.html
#' job <- gdal_vector_combine()
#' # gdal_job_run(job)
#' }
#' @export
gdal_vector_combine <- function(input,
  input_format = NULL,
  input_layer = NULL,
  output,
  output_format = NULL,
  output_open_option = NULL,
  output_layer = NULL,
  open_option = NULL,
  quiet = FALSE,
  creation_option = NULL,
  layer_creation_option = NULL,
  overwrite = FALSE,
  update = FALSE,
  overwrite_layer = FALSE,
  append = FALSE,
  upsert = FALSE,
  skip_errors = FALSE,
  group_by = NULL,
  keep_nested = FALSE,
  add_extra_fields = NULL,
  ...) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(input_layer)) new_args[["input_layer"]] <- input_layer
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(output_open_option)) new_args[["output_open_option"]] <- output_open_option
  if (!missing(output_layer)) new_args[["output_layer"]] <- output_layer
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(quiet)) new_args[["quiet"]] <- quiet
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(layer_creation_option)) new_args[["layer_creation_option"]] <- layer_creation_option
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(update)) new_args[["update"]] <- update
  if (!missing(overwrite_layer)) new_args[["overwrite_layer"]] <- overwrite_layer
  if (!missing(append)) new_args[["append"]] <- append
  if (!missing(upsert)) new_args[["upsert"]] <- upsert
  if (!missing(skip_errors)) new_args[["skip_errors"]] <- skip_errors
  if (!missing(group_by)) new_args[["group_by"]] <- group_by
  if (!missing(keep_nested)) new_args[["keep_nested"]] <- keep_nested
  if (!missing(add_extra_fields)) new_args[["add_extra_fields"]] <- add_extra_fields


  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("vector", "combine"), new_args))
  }


  merged_args <- .merge_alias_parameters(list(...), new_args)
  .update_intent_mapping <- NULL
  .update_intent <- infer_update_intent("gdal_vector_combine", merged_args, .update_intent_mapping)

  .arg_mapping <- list(
    input = list(min_count = 1, max_count = 1),
    input_format = list(min_count = 0, max_count = 2147483647),
    input_layer = list(min_count = 0, max_count = 2147483647),
    output = list(min_count = 0, max_count = 1),
    output_format = list(min_count = 0, max_count = 1),
    output_open_option = list(min_count = 0, max_count = 2147483647),
    output_layer = list(min_count = 0, max_count = 1),
    open_option = list(min_count = 0, max_count = 2147483647),
    quiet = list(min_count = 0, max_count = 1),
    creation_option = list(min_count = 0, max_count = 2147483647),
    layer_creation_option = list(min_count = 0, max_count = 2147483647),
    overwrite = list(min_count = 0, max_count = 1),
    update = list(min_count = 0, max_count = 1),
    overwrite_layer = list(min_count = 0, max_count = 1),
    append = list(min_count = 0, max_count = 1),
    upsert = list(min_count = 0, max_count = 1),
    skip_errors = list(min_count = 0, max_count = 1),
    group_by = list(min_count = 0, max_count = 2147483647),
    keep_nested = list(min_count = 0, max_count = 1),
    add_extra_fields = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("vector", "combine"), arguments = merged_args, arg_mapping = .arg_mapping, update_intent = .update_intent)
}

