# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# ===================================================================

#' @title Create a regular grid from scattered points using weighted inverse distance interpolation nearest neighbour.
#' @description
#' Auto-generated GDAL CLI wrapper.
#' Create a regular grid from scattered points using weighted inverse distance interpolation nearest neighbour.
#' @param output_format GDAL argument
#' @param open_option GDAL argument
#' @param input_format GDAL argument
#' @param input GDAL argument
#' @param creation_option GDAL argument
#' @param extent GDAL argument
#' @param resolution GDAL argument
#' @param size GDAL argument
#' @param output_data_type GDAL argument
#' @param crs GDAL argument
#' @param overwrite GDAL argument
#' @param layer GDAL argument
#' @param sql GDAL argument
#' @param bbox GDAL argument
#' @param zfield GDAL argument
#' @param zoffset GDAL argument
#' @param zmultiply GDAL argument
#' @param power GDAL argument
#' @param smoothing GDAL argument
#' @param radius GDAL argument
#' @param min_points GDAL argument
#' @param max_points GDAL argument
#' @param min_points_per_quadrant GDAL argument
#' @param max_points_per_quadrant GDAL argument
#' @param nodata GDAL argument
#' @return A [gdal_job] object.
#' @family gdal_vector_utilities
#' @examples
#' \dontrun{
#' gdal_vector_grid_invdistnn(...) |> gdal_run()
#' }

#' @export
gdal_vector_grid_invdistnn <- function(output_format = NULL,
  open_option = NULL,
  input_format = NULL,
  input = NULL,
  creation_option = NULL,
  extent,
  resolution,
  size,
  output_data_type = NULL,
  crs = NULL,
  overwrite = FALSE,
  layer = NULL,
  sql = NULL,
  bbox,
  zfield = NULL,
  zoffset = NULL,
  zmultiply = NULL,
  power = NULL,
  smoothing = NULL,
  radius = NULL,
  min_points = NULL,
  max_points = NULL,
  min_points_per_quadrant = NULL,
  max_points_per_quadrant = NULL,
  nodata = NULL) {
  # Collect arguments
  args <- list()
  if (!missing(output_format)) args[["output_format"]] <- output_format
  if (!missing(open_option)) args[["open_option"]] <- open_option
  if (!missing(input_format)) args[["input_format"]] <- input_format
  if (!missing(input)) args[["input"]] <- input
  if (!missing(creation_option)) args[["creation_option"]] <- creation_option
  if (!missing(extent)) args[["extent"]] <- extent
  if (!missing(resolution)) args[["resolution"]] <- resolution
  if (!missing(size)) args[["size"]] <- size
  if (!missing(output_data_type)) args[["output_data_type"]] <- output_data_type
  if (!missing(crs)) args[["crs"]] <- crs
  if (!missing(overwrite)) args[["overwrite"]] <- overwrite
  if (!missing(layer)) args[["layer"]] <- layer
  if (!missing(sql)) args[["sql"]] <- sql
  if (!missing(bbox)) args[["bbox"]] <- bbox
  if (!missing(zfield)) args[["zfield"]] <- zfield
  if (!missing(zoffset)) args[["zoffset"]] <- zoffset
  if (!missing(zmultiply)) args[["zmultiply"]] <- zmultiply
  if (!missing(power)) args[["power"]] <- power
  if (!missing(smoothing)) args[["smoothing"]] <- smoothing
  if (!missing(radius)) args[["radius"]] <- radius
  if (!missing(min_points)) args[["min_points"]] <- min_points
  if (!missing(max_points)) args[["max_points"]] <- max_points
  if (!missing(min_points_per_quadrant)) args[["min_points_per_quadrant"]] <- min_points_per_quadrant
  if (!missing(max_points_per_quadrant)) args[["max_points_per_quadrant"]] <- max_points_per_quadrant
  if (!missing(nodata)) args[["nodata"]] <- nodata

  new_gdal_job(command_path = c("gdal", "vector", "grid", "invdistnn"), arguments = args)
}

