# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# ===================================================================

#' @title Multidimensional commands.
#' @description
#' Auto-generated GDAL CLI wrapper.
#' Multidimensional commands.
#' @param drivers GDAL argument
#' @return A [gdal_job] object.
#' @family gdal_mdim_utilities
#' @examples
#' \dontrun{
#' gdal_mdim(...) |> gdal_run()
#' }

#' @export
gdal_mdim <- function(drivers = FALSE) {
  # Collect arguments
  args <- list()
  if (!missing(drivers)) args[["drivers"]] <- drivers

  new_gdal_job(command_path = c("gdal", "mdim"), arguments = args)
}

