# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# ===================================================================

#' @title move: Move/rename a file/directory located on GDAL Virtual System Interface (VSI)
#' @description
#' `gdal vsi move` move files and directories located on GDAL Virtual File Systems (compressed, network hosted, etc...): /vsimem, /vsizip, /vsitar, /vsicurl, ....
#' 
#' See \url{https://gdal.org/en/stable/programs/gdal_vsi_move.html} for detailed GDAL documentation.
#' @param job A gdal_job object from a piped operation, or NULL
#' @param source Source file or directory name (required)
#' @param destination Destination file or directory name (required)
#' @return A [gdal_job] object.
#' @family gdal_vsi_utilities
#' @examples
#' @export
gdal_vsi_move <- function(job = NULL,
  source,
  destination) {
  new_args <- list()
  if (!missing(source)) new_args[["source"]] <- source
  if (!missing(destination)) new_args[["destination"]] <- destination
  job_input <- handle_job_input(job, new_args, c("vsi", "move"))
  if (job_input$should_extend) {
    return(extend_gdal_pipeline(job_input$job, c("vsi", "move"), new_args))
  } else {
    merged_args <- job_input$merged_args
  }

  new_gdal_job(command_path = c("vsi", "move"), arguments = merged_args)
}

