# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# ===================================================================

#' @title Create an index of raster datasets compatible of the GDAL Tile Index (GTI) driver.
#' @description
#' Auto-generated GDAL CLI wrapper.
#' Create an index of raster datasets compatible of the GDAL Tile Index (GTI) driver.
#' @param input GDAL argument
#' @param output_format GDAL argument
#' @param creation_option GDAL argument
#' @param layer_creation_option GDAL argument
#' @param overwrite GDAL argument
#' @param update GDAL argument
#' @param overwrite_layer GDAL argument
#' @param append GDAL argument
#' @param layer GDAL argument
#' @param recursive GDAL argument
#' @param filename_filter GDAL argument
#' @param min_pixel_size GDAL argument
#' @param max_pixel_size GDAL argument
#' @param location_name GDAL argument
#' @param absolute_path GDAL argument
#' @param dst_crs GDAL argument
#' @param metadata GDAL argument
#' @param xml_filename GDAL argument
#' @param resolution GDAL argument
#' @param bbox GDAL argument
#' @param output_data_type GDAL argument
#' @param band_count GDAL argument
#' @param nodata GDAL argument
#' @param color_interpretation GDAL argument
#' @param mask GDAL argument
#' @param fetch_metadata GDAL argument
#' @return A [gdal_job] object.
#' @family gdal_driver_utilities
#' @examples
#' \dontrun{
#' gdal_driver_gti_create(...) |> gdal_run()
#' }

#' @export
gdal_driver_gti_create <- function(input = NULL,
  output_format = NULL,
  creation_option = NULL,
  layer_creation_option = NULL,
  overwrite = FALSE,
  update = FALSE,
  overwrite_layer = FALSE,
  append = FALSE,
  layer = NULL,
  recursive = FALSE,
  filename_filter = NULL,
  min_pixel_size = NULL,
  max_pixel_size = NULL,
  location_name = NULL,
  absolute_path = FALSE,
  dst_crs = NULL,
  metadata = NULL,
  xml_filename = NULL,
  resolution,
  bbox,
  output_data_type = NULL,
  band_count = NULL,
  nodata = NULL,
  color_interpretation = NULL,
  mask = FALSE,
  fetch_metadata = NULL) {
  # Collect arguments
  args <- list()
  if (!missing(input)) args[["input"]] <- input
  if (!missing(output_format)) args[["output_format"]] <- output_format
  if (!missing(creation_option)) args[["creation_option"]] <- creation_option
  if (!missing(layer_creation_option)) args[["layer_creation_option"]] <- layer_creation_option
  if (!missing(overwrite)) args[["overwrite"]] <- overwrite
  if (!missing(update)) args[["update"]] <- update
  if (!missing(overwrite_layer)) args[["overwrite_layer"]] <- overwrite_layer
  if (!missing(append)) args[["append"]] <- append
  if (!missing(layer)) args[["layer"]] <- layer
  if (!missing(recursive)) args[["recursive"]] <- recursive
  if (!missing(filename_filter)) args[["filename_filter"]] <- filename_filter
  if (!missing(min_pixel_size)) args[["min_pixel_size"]] <- min_pixel_size
  if (!missing(max_pixel_size)) args[["max_pixel_size"]] <- max_pixel_size
  if (!missing(location_name)) args[["location_name"]] <- location_name
  if (!missing(absolute_path)) args[["absolute_path"]] <- absolute_path
  if (!missing(dst_crs)) args[["dst_crs"]] <- dst_crs
  if (!missing(metadata)) args[["metadata"]] <- metadata
  if (!missing(xml_filename)) args[["xml_filename"]] <- xml_filename
  if (!missing(resolution)) args[["resolution"]] <- resolution
  if (!missing(bbox)) args[["bbox"]] <- bbox
  if (!missing(output_data_type)) args[["output_data_type"]] <- output_data_type
  if (!missing(band_count)) args[["band_count"]] <- band_count
  if (!missing(nodata)) args[["nodata"]] <- nodata
  if (!missing(color_interpretation)) args[["color_interpretation"]] <- color_interpretation
  if (!missing(mask)) args[["mask"]] <- mask
  if (!missing(fetch_metadata)) args[["fetch_metadata"]] <- fetch_metadata

  new_gdal_job(command_path = c("gdal", "driver", "gti", "create"), arguments = args)
}

