# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# ===================================================================

#' @title Convert a multidimensional dataset.
#' @description
#' Auto-generated GDAL CLI wrapper.
#' Convert a multidimensional dataset.
#' @param output_format GDAL argument
#' @param open_option GDAL argument
#' @param input_format GDAL argument
#' @param input GDAL argument
#' @param creation_option GDAL argument
#' @param overwrite GDAL argument
#' @param array GDAL argument
#' @param array_option GDAL argument
#' @param group GDAL argument
#' @param subset GDAL argument
#' @param scale_axes GDAL argument
#' @param strict GDAL argument
#' @return A [gdal_job] object.
#' @family gdal_mdim_utilities
#' @examples
#' \dontrun{
#' gdal_mdim_convert(...) |> gdal_run()
#' }

#' @export
gdal_mdim_convert <- function(output_format = NULL,
  open_option = NULL,
  input_format = NULL,
  input = NULL,
  creation_option = NULL,
  overwrite = FALSE,
  array = NULL,
  array_option = NULL,
  group = NULL,
  subset = NULL,
  scale_axes = NULL,
  strict = FALSE) {
  # Collect arguments
  args <- list()
  if (!missing(output_format)) args[["output_format"]] <- output_format
  if (!missing(open_option)) args[["open_option"]] <- open_option
  if (!missing(input_format)) args[["input_format"]] <- input_format
  if (!missing(input)) args[["input"]] <- input
  if (!missing(creation_option)) args[["creation_option"]] <- creation_option
  if (!missing(overwrite)) args[["overwrite"]] <- overwrite
  if (!missing(array)) args[["array"]] <- array
  if (!missing(array_option)) args[["array_option"]] <- array_option
  if (!missing(group)) args[["group"]] <- group
  if (!missing(subset)) args[["subset"]] <- subset
  if (!missing(scale_axes)) args[["scale_axes"]] <- scale_axes
  if (!missing(strict)) args[["strict"]] <- strict

  new_gdal_job(command_path = c("gdal", "mdim", "convert"), arguments = args)
}

