# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.12.2
# ===================================================================

#' @title repack: Repack a FileGeoDatabase dataset
#' @description
#' Runs the a repack operation on a FileGeodatabase dataset to recover lost space due to updates or deletions.
#' 
#' See \url{https://gdal.org/en/release-3.12/programs/gdal_driver_openfilegdb_repack.html} for detailed GDAL documentation.
#' @param dataset FileGeoDatabase dataset (Dataset path) (required). Can also be a [gdal_job] object to extend a pipeline
#' @param ... Parameter aliases and synonyms for backward compatibility. See `?gdal_parameter_aliases` for details.
#' @return A [gdal_job] object.
#' @family gdal_driver_utilities
#' @examples

#' job <- gdal_driver_openfilegdb_repack(dataset = "my.gdb")
#' \dontrun{
#'   result <- gdal_job_run(job)
#' }
#' @export
gdal_driver_openfilegdb_repack <- function(dataset,
  ...) {
  new_args <- list()
  if (!missing(dataset)) new_args[["dataset"]] <- dataset


  if (!missing(dataset) && inherits(dataset, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- dataset
    new_args[["dataset"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("driver", "openfilegdb", "repack"), new_args))
  }


  merged_args <- .merge_alias_parameters(list(...), new_args)
  .update_intent_mapping <- NULL
  .update_intent <- infer_update_intent("gdal_driver_openfilegdb_repack", merged_args, .update_intent_mapping)

  .arg_mapping <- list(
    dataset = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("driver", "openfilegdb", "repack"), arguments = merged_args, arg_mapping = .arg_mapping, update_intent = .update_intent)
}

