# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# ===================================================================

#' @title Fill nodata raster regions by interpolation from edges.
#' @description
#' Auto-generated GDAL CLI wrapper.
#' Fill nodata raster regions by interpolation from edges.
#' @param input_format GDAL argument
#' @param input GDAL argument
#' @param output_format GDAL argument
#' @param creation_option GDAL argument
#' @param overwrite GDAL argument
#' @param band GDAL argument
#' @param max_distance GDAL argument
#' @param smoothing_iterations GDAL argument
#' @param mask GDAL argument
#' @param strategy GDAL argument
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples
#' \dontrun{
#' gdal_raster_fill_nodata(...) |> gdal_run()
#' }

#' @export
gdal_raster_fill_nodata <- function(input_format = NULL,
  input = NULL,
  output_format = NULL,
  creation_option = NULL,
  overwrite = FALSE,
  band = NULL,
  max_distance = NULL,
  smoothing_iterations = NULL,
  mask = NULL,
  strategy = NULL) {
  # Collect arguments
  args <- list()
  if (!missing(input_format)) args[["input_format"]] <- input_format
  if (!missing(input)) args[["input"]] <- input
  if (!missing(output_format)) args[["output_format"]] <- output_format
  if (!missing(creation_option)) args[["creation_option"]] <- creation_option
  if (!missing(overwrite)) args[["overwrite"]] <- overwrite
  if (!missing(band)) args[["band"]] <- band
  if (!missing(max_distance)) args[["max_distance"]] <- max_distance
  if (!missing(smoothing_iterations)) args[["smoothing_iterations"]] <- smoothing_iterations
  if (!missing(mask)) args[["mask"]] <- mask
  if (!missing(strategy)) args[["strategy"]] <- strategy

  new_gdal_job(command_path = c("gdal", "raster", "fill-nodata"), arguments = args)
}

