# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.13.3
# ===================================================================

#' @title viewshed: Compute the viewshed of a raster dataset
#' @description
#' `gdal raster viewshed` creates a binary visibility raster from one band of the input raster elevation model (DEM). The output raster will be of type Byte. Using the ``DEM`` or ``ground`` values of --mode can also create a minimum visible height raster of type Float64. It uses the method defined in \[Wang2000\]_ for a user defined point. This subcommand is also available as a potential step of gdal_raster_pipeline (since GDAL 3.12)
#' 
#' See \url{https://gdal.org/en/release-3.13/programs/gdal_raster_viewshed.html} for detailed GDAL documentation.
#' @param input Input raster datasets (required). Exactly `1` value(s). Can also be a [gdal_job] object to extend a pipeline
#' @param input_format Input formats (Character vector) (Advanced)
#' @param output Output raster dataset (Dataset path) (required)
#' @param output_format Output format ("GDALG" allowed)
#' @param target_height Height of the target above the DEM surface in the height unit of the DEM. (Default: `0`)
#' @param output_nodata The value to be set for the cells in the output raster that have no data.. Range: (`0` to `255`)
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>` (Advanced)
#' @param quiet Quiet mode (no progress bar or warning message) (Logical) (Common)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`
#' @param overwrite Whether overwriting existing output dataset is allowed (Logical) (Default: `false`)
#' @param append Append as a subdataset to existing output (Logical) (Default: `false`)
#' @param position Observer position. Format: `<X,Y> or <X,Y,H>`. `2` to `3` value(s)
#' @param height Observer height
#' @param sd_filename Filename of standard-deviation raster (Dataset path)
#' @param mode Sets what information the output contains.. Choices: "normal", "DEM", "ground", "cumulative" (Default: `normal`)
#' @param max_distance Maximum distance from observer to compute visibility. It is also used to clamp the extent of the output raster.. Minimum: `0`
#' @param min_distance Mask all cells less than this distance from the observer. Must be less than 'max-distance'.. Minimum: `0`
#' @param start_angle Mask all cells outside of the arc ('start-angle', 'end-angle'). Clockwise degrees from north. Also used to clamp the extent of the output raster.. Range: (`0` to `360`)
#' @param end_angle Mask all cells outside of the arc ('start-angle', 'end-angle'). Clockwise degrees from north. Also used to clamp the extent of the output raster.. Range: (`0` to `360`)
#' @param high_pitch Mark all cells out-of-range where the observable height would be higher than the 'high-pitch' angle from the observer. Degrees from horizontal - positive is up. Must be greater than 'low-pitch'.. Range: (`-90` to `90`)
#' @param low_pitch Bound observable height to be no lower than the 'low-pitch' angle from the observer. Degrees from horizontal - positive is up. Must be less than 'high-pitch'.. Range: (`-90` to `90`)
#' @param curvature_coefficient Coefficient to consider the effect of the curvature and refraction.. Minimum: `0`
#' @param band Input band (1-based index) (Integer) (Default: `1`)
#' @param visible_value Pixel value to set for visible areas (Default: `255`). Range: (`0` to `255`)
#' @param invisible_value Pixel value to set for invisible areas (Default: `0`). Range: (`0` to `255`)
#' @param maybe_visible_value Pixel value to set for potentially visible areas (Default: `2`). Range: (`0` to `255`)
#' @param out_of_range_value Pixel value to set for the cells that fall outside of the range specified by the observer location and the maximum distance (Default: `0`)
#' @param observer_spacing Cell Spacing between observers (Integer) (Default: `10`). Minimum: `1`
#' @param num_threads Number of jobs (or ALL_CPUS) (Default: `3`)
#' @param ... Parameter aliases and synonyms for backward compatibility. See `?gdal_parameter_aliases` for details.
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples

#' job <- gdal_raster_viewshed(input = "source.tif", output = "destination.tif", 
#'     max_distance = 500)
#' \dontrun{
#'   result <- gdal_job_run(job)
#' }
#' @export
gdal_raster_viewshed <- function(input,
  input_format = NULL,
  output,
  output_format = NULL,
  target_height = NULL,
  output_nodata = NULL,
  open_option = NULL,
  quiet = FALSE,
  creation_option = NULL,
  overwrite = FALSE,
  append = FALSE,
  position = NULL,
  height = NULL,
  sd_filename = NULL,
  mode = NULL,
  max_distance = NULL,
  min_distance = NULL,
  start_angle = NULL,
  end_angle = NULL,
  high_pitch = NULL,
  low_pitch = NULL,
  curvature_coefficient = NULL,
  band = NULL,
  visible_value = NULL,
  invisible_value = NULL,
  maybe_visible_value = NULL,
  out_of_range_value = NULL,
  observer_spacing = NULL,
  num_threads = NULL,
  ...) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(target_height)) new_args[["target_height"]] <- target_height
  if (!missing(output_nodata)) new_args[["output_nodata"]] <- output_nodata
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(quiet)) new_args[["quiet"]] <- quiet
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(append)) new_args[["append"]] <- append
  if (!missing(position)) new_args[["position"]] <- position
  if (!missing(height)) new_args[["height"]] <- height
  if (!missing(sd_filename)) new_args[["sd_filename"]] <- sd_filename
  if (!missing(mode)) new_args[["mode"]] <- mode
  if (!missing(max_distance)) new_args[["max_distance"]] <- max_distance
  if (!missing(min_distance)) new_args[["min_distance"]] <- min_distance
  if (!missing(start_angle)) new_args[["start_angle"]] <- start_angle
  if (!missing(end_angle)) new_args[["end_angle"]] <- end_angle
  if (!missing(high_pitch)) new_args[["high_pitch"]] <- high_pitch
  if (!missing(low_pitch)) new_args[["low_pitch"]] <- low_pitch
  if (!missing(curvature_coefficient)) new_args[["curvature_coefficient"]] <- curvature_coefficient
  if (!missing(band)) new_args[["band"]] <- band
  if (!missing(visible_value)) new_args[["visible_value"]] <- visible_value
  if (!missing(invisible_value)) new_args[["invisible_value"]] <- invisible_value
  if (!missing(maybe_visible_value)) new_args[["maybe_visible_value"]] <- maybe_visible_value
  if (!missing(out_of_range_value)) new_args[["out_of_range_value"]] <- out_of_range_value
  if (!missing(observer_spacing)) new_args[["observer_spacing"]] <- observer_spacing
  if (!missing(num_threads)) new_args[["num_threads"]] <- num_threads


  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("raster", "viewshed"), new_args))
  }


  merged_args <- .merge_alias_parameters(list(...), new_args)
  .update_intent_mapping <- NULL
  .update_intent <- infer_update_intent("gdal_raster_viewshed", merged_args, .update_intent_mapping)

  .arg_mapping <- list(
    input = list(min_count = 1, max_count = 1),
    input_format = list(min_count = 0, max_count = 2147483647),
    output = list(min_count = 0, max_count = 1),
    output_format = list(min_count = 0, max_count = 1),
    target_height = list(min_count = 0, max_count = 1),
    output_nodata = list(min_count = 0, max_count = 1),
    open_option = list(min_count = 0, max_count = 2147483647),
    quiet = list(min_count = 0, max_count = 1),
    creation_option = list(min_count = 0, max_count = 2147483647),
    overwrite = list(min_count = 0, max_count = 1),
    append = list(min_count = 0, max_count = 1),
    position = list(min_count = 2, max_count = 3),
    height = list(min_count = 0, max_count = 1),
    sd_filename = list(min_count = 0, max_count = 1),
    mode = list(min_count = 0, max_count = 1),
    max_distance = list(min_count = 0, max_count = 1),
    min_distance = list(min_count = 0, max_count = 1),
    start_angle = list(min_count = 0, max_count = 1),
    end_angle = list(min_count = 0, max_count = 1),
    high_pitch = list(min_count = 0, max_count = 1),
    low_pitch = list(min_count = 0, max_count = 1),
    curvature_coefficient = list(min_count = 0, max_count = 1),
    band = list(min_count = 0, max_count = 1),
    visible_value = list(min_count = 0, max_count = 1),
    invisible_value = list(min_count = 0, max_count = 1),
    maybe_visible_value = list(min_count = 0, max_count = 1),
    out_of_range_value = list(min_count = 0, max_count = 1),
    observer_spacing = list(min_count = 0, max_count = 1),
    num_threads = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("raster", "viewshed"), arguments = merged_args, arg_mapping = .arg_mapping, update_intent = .update_intent)
}

