# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.13.2
# ===================================================================

#' @title refresh: Refresh overviews
#' @description
#' `gdal raster overview refresh` can be used to refresh existing overviews of a dataset. By default all overviews are refreshed, but it is also possible to restrict the refreshed overviews by level and/or extent.
#' 
#' See \url{https://gdal.org/en/release-3.13/programs/gdal_raster_overview_refresh.html} for detailed GDAL documentation.
#' @param input Dataset (to be updated in-place, unless --external) (Dataset path) (required). Can also be a [gdal_job] object to extend a pipeline
#' @param quiet Quiet mode (no progress bar or warning message) (Logical) (Common)
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>` (Advanced)
#' @param external Refresh external overviews (Logical)
#' @param resampling Resampling method. Choices: "nearest", "average", "cubic", "cubicspline", "lanczos", ...
#' @param levels Levels / decimation factors (Integer vector). Minimum: `2`
#' @param bbox Bounding box to refresh. Exactly `4` value(s)
#' @param like Use extent of dataset(s) (Character vector)
#' @param use_source_timestamp Use timestamp of VRT or GTI sources as refresh criterion (Logical)
#' @param ... Parameter aliases and synonyms for backward compatibility. See `?gdal_parameter_aliases` for details.
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples
#' \dontrun{
#' # TODO: No examples available for gdal_raster_overview_refresh.
#' # See GDAL documentation at:
#' https://gdal.org/en/release-3.13/programs/gdal_raster_overview_refresh.html
#' job <- gdal_raster_overview_refresh()
#' # gdal_job_run(job)
#' }
#' @export
gdal_raster_overview_refresh <- function(input,
  quiet = FALSE,
  open_option = NULL,
  external = FALSE,
  resampling = NULL,
  levels = NULL,
  bbox = NULL,
  like = NULL,
  use_source_timestamp = FALSE,
  ...) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(quiet)) new_args[["quiet"]] <- quiet
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(external)) new_args[["external"]] <- external
  if (!missing(resampling)) new_args[["resampling"]] <- resampling
  if (!missing(levels)) new_args[["levels"]] <- levels
  if (!missing(bbox)) new_args[["bbox"]] <- bbox
  if (!missing(like)) new_args[["like"]] <- like
  if (!missing(use_source_timestamp)) new_args[["use_source_timestamp"]] <- use_source_timestamp


  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("raster", "overview", "refresh"), new_args))
  }


  merged_args <- .merge_alias_parameters(list(...), new_args)
  .update_intent_mapping <- list(dataset = list(by_default = TRUE, unless_any_of = "external"))
  .update_intent <- infer_update_intent("gdal_raster_overview_refresh", merged_args, .update_intent_mapping)

  .arg_mapping <- list(
    input = list(min_count = 0, max_count = 1),
    quiet = list(min_count = 0, max_count = 1),
    open_option = list(min_count = 0, max_count = 2147483647),
    external = list(min_count = 0, max_count = 1),
    resampling = list(min_count = 0, max_count = 1),
    levels = list(min_count = 0, max_count = 2147483647),
    bbox = list(min_count = 4, max_count = 4),
    like = list(min_count = 0, max_count = 2147483647),
    use_source_timestamp = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("raster", "overview", "refresh"), arguments = merged_args, arg_mapping = .arg_mapping, update_intent = .update_intent)
}

