# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# ===================================================================

#' @title Clip a vector dataset.
#' @description
#' Auto-generated GDAL CLI wrapper.
#' Clip a vector dataset.
#' @param input_format GDAL argument
#' @param open_option GDAL argument
#' @param input GDAL argument
#' @param input_layer GDAL argument
#' @param output_format GDAL argument
#' @param creation_option GDAL argument
#' @param layer_creation_option GDAL argument
#' @param overwrite GDAL argument
#' @param update GDAL argument
#' @param overwrite_layer GDAL argument
#' @param append GDAL argument
#' @param output_layer GDAL argument
#' @param active_layer GDAL argument
#' @param bbox GDAL argument
#' @param bbox_crs GDAL argument
#' @param geometry GDAL argument
#' @param geometry_crs GDAL argument
#' @param like GDAL argument
#' @param like_sql GDAL argument
#' @param like_layer GDAL argument
#' @param like_where GDAL argument
#' @return A [gdal_job] object.
#' @family gdal_vector_utilities
#' @examples
#' \dontrun{
#' gdal_vector_clip(...) |> gdal_run()
#' }

#' @export
gdal_vector_clip <- function(input_format = NULL,
  open_option = NULL,
  input,
  input_layer = NULL,
  output_format = NULL,
  creation_option = NULL,
  layer_creation_option = NULL,
  overwrite = FALSE,
  update = FALSE,
  overwrite_layer = FALSE,
  append = FALSE,
  output_layer = NULL,
  active_layer = NULL,
  bbox,
  bbox_crs = NULL,
  geometry = NULL,
  geometry_crs = NULL,
  like = NULL,
  like_sql = NULL,
  like_layer = NULL,
  like_where = NULL) {
  # Collect arguments
  args <- list()
  if (!missing(input_format)) args[["input_format"]] <- input_format
  if (!missing(open_option)) args[["open_option"]] <- open_option
  if (!missing(input)) args[["input"]] <- input
  if (!missing(input_layer)) args[["input_layer"]] <- input_layer
  if (!missing(output_format)) args[["output_format"]] <- output_format
  if (!missing(creation_option)) args[["creation_option"]] <- creation_option
  if (!missing(layer_creation_option)) args[["layer_creation_option"]] <- layer_creation_option
  if (!missing(overwrite)) args[["overwrite"]] <- overwrite
  if (!missing(update)) args[["update"]] <- update
  if (!missing(overwrite_layer)) args[["overwrite_layer"]] <- overwrite_layer
  if (!missing(append)) args[["append"]] <- append
  if (!missing(output_layer)) args[["output_layer"]] <- output_layer
  if (!missing(active_layer)) args[["active_layer"]] <- active_layer
  if (!missing(bbox)) args[["bbox"]] <- bbox
  if (!missing(bbox_crs)) args[["bbox_crs"]] <- bbox_crs
  if (!missing(geometry)) args[["geometry"]] <- geometry
  if (!missing(geometry_crs)) args[["geometry_crs"]] <- geometry_crs
  if (!missing(like)) args[["like"]] <- like
  if (!missing(like_sql)) args[["like_sql"]] <- like_sql
  if (!missing(like_layer)) args[["like_layer"]] <- like_layer
  if (!missing(like_where)) args[["like_where"]] <- like_where

  new_gdal_job(command_path = c("gdal", "vector", "clip"), arguments = args)
}

