# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.11.4
# Generation date: 2026-02-13
# ===================================================================

#' @title rasterize: Burns vector geometries into a raster
#' @description
#' Burns vector geometries into a raster.
#' 
#' See \url{https://gdal.org/en/3.11.4/programs/gdal_vector_rasterize.html} for detailed GDAL documentation.
#' @param input Input vector dataset (Dataset path). Format: `NA`. Choices: NULL (Default: `NULL`) (required). Can also be a [gdal_job] object to extend a pipeline
#' @param input_format Input formats (Character vector). Format: `NA`. Choices: NULL (Default: `NULL`). `0` to `2147483647` value(s) (Advanced)
#' @param output Output raster dataset (Dataset path) (required)
#' @param output_format Output format. Format: `NA`. Choices: NULL (Default: `NULL`)
#' @param target_aligned_pixels (target aligned pixels) Align the coordinates of the extent of the output file to the values of the resolution (Logical). Format: `NA`. Choices: NULL (Default: `NULL`)
#' @param output_data_type Output data type. Format: `NA`. Choices: c("Byte", "Int8", "UInt16", "Int16", "UInt32", "Int32", "UInt64", "Int64", "CInt16", "CInt32", "Float16", "Float32", "Float64", "CFloat32", "CFloat64") (Default: `NULL`)
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>`. Choices: NULL (Default: `NULL`). `0` to `2147483647` value(s) (Advanced)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`. Choices: NULL (Default: `NULL`). `0` to `2147483647` value(s)
#' @param band The band(s) to burn values into (1-based index) (Integer vector). Format: `NA`. Choices: NULL (Default: `NULL`). `0` to `2147483647` value(s)
#' @param invert Invert the rasterization (Logical). Format: `NA`. Choices: NULL (Default: `FALSE`)
#' @param all_touched Enables the ALL_TOUCHED rasterization option (Logical). Format: `NA`. Choices: NULL (Default: `NULL`)
#' @param burn Burn value. Format: `NA`. Choices: NULL (Default: `NULL`). `0` to `2147483647` value(s)
#' @param attribute_name Attribute name. Format: `NA`. Choices: NULL (Default: `NULL`)
#' @param X3d Indicates that a burn value should be extracted from the Z values of the feature (Logical). Format: `NA`. Choices: NULL (Default: `NULL`)
#' @param add Add to existing raster (Logical). Format: `NA`. Choices: NULL (Default: `FALSE`)
#' @param layer_name Layer name. Format: `NA`. Choices: NULL (Default: `NULL`)
#' @param where SQL where clause. Format: `NA`. Choices: NULL (Default: `NULL`)
#' @param sql SQL select statement. Format: `NA`. Choices: NULL (Default: `NULL`)
#' @param dialect SQL dialect. Format: `NA`. Choices: NULL (Default: `NULL`)
#' @param nodata Assign a specified nodata value to output bands. Format: `NA`. Choices: NULL (Default: `NULL`)
#' @param init Pre-initialize output bands with specified value. Format: `NA`. Choices: NULL (Default: `NULL`). `0` to `2147483647` value(s)
#' @param crs Override the projection for the output file. Format: `NA`. Choices: NULL (Default: `NULL`)
#' @param transformer_option Set a transformer option suitable to pass to GDALCreateGenImgProjTransformer2 (Character vector). Format: `<NAME>=<VALUE>`. Choices: NULL (Default: `NULL`). `0` to `2147483647` value(s)
#' @param extent Set the target georeferenced extent. Format: `<xmin>,<ymin>,<xmax>,<ymax>`. Choices: NULL (Default: `NULL`). Exactly `4` value(s)
#' @param resolution Set the target resolution. Format: `<xres>,<yres>`. Choices: NULL (Default: `NULL`). Exactly `2` value(s)
#' @param size Set the target size in pixels and lines (Integer vector). Format: `<xsize>,<ysize>`. Choices: NULL (Default: `NULL`). Exactly `2` value(s)
#' @param optimization Force the algorithm used (results are identical). Format: `NA`. Choices: c("AUTO", "RASTER", "VECTOR") (Default: `AUTO`)
#' @param update Whether to open existing dataset in update mode (Logical). Format: `NA`. Choices: NULL (Default: `FALSE`)
#' @param overwrite Whether overwriting existing output is allowed (Logical). Format: `NA`. Choices: NULL (Default: `FALSE`)
#' @return A [gdal_job] object.
#' @family gdal_vector_utilities
#' @examples
#' \dontrun{
#' # TODO: No examples available for gdal_vector_rasterize.
#' # See GDAL documentation: https://gdal.org/programs/gdal-vector-rasterize.html
#' job <- gdal_vector_rasterize()
#' # gdal_job_run(job)
#' }
#' @export
gdal_vector_rasterize <- function(input,
  input_format = NULL,
  output,
  output_format = NULL,
  target_aligned_pixels = FALSE,
  output_data_type = NULL,
  open_option = NULL,
  creation_option = NULL,
  band = NULL,
  invert = FALSE,
  all_touched = FALSE,
  burn = NULL,
  attribute_name = NULL,
  X3d = FALSE,
  add = FALSE,
  layer_name = NULL,
  where = NULL,
  sql = NULL,
  dialect = NULL,
  nodata = NULL,
  init = NULL,
  crs = NULL,
  transformer_option = NULL,
  extent = NULL,
  resolution = NULL,
  size = NULL,
  optimization = NULL,
  update = FALSE,
  overwrite = FALSE) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(target_aligned_pixels)) new_args[["target_aligned_pixels"]] <- target_aligned_pixels
  if (!missing(output_data_type)) new_args[["output_data_type"]] <- output_data_type
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(band)) new_args[["band"]] <- band
  if (!missing(invert)) new_args[["invert"]] <- invert
  if (!missing(all_touched)) new_args[["all_touched"]] <- all_touched
  if (!missing(burn)) new_args[["burn"]] <- burn
  if (!missing(attribute_name)) new_args[["attribute_name"]] <- attribute_name
  if (!missing(X3d)) new_args[["X3d"]] <- X3d
  if (!missing(add)) new_args[["add"]] <- add
  if (!missing(layer_name)) new_args[["layer_name"]] <- layer_name
  if (!missing(where)) new_args[["where"]] <- where
  if (!missing(sql)) new_args[["sql"]] <- sql
  if (!missing(dialect)) new_args[["dialect"]] <- dialect
  if (!missing(nodata)) new_args[["nodata"]] <- nodata
  if (!missing(init)) new_args[["init"]] <- init
  if (!missing(crs)) new_args[["crs"]] <- crs
  if (!missing(transformer_option)) new_args[["transformer_option"]] <- transformer_option
  if (!missing(extent)) new_args[["extent"]] <- extent
  if (!missing(resolution)) new_args[["resolution"]] <- resolution
  if (!missing(size)) new_args[["size"]] <- size
  if (!missing(optimization)) new_args[["optimization"]] <- optimization
  if (!missing(update)) new_args[["update"]] <- update
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("vector", "rasterize"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    input = list(min_count = NA, max_count = NA),
    input_format = list(min_count = 0, max_count = 2147483647),
    output = list(min_count = 0, max_count = 1),
    output_format = list(min_count = NA, max_count = NA),
    target_aligned_pixels = list(min_count = NA, max_count = NA),
    output_data_type = list(min_count = NA, max_count = NA),
    open_option = list(min_count = 0, max_count = 2147483647),
    creation_option = list(min_count = 0, max_count = 2147483647),
    band = list(min_count = 0, max_count = 2147483647),
    invert = list(min_count = NA, max_count = NA),
    all_touched = list(min_count = NA, max_count = NA),
    burn = list(min_count = 0, max_count = 2147483647),
    attribute_name = list(min_count = NA, max_count = NA),
    X3d = list(min_count = NA, max_count = NA),
    add = list(min_count = NA, max_count = NA),
    layer_name = list(min_count = NA, max_count = NA),
    where = list(min_count = NA, max_count = NA),
    sql = list(min_count = NA, max_count = NA),
    dialect = list(min_count = NA, max_count = NA),
    nodata = list(min_count = NA, max_count = NA),
    init = list(min_count = 0, max_count = 2147483647),
    crs = list(min_count = NA, max_count = NA),
    transformer_option = list(min_count = 0, max_count = 2147483647),
    extent = list(min_count = 4, max_count = 4),
    resolution = list(min_count = 2, max_count = 2),
    size = list(min_count = 2, max_count = 2),
    optimization = list(min_count = NA, max_count = NA),
    update = list(min_count = NA, max_count = NA),
    overwrite = list(min_count = NA, max_count = NA)
  )

  new_gdal_job(command_path = c("vector", "rasterize"), arguments = merged_args, arg_mapping = .arg_mapping)
}

