# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.11.4
# Generation date: 2026-02-08
# ===================================================================

#' @title index: Create a vector index of raster datasets
#' @description
#' Create a vector index of raster datasets.
#' 
#' See \url{https://gdal.org/en/3.11.4/programs/gdal_raster_index.html} for detailed GDAL documentation.
#' @param input Input raster datasets. Format: `NA`. Choices: NULL (Default: `NULL`) (required). Minimum: `NA`. `0` to `2147483647` value(s). Can also be a [gdal_job] object to extend a pipeline
#' @param source_crs_field_name Name of the field to store the CRS of each dataset. Format: `NA`. Choices: NULL (Default: `NULL`). Minimum: `NA`
#' @param source_crs_format Format in which the CRS of each dataset must be written. Format: `NA`. Choices: c("auto", "WKT", "EPSG", "PROJ") (Default: `auto`). Minimum: `NA`
#' @param output Output vector dataset (Dataset path) (required)
#' @param output_format Output format. Format: `NA`. Choices: NULL (Default: `NULL`). Minimum: `NA`
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`. Choices: NULL (Default: `NULL`). Minimum: `NA`. `0` to `2147483647` value(s)
#' @param layer_creation_option Layer creation option (Character vector). Format: `<KEY>=<VALUE>`. Choices: NULL (Default: `NULL`). Minimum: `NA`. `0` to `2147483647` value(s)
#' @param overwrite Whether overwriting existing output is allowed (Logical). Format: `NA`. Choices: NULL (Default: `FALSE`). Minimum: `NA`
#' @param update Whether to open existing dataset in update mode (Logical). Format: `NA`. Choices: NULL (Default: `FALSE`). Minimum: `NA`
#' @param overwrite_layer Whether overwriting existing layer is allowed (Logical). Format: `NA`. Choices: NULL (Default: `FALSE`). Minimum: `NA`
#' @param append Whether appending to existing layer is allowed (Logical). Format: `NA`. Choices: NULL (Default: `FALSE`). Minimum: `NA`
#' @param layer Layer name. Format: `NA`. Choices: NULL (Default: `NULL`). Minimum: `NA`
#' @param recursive Whether input directories should be explored recursively. (Logical). Format: `NA`. Choices: NULL (Default: `NULL`). Minimum: `NA`
#' @param filename_filter Pattern that the filenames in input directories should follow ('*' and '?' wildcard) (Character vector). Format: `NA`. Choices: NULL (Default: `NULL`). Minimum: `NA`. `0` to `2147483647` value(s)
#' @param min_pixel_size Minimum pixel size in term of geospatial extent per pixel (resolution) that a raster should have to be selected.. Format: `NA`. Choices: NULL (Default: `NULL`). Minimum: `0`
#' @param max_pixel_size Maximum pixel size in term of geospatial extent per pixel (resolution) that a raster should have to be selected.. Format: `NA`. Choices: NULL (Default: `NULL`). Minimum: `0`
#' @param location_name Name of the field with the raster path. Format: `NA`. Choices: NULL (Default: `location`). Minimum: `NA`
#' @param absolute_path Whether the path to the input datasets should be stored as an absolute path (Logical). Format: `NA`. Choices: NULL (Default: `NULL`). Minimum: `NA`
#' @param dst_crs Destination CRS. Format: `NA`. Choices: NULL (Default: `NULL`). Minimum: `NA`
#' @param metadata Add dataset metadata item (Character vector). Format: `<KEY>=<VALUE>`. Choices: NULL (Default: `NULL`). Minimum: `NA`. `0` to `2147483647` value(s)
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples

#' job <- gdal_raster_index(input = "doq/*.tif", output = "doq_index.gpkg")
#' \dontrun{
#'   result <- gdal_job_run(job)
#' }
#' @export
gdal_raster_index <- function(input,
  source_crs_field_name = NULL,
  source_crs_format = NULL,
  output,
  output_format = NULL,
  creation_option = NULL,
  layer_creation_option = NULL,
  overwrite = FALSE,
  update = FALSE,
  overwrite_layer = FALSE,
  append = FALSE,
  layer = NULL,
  recursive = FALSE,
  filename_filter = NULL,
  min_pixel_size = NULL,
  max_pixel_size = NULL,
  location_name = NULL,
  absolute_path = FALSE,
  dst_crs = NULL,
  metadata = NULL) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(source_crs_field_name)) new_args[["source_crs_field_name"]] <- source_crs_field_name
  if (!missing(source_crs_format)) new_args[["source_crs_format"]] <- source_crs_format
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(layer_creation_option)) new_args[["layer_creation_option"]] <- layer_creation_option
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(update)) new_args[["update"]] <- update
  if (!missing(overwrite_layer)) new_args[["overwrite_layer"]] <- overwrite_layer
  if (!missing(append)) new_args[["append"]] <- append
  if (!missing(layer)) new_args[["layer"]] <- layer
  if (!missing(recursive)) new_args[["recursive"]] <- recursive
  if (!missing(filename_filter)) new_args[["filename_filter"]] <- filename_filter
  if (!missing(min_pixel_size)) new_args[["min_pixel_size"]] <- min_pixel_size
  if (!missing(max_pixel_size)) new_args[["max_pixel_size"]] <- max_pixel_size
  if (!missing(location_name)) new_args[["location_name"]] <- location_name
  if (!missing(absolute_path)) new_args[["absolute_path"]] <- absolute_path
  if (!missing(dst_crs)) new_args[["dst_crs"]] <- dst_crs
  if (!missing(metadata)) new_args[["metadata"]] <- metadata

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("raster", "index"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    input = list(min_count = 0, max_count = 2147483647),
    source_crs_field_name = list(min_count = NA, max_count = NA),
    source_crs_format = list(min_count = NA, max_count = NA),
    output = list(min_count = 0, max_count = 1),
    output_format = list(min_count = NA, max_count = NA),
    creation_option = list(min_count = 0, max_count = 2147483647),
    layer_creation_option = list(min_count = 0, max_count = 2147483647),
    overwrite = list(min_count = NA, max_count = NA),
    update = list(min_count = NA, max_count = NA),
    overwrite_layer = list(min_count = NA, max_count = NA),
    append = list(min_count = NA, max_count = NA),
    layer = list(min_count = NA, max_count = NA),
    recursive = list(min_count = NA, max_count = NA),
    filename_filter = list(min_count = 0, max_count = 2147483647),
    min_pixel_size = list(min_count = NA, max_count = NA),
    max_pixel_size = list(min_count = NA, max_count = NA),
    location_name = list(min_count = NA, max_count = NA),
    absolute_path = list(min_count = NA, max_count = NA),
    dst_crs = list(min_count = NA, max_count = NA),
    metadata = list(min_count = 0, max_count = 2147483647)
  )

  new_gdal_job(command_path = c("raster", "index"), arguments = merged_args, arg_mapping = .arg_mapping)
}

