# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# ===================================================================

#' @title clip: Clip a vector dataset
#' @description
#' Clip a vector dataset.
#' 
#' See \url{https://gdal.org/en/stable/programs/gdal_vector_clip.html} for detailed GDAL documentation.
#' @param job A gdal_job object from a piped operation, or NULL
#' @param input Input vector datasets (required). Exactly `1` value(s)
#' @param output Output vector dataset (Dataset path) (required)
#' @param input_format Input formats (Character vector). `0` to `2147483647` value(s) (Advanced)
#' @param input_layer Input layer name(s) (Character vector). `0` to `2147483647` value(s)
#' @param output_format Output format ("GDALG" allowed)
#' @param output_layer Output layer name
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s) (Advanced)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s)
#' @param layer_creation_option Layer creation option (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s)
#' @param overwrite Whether overwriting existing output is allowed (Logical) (Default: `false`)
#' @param update Whether to open existing dataset in update mode (Logical) (Default: `false`)
#' @param overwrite_layer Whether overwriting existing layer is allowed (Logical) (Default: `false`)
#' @param append Whether appending to existing layer is allowed (Logical) (Default: `false`)
#' @param active_layer Set active layer (if not specified, all)
#' @param bbox Clipping bounding box as xmin,ymin,xmax,ymax. Exactly `4` value(s)
#' @param bbox_crs CRS of clipping bounding box
#' @param geometry Clipping geometry (WKT or GeoJSON)
#' @param geometry_crs CRS of clipping geometry
#' @param like Dataset to use as a template for bounds (Dataset path). Format: `DATASET`
#' @param like_sql SELECT statement to run on the 'like' dataset. Format: `SELECT-STATEMENT`
#' @param like_layer Name of the layer of the 'like' dataset. Format: `LAYER-NAME`
#' @param like_where WHERE SQL clause to run on the 'like' dataset. Format: `WHERE-EXPRESSION`
#' @return A [gdal_job] object.
#' @family gdal_vector_utilities
#' @examples
#' @export
gdal_vector_clip <- function(job = NULL,
  input,
  output,
  input_format = NULL,
  input_layer = NULL,
  output_format = NULL,
  output_layer = NULL,
  open_option = NULL,
  creation_option = NULL,
  layer_creation_option = NULL,
  overwrite = FALSE,
  update = FALSE,
  overwrite_layer = FALSE,
  append = FALSE,
  active_layer = NULL,
  bbox = NULL,
  bbox_crs = NULL,
  geometry = NULL,
  geometry_crs = NULL,
  like = NULL,
  like_sql = NULL,
  like_layer = NULL,
  like_where = NULL) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(input_layer)) new_args[["input_layer"]] <- input_layer
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(output_layer)) new_args[["output_layer"]] <- output_layer
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(layer_creation_option)) new_args[["layer_creation_option"]] <- layer_creation_option
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(update)) new_args[["update"]] <- update
  if (!missing(overwrite_layer)) new_args[["overwrite_layer"]] <- overwrite_layer
  if (!missing(append)) new_args[["append"]] <- append
  if (!missing(active_layer)) new_args[["active_layer"]] <- active_layer
  if (!missing(bbox)) new_args[["bbox"]] <- bbox
  if (!missing(bbox_crs)) new_args[["bbox_crs"]] <- bbox_crs
  if (!missing(geometry)) new_args[["geometry"]] <- geometry
  if (!missing(geometry_crs)) new_args[["geometry_crs"]] <- geometry_crs
  if (!missing(like)) new_args[["like"]] <- like
  if (!missing(like_sql)) new_args[["like_sql"]] <- like_sql
  if (!missing(like_layer)) new_args[["like_layer"]] <- like_layer
  if (!missing(like_where)) new_args[["like_where"]] <- like_where
  job_input <- handle_job_input(job, new_args, c("vector", "clip"))
  if (job_input$should_extend) {
    return(extend_gdal_pipeline(job_input$job, c("vector", "clip"), new_args))
  } else {
    merged_args <- job_input$merged_args
  }

  new_gdal_job(command_path = c("vector", "clip"), arguments = merged_args)
}

