# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.12.2
# Generation date: 2026-02-13
# ===================================================================

#' @title unscale: Convert scaled values of a raster dataset into unscaled values
#' @description
#' Convert scaled values of a raster dataset into unscaled values.
#' 
#' See \url{https://gdal.org/en/3.12.2/programs/gdal_raster_unscale.html} for detailed GDAL documentation.
#' @param input Input raster datasets. Format: `NA`. Choices: NULL (Default: `NA`) (required). Exactly `1` value(s). Can also be a [gdal_job] object to extend a pipeline
#' @param input_format Input formats (Character vector). Format: `NA`. Choices: NULL (Default: `NA`). `0` to `2147483647` value(s) (Advanced)
#' @param output Output raster dataset (Dataset path) (required)
#' @param output_format Output format ("GDALG" allowed). Format: `NA`. Choices: NULL (Default: `NA`)
#' @param output_data_type Output data type. Format: `NA`. Choices: c("Byte", "Int8", "UInt16", "Int16", "UInt32", "Int32", "UInt64", "Int64", "CInt16", "CInt32", "Float16", "Float32", "Float64", "CFloat32", "CFloat64") (Default: `NA`)
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>`. Choices: NULL (Default: `NA`). `0` to `2147483647` value(s) (Advanced)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`. Choices: NULL (Default: `NA`). `0` to `2147483647` value(s)
#' @param overwrite Whether overwriting existing output is allowed (Logical). Format: `NA`. Choices: NULL (Default: `false`)
#' @param append Append as a subdataset to existing output (Logical). Format: `NA`. Choices: NULL (Default: `false`)
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples

#' job <- gdal_raster_unscale(input = "scaled_byte.tif", output = "unscaled_float32.tif", 
#'     overwrite = TRUE)
#' \dontrun{
#'   result <- gdal_job_run(job)
#' }
#' @export
gdal_raster_unscale <- function(input,
  input_format = NULL,
  output,
  output_format = NULL,
  output_data_type = NULL,
  open_option = NULL,
  creation_option = NULL,
  overwrite = FALSE,
  append = FALSE) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(output_data_type)) new_args[["output_data_type"]] <- output_data_type
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(append)) new_args[["append"]] <- append

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("raster", "unscale"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    input = list(min_count = 1, max_count = 1),
    input_format = list(min_count = 0, max_count = 2147483647),
    output = list(min_count = 0, max_count = 1),
    output_format = list(min_count = NA, max_count = NA),
    output_data_type = list(min_count = NA, max_count = NA),
    open_option = list(min_count = 0, max_count = 2147483647),
    creation_option = list(min_count = 0, max_count = 2147483647),
    overwrite = list(min_count = NA, max_count = NA),
    append = list(min_count = NA, max_count = NA)
  )

  new_gdal_job(command_path = c("raster", "unscale"), arguments = merged_args, arg_mapping = .arg_mapping)
}

