# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.12.2
# Generation date: 2026-02-13
# ===================================================================

#' @title create: Create a Seek-optimized ZIP (SOZIP) file
#' @description
#' Create a Seek-optimized ZIP (SOZIP) file.
#' 
#' See \url{https://gdal.org/en/3.12.2/programs/gdal_vsi_sozip_create.html} for detailed GDAL documentation.
#' @param input Input filenames (Character vector). Format: `NA`. Choices: NULL (Default: `NULL`) (required). `0` to `2147483647` value(s). Can also be a [gdal_job] object to extend a pipeline
#' @param output Output ZIP filename. Format: `NA`. Choices: NULL (Default: `NULL`) (required)
#' @param overwrite Whether overwriting existing output is allowed (Logical). Format: `NA`. Choices: NULL (Default: `FALSE`)
#' @param recursive Travels the directory structure of the specified directories recursively (Logical). Format: `NA`. Choices: NULL (Default: `NULL`)
#' @param no_paths Store just the name of a saved file, and do not store directory names (Logical). Format: `NA`. Choices: NULL (Default: `NULL`)
#' @param enable_sozip Whether to automatically/systematically/never apply the SOZIP optimization. Format: `NA`. Choices: c("auto", "yes", "no") (Default: `auto`)
#' @param sozip_chunk_size Chunk size for a seek-optimized file. Format: `value in bytes or with K/M suffix`. Choices: NULL (Default: `32768`)
#' @param sozip_min_file_size Minimum file size to decide if a file should be seek-optimized. Format: `value in bytes or with K/M/G suffix`. Choices: NULL (Default: `1 MB`)
#' @param content_type Store the Content-Type of the file being added.. Format: `NA`. Choices: NULL (Default: `NULL`)
#' @return A [gdal_job] object.
#' @family gdal_vsi_utilities
#' @examples
#' \dontrun{
#' # TODO: No examples available for gdal_vsi_sozip_create.
#' # See GDAL documentation: https://gdal.org/programs/gdal-vsi-sozip-create.html
#' job <- gdal_vsi_sozip_create()
#' # gdal_job_run(job)
#' }
#' @export
gdal_vsi_sozip_create <- function(input,
  output,
  overwrite = FALSE,
  recursive = FALSE,
  no_paths = FALSE,
  enable_sozip = NULL,
  sozip_chunk_size = NULL,
  sozip_min_file_size = NULL,
  content_type = NULL) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(recursive)) new_args[["recursive"]] <- recursive
  if (!missing(no_paths)) new_args[["no_paths"]] <- no_paths
  if (!missing(enable_sozip)) new_args[["enable_sozip"]] <- enable_sozip
  if (!missing(sozip_chunk_size)) new_args[["sozip_chunk_size"]] <- sozip_chunk_size
  if (!missing(sozip_min_file_size)) new_args[["sozip_min_file_size"]] <- sozip_min_file_size
  if (!missing(content_type)) new_args[["content_type"]] <- content_type

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("vsi", "sozip", "create"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    input = list(min_count = 0, max_count = 2147483647),
    output = list(min_count = NA, max_count = NA),
    overwrite = list(min_count = NA, max_count = NA),
    recursive = list(min_count = NA, max_count = NA),
    no_paths = list(min_count = NA, max_count = NA),
    enable_sozip = list(min_count = NA, max_count = NA),
    sozip_chunk_size = list(min_count = NA, max_count = NA),
    sozip_min_file_size = list(min_count = NA, max_count = NA),
    content_type = list(min_count = NA, max_count = NA)
  )

  new_gdal_job(command_path = c("vsi", "sozip", "create"), arguments = merged_args, arg_mapping = .arg_mapping)
}

