# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# ===================================================================

#' @title Build a mosaic, either virtual (VRT) or materialized.
#' @description
#' Auto-generated GDAL CLI wrapper.
#' Build a mosaic, either virtual (VRT) or materialized.
#' @param output_format GDAL argument
#' @param input GDAL argument
#' @param creation_option GDAL argument
#' @param band GDAL argument
#' @param overwrite GDAL argument
#' @param resolution GDAL argument
#' @param bbox GDAL argument
#' @param target_aligned_pixels GDAL argument
#' @param src_nodata GDAL argument
#' @param dst_nodata GDAL argument
#' @param hide_nodata GDAL argument
#' @param add_alpha GDAL argument
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples
#' \dontrun{
#' gdal_raster_mosaic(...) |> gdal_run()
#' }

#' @export
gdal_raster_mosaic <- function(output_format = NULL,
  input,
  creation_option = NULL,
  band = NULL,
  overwrite = FALSE,
  resolution = NULL,
  bbox,
  target_aligned_pixels = FALSE,
  src_nodata,
  dst_nodata,
  hide_nodata = FALSE,
  add_alpha = FALSE) {
  # Collect arguments
  args <- list()
  if (!missing(output_format)) args[["output_format"]] <- output_format
  if (!missing(input)) args[["input"]] <- input
  if (!missing(creation_option)) args[["creation_option"]] <- creation_option
  if (!missing(band)) args[["band"]] <- band
  if (!missing(overwrite)) args[["overwrite"]] <- overwrite
  if (!missing(resolution)) args[["resolution"]] <- resolution
  if (!missing(bbox)) args[["bbox"]] <- bbox
  if (!missing(target_aligned_pixels)) args[["target_aligned_pixels"]] <- target_aligned_pixels
  if (!missing(src_nodata)) args[["src_nodata"]] <- src_nodata
  if (!missing(dst_nodata)) args[["dst_nodata"]] <- dst_nodata
  if (!missing(hide_nodata)) args[["hide_nodata"]] <- hide_nodata
  if (!missing(add_alpha)) args[["add_alpha"]] <- add_alpha

  new_gdal_job(command_path = c("gdal", "raster", "mosaic"), arguments = args)
}

