# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.12.0
# Generation date: 2025-12-14
# ===================================================================

#' @title info: Return information on a vector dataset
#' @description
#' Return information on a vector dataset.
#' 
#' See \url{https://gdal.org/en/3.12.0/programs/gdal_vector_info.html} for detailed GDAL documentation.
#' @param input Input vector datasets (required). `0` to `2147483647` value(s). Can also be a [gdal_job] object to extend a pipeline
#' @param input_format Input formats (Character vector). `0` to `2147483647` value(s) (Advanced)
#' @param input_layer Input layer name (Character vector). `0` to `2147483647` value(s)
#' @param output_format Output format. Choices: json, text
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s) (Advanced)
#' @param features List all features (beware of RAM consumption on large layers) (Logical)
#' @param summary List the layer names and the geometry type (Logical)
#' @param limit Limit the number of features per layer (implies --features) (Integer). Format: `FEATURE-COUNT`. Minimum: `0`
#' @param sql Execute the indicated SQL statement and return the result. Format: `<statement>|@<filename>`
#' @param where Attribute query in a restricted form of the queries used in the SQL WHERE statement. Format: `<WHERE>|@<filename>`
#' @param dialect SQL dialect
#' @param update Open the dataset in update mode (Logical)
#' @return A [gdal_job] object.
#' @family gdal_vector_utilities
#' @examples

#' job <- gdal_vector_info(output_format = "text", features = "poly.gpkg")
#' \dontrun{
#'   result <- gdal_job_run(job)
#' }
#' @export
gdal_vector_info <- function(input,
  input_format = NULL,
  input_layer = NULL,
  output_format = NULL,
  open_option = NULL,
  features = FALSE,
  summary = FALSE,
  limit = NULL,
  sql = NULL,
  where = NULL,
  dialect = NULL,
  update = FALSE) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(input_layer)) new_args[["input_layer"]] <- input_layer
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(features)) new_args[["features"]] <- features
  if (!missing(summary)) new_args[["summary"]] <- summary
  if (!missing(limit)) new_args[["limit"]] <- limit
  if (!missing(sql)) new_args[["sql"]] <- sql
  if (!missing(where)) new_args[["where"]] <- where
  if (!missing(dialect)) new_args[["dialect"]] <- dialect
  if (!missing(update)) new_args[["update"]] <- update

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("vector", "info"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    input = list(min_count = 0, max_count = 2147483647),
    input_format = list(min_count = 0, max_count = 2147483647),
    input_layer = list(min_count = 0, max_count = 2147483647),
    output_format = list(min_count = 0, max_count = 1),
    open_option = list(min_count = 0, max_count = 2147483647),
    features = list(min_count = 0, max_count = 1),
    summary = list(min_count = 0, max_count = 1),
    limit = list(min_count = 0, max_count = 1),
    sql = list(min_count = 0, max_count = 1),
    where = list(min_count = 0, max_count = 1),
    dialect = list(min_count = 0, max_count = 1),
    update = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("vector", "info"), arguments = merged_args, arg_mapping = .arg_mapping)
}

