# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# ===================================================================

#' @title Generate tiles in separate files from a raster dataset.
#' @description
#' Auto-generated GDAL CLI wrapper.
#' Generate tiles in separate files from a raster dataset.
#' @param open_option GDAL argument
#' @param input_format GDAL argument
#' @param input GDAL argument
#' @param output_format GDAL argument
#' @param creation_option GDAL argument
#' @param output GDAL argument
#' @param tiling_scheme GDAL argument
#' @param min_zoom GDAL argument
#' @param max_zoom GDAL argument
#' @param min_x GDAL argument
#' @param max_x GDAL argument
#' @param min_y GDAL argument
#' @param max_y GDAL argument
#' @param no_intersection_ok GDAL argument
#' @param resampling GDAL argument
#' @param overview_resampling GDAL argument
#' @param convention GDAL argument
#' @param tile_size GDAL argument
#' @param add_alpha GDAL argument
#' @param no_alpha GDAL argument
#' @param dst_nodata GDAL argument
#' @param skip_blank GDAL argument
#' @param metadata GDAL argument
#' @param copy_src_metadata GDAL argument
#' @param aux_xml GDAL argument
#' @param kml GDAL argument
#' @param resume GDAL argument
#' @param num_threads GDAL argument
#' @param excluded_values GDAL argument
#' @param excluded_values_pct_threshold GDAL argument
#' @param nodata_values_pct_threshold GDAL argument
#' @param webviewer GDAL argument
#' @param url GDAL argument
#' @param title GDAL argument
#' @param copyright GDAL argument
#' @param mapml_template GDAL argument
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples
#' \dontrun{
#' gdal_raster_tile(...) |> gdal_run()
#' }

#' @export
gdal_raster_tile <- function(open_option = NULL,
  input_format = NULL,
  input = NULL,
  output_format = NULL,
  creation_option = NULL,
  output = NULL,
  tiling_scheme = NULL,
  min_zoom = NULL,
  max_zoom = NULL,
  min_x = NULL,
  max_x = NULL,
  min_y = NULL,
  max_y = NULL,
  no_intersection_ok = FALSE,
  resampling = NULL,
  overview_resampling = NULL,
  convention = NULL,
  tile_size = NULL,
  add_alpha = FALSE,
  no_alpha = FALSE,
  dst_nodata = NULL,
  skip_blank = FALSE,
  metadata = NULL,
  copy_src_metadata = FALSE,
  aux_xml = FALSE,
  kml = FALSE,
  resume = FALSE,
  num_threads = NULL,
  excluded_values = NULL,
  excluded_values_pct_threshold = NULL,
  nodata_values_pct_threshold = NULL,
  webviewer = NULL,
  url = NULL,
  title = NULL,
  copyright = NULL,
  mapml_template = NULL) {
  # Collect arguments
  args <- list()
  if (!missing(open_option)) args[["open_option"]] <- open_option
  if (!missing(input_format)) args[["input_format"]] <- input_format
  if (!missing(input)) args[["input"]] <- input
  if (!missing(output_format)) args[["output_format"]] <- output_format
  if (!missing(creation_option)) args[["creation_option"]] <- creation_option
  if (!missing(output)) args[["output"]] <- output
  if (!missing(tiling_scheme)) args[["tiling_scheme"]] <- tiling_scheme
  if (!missing(min_zoom)) args[["min_zoom"]] <- min_zoom
  if (!missing(max_zoom)) args[["max_zoom"]] <- max_zoom
  if (!missing(min_x)) args[["min_x"]] <- min_x
  if (!missing(max_x)) args[["max_x"]] <- max_x
  if (!missing(min_y)) args[["min_y"]] <- min_y
  if (!missing(max_y)) args[["max_y"]] <- max_y
  if (!missing(no_intersection_ok)) args[["no_intersection_ok"]] <- no_intersection_ok
  if (!missing(resampling)) args[["resampling"]] <- resampling
  if (!missing(overview_resampling)) args[["overview_resampling"]] <- overview_resampling
  if (!missing(convention)) args[["convention"]] <- convention
  if (!missing(tile_size)) args[["tile_size"]] <- tile_size
  if (!missing(add_alpha)) args[["add_alpha"]] <- add_alpha
  if (!missing(no_alpha)) args[["no_alpha"]] <- no_alpha
  if (!missing(dst_nodata)) args[["dst_nodata"]] <- dst_nodata
  if (!missing(skip_blank)) args[["skip_blank"]] <- skip_blank
  if (!missing(metadata)) args[["metadata"]] <- metadata
  if (!missing(copy_src_metadata)) args[["copy_src_metadata"]] <- copy_src_metadata
  if (!missing(aux_xml)) args[["aux_xml"]] <- aux_xml
  if (!missing(kml)) args[["kml"]] <- kml
  if (!missing(resume)) args[["resume"]] <- resume
  if (!missing(num_threads)) args[["num_threads"]] <- num_threads
  if (!missing(excluded_values)) args[["excluded_values"]] <- excluded_values
  if (!missing(excluded_values_pct_threshold)) args[["excluded_values_pct_threshold"]] <- excluded_values_pct_threshold
  if (!missing(nodata_values_pct_threshold)) args[["nodata_values_pct_threshold"]] <- nodata_values_pct_threshold
  if (!missing(webviewer)) args[["webviewer"]] <- webviewer
  if (!missing(url)) args[["url"]] <- url
  if (!missing(title)) args[["title"]] <- title
  if (!missing(copyright)) args[["copyright"]] <- copyright
  if (!missing(mapml_template)) args[["mapml_template"]] <- mapml_template

  new_gdal_job(command_path = c("gdal", "raster", "tile"), arguments = args)
}

