# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# ===================================================================

#' @title Process a raster dataset.
#' @description
#' Auto-generated GDAL CLI wrapper.
#' Process a raster dataset.
#' 
#' See \url{https://gdal.org/en/stable/programs/gdal_raster_pipeline.html} for detailed GDAL documentation.
#' @param jobs A vector of gdal_job objects to execute in sequence, or NULL to use pipeline string
#' @param input Input raster dataset (Dataset path)
#' @param input_format Input formats (Character vector). `0` to `2147483647` value(s) (Advanced)
#' @param pipeline Pipeline string (ignored if jobs is provided)
#' @param output Output raster dataset (Dataset path)
#' @param output_format Output format ("GDALG" allowed)
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s) (Advanced)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s)
#' @param overwrite Whether overwriting existing output is allowed (Logical) (Default: `false`)
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples
#' # Create a GDAL job (not executed)
#' job <- gdal_raster_pipeline(input = "data.tif")
#' #
#' # Inspect the job (optional)
#' # print(job)

#' @export
gdal_raster_pipeline <- function(jobs = NULL,
  input = NULL,
  input_format = NULL,
  pipeline = NULL,
  output = NULL,
  output_format = NULL,
  open_option = NULL,
  creation_option = NULL,
  overwrite = FALSE) {
  # If jobs is provided, build pipeline string from job sequence
  if (!is.null(jobs)) {
    if (!is.list(jobs) && !is.vector(jobs)) {
      rlang::abort('jobs must be a list or vector of gdal_job objects')
    }
    for (i in seq_along(jobs)) {
      if (!inherits(jobs[[i]], 'gdal_job')) {
        rlang::abort(sprintf('jobs[[%d]] must be a gdal_job object', i))
      }
    }
    pipeline <- build_pipeline_from_jobs(jobs)
  }

  # Collect arguments
  args <- list()
  if (!missing(input)) args[["input"]] <- input
  if (!missing(input_format)) args[["input_format"]] <- input_format
  if (!missing(pipeline)) args[["pipeline"]] <- pipeline
  if (!missing(output)) args[["output"]] <- output
  if (!missing(output_format)) args[["output_format"]] <- output_format
  if (!missing(open_option)) args[["open_option"]] <- open_option
  if (!missing(creation_option)) args[["creation_option"]] <- creation_option
  if (!missing(overwrite)) args[["overwrite"]] <- overwrite

  new_gdal_job(command_path = c("raster", "pipeline"), arguments = args)
}

