# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.13.3
# ===================================================================

#' @title export-schema: Export the OGR_SCHEMA from a vector dataset
#' @description
#' `gdal vector export-schema` exports the ``OGR_SCHEMA`` from a GDAL-supported vector dataset, and returns it on the standard output stream when used from the command line, or in the ``output`` parameter when used from the API. ``OGR_SCHEMA`` is a JSON object describing the structure of a vector dataset according to the schema definition at ogr/data/ogr_fields_override.schema.json gdal vector export-schema can be used as the last step of a pipeline. The following options are available:
#' 
#' See \url{https://gdal.org/en/release-3.13/programs/gdal_vector_export-schema.html} for detailed GDAL documentation.
#' @param input Input vector datasets (required). Can also be a [gdal_job] object to extend a pipeline
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>` (Advanced)
#' @param input_format Input formats (Character vector) (Advanced)
#' @param input_layer Input layer name (Character vector)
#' @param ... Parameter aliases and synonyms for backward compatibility. See `?gdal_parameter_aliases` for details.
#' @return A [gdal_job] object.
#' @family gdal_vector_utilities
#' @examples

#' job <- gdal_vector_export_schema(input = "poly.gpkg")
#' \dontrun{
#'   result <- gdal_job_run(job)
#' }
#' @export
gdal_vector_export_schema <- function(input,
  open_option = NULL,
  input_format = NULL,
  input_layer = NULL,
  ...) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(input_layer)) new_args[["input_layer"]] <- input_layer


  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("vector", "export-schema"), new_args))
  }


  merged_args <- .merge_alias_parameters(list(...), new_args)
  .update_intent_mapping <- NULL
  .update_intent <- infer_update_intent("gdal_vector_export_schema", merged_args, .update_intent_mapping)

  .arg_mapping <- list(
    input = list(min_count = 0, max_count = 2147483647),
    open_option = list(min_count = 0, max_count = 2147483647),
    input_format = list(min_count = 0, max_count = 2147483647),
    input_layer = list(min_count = 0, max_count = 2147483647)
  )

  new_gdal_job(command_path = c("vector", "export-schema"), arguments = merged_args, arg_mapping = .arg_mapping, update_intent = .update_intent)
}

