# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.12.0
# Generation date: 2025-12-14
# ===================================================================

#' @title mosaic: Build a mosaic, either virtual (VRT) or materialized, from multidimensional...
#' @description
#' Build a mosaic, either virtual (VRT) or materialized, from multidimensional datasets.
#' 
#' See \url{https://gdal.org/en/3.12.0/programs/gdal_mdim_mosaic.html} for detailed GDAL documentation.
#' @param input Input multidimensional raster datasets (required). `1` to `2147483647` value(s). Can also be a [gdal_job] object to extend a pipeline
#' @param input_format Input formats (Character vector). `0` to `2147483647` value(s) (Advanced)
#' @param output Output multidimensional raster dataset (Dataset path) (required)
#' @param output_format Output format
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s) (Advanced)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s)
#' @param overwrite Whether overwriting existing output is allowed (Logical) (Default: `false`)
#' @param array Name of array(s) to mosaic. (Character vector). `0` to `2147483647` value(s)
#' @return A [gdal_job] object.
#' @family gdal_mdim_utilities
#' @examples

#' job <- gdal_mdim_mosaic(input = "slice*.nc", output = "out.vrt")
#' \dontrun{
#'   result <- gdal_job_run(job)
#' }
#' @export
gdal_mdim_mosaic <- function(input,
  input_format = NULL,
  output,
  output_format = NULL,
  open_option = NULL,
  creation_option = NULL,
  overwrite = FALSE,
  array = NULL) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(array)) new_args[["array"]] <- array

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("mdim", "mosaic"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    input = list(min_count = 1, max_count = 2147483647),
    input_format = list(min_count = 0, max_count = 2147483647),
    output = list(min_count = 0, max_count = 1),
    output_format = list(min_count = 0, max_count = 1),
    open_option = list(min_count = 0, max_count = 2147483647),
    creation_option = list(min_count = 0, max_count = 2147483647),
    overwrite = list(min_count = 0, max_count = 1),
    array = list(min_count = 0, max_count = 2147483647)
  )

  new_gdal_job(command_path = c("mdim", "mosaic"), arguments = merged_args, arg_mapping = .arg_mapping)
}

