# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# ===================================================================

#' @title Create a new raster dataset.
#' @description
#' Auto-generated GDAL CLI wrapper.
#' Create a new raster dataset.
#' @param output_format GDAL argument
#' @param open_option GDAL argument
#' @param input_format GDAL argument
#' @param input GDAL argument
#' @param creation_option GDAL argument
#' @param overwrite GDAL argument
#' @param append GDAL argument
#' @param size GDAL argument
#' @param band_count GDAL argument
#' @param output_data_type GDAL argument
#' @param nodata GDAL argument
#' @param burn GDAL argument
#' @param crs GDAL argument
#' @param bbox GDAL argument
#' @param metadata GDAL argument
#' @param copy_metadata GDAL argument
#' @param copy_overviews GDAL argument
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples
#' \dontrun{
#' gdal_raster_create(...) |> gdal_run()
#' }

#' @export
gdal_raster_create <- function(output_format = NULL,
  open_option = NULL,
  input_format = NULL,
  input = NULL,
  creation_option = NULL,
  overwrite = FALSE,
  append = FALSE,
  size,
  band_count = NULL,
  output_data_type = NULL,
  nodata = NULL,
  burn = NULL,
  crs = NULL,
  bbox,
  metadata = NULL,
  copy_metadata = FALSE,
  copy_overviews = FALSE) {
  # Collect arguments
  args <- list()
  if (!missing(output_format)) args[["output_format"]] <- output_format
  if (!missing(open_option)) args[["open_option"]] <- open_option
  if (!missing(input_format)) args[["input_format"]] <- input_format
  if (!missing(input)) args[["input"]] <- input
  if (!missing(creation_option)) args[["creation_option"]] <- creation_option
  if (!missing(overwrite)) args[["overwrite"]] <- overwrite
  if (!missing(append)) args[["append"]] <- append
  if (!missing(size)) args[["size"]] <- size
  if (!missing(band_count)) args[["band_count"]] <- band_count
  if (!missing(output_data_type)) args[["output_data_type"]] <- output_data_type
  if (!missing(nodata)) args[["nodata"]] <- nodata
  if (!missing(burn)) args[["burn"]] <- burn
  if (!missing(crs)) args[["crs"]] <- crs
  if (!missing(bbox)) args[["bbox"]] <- bbox
  if (!missing(metadata)) args[["metadata"]] <- metadata
  if (!missing(copy_metadata)) args[["copy_metadata"]] <- copy_metadata
  if (!missing(copy_overviews)) args[["copy_overviews"]] <- copy_overviews

  new_gdal_job(command_path = c("gdal", "raster", "create"), arguments = args)
}

