# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.12.0
# Generation date: 2025-12-14
# ===================================================================

#' @title as-features: Create features from pixels of a raster dataset
#' @description
#' Create features from pixels of a raster dataset
#' 
#' See \url{https://gdal.org/en/3.12.0/programs/gdal_raster_as-features.html} for detailed GDAL documentation.
#' @param input Input raster datasets (required). Exactly `1` value(s). Can also be a [gdal_job] object to extend a pipeline
#' @param input_format Input formats (Character vector). `0` to `2147483647` value(s) (Advanced)
#' @param output Output vector dataset (Dataset path) (required)
#' @param output_format Output format ("GDALG" allowed)
#' @param output_open_option Output open options (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s) (Advanced)
#' @param output_layer Output layer name
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s) (Advanced)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s)
#' @param layer_creation_option Layer creation option (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s)
#' @param overwrite Whether overwriting existing output is allowed (Logical) (Default: `false`)
#' @param update Whether to open existing dataset in update mode (Logical) (Default: `false`)
#' @param overwrite_layer Whether overwriting existing output is allowed (Logical) (Default: `false`)
#' @param append Whether appending to existing layer is allowed (Logical) (Default: `false`)
#' @param band Input band(s) (1-based index) (Integer vector). `0` to `2147483647` value(s)
#' @param geometry_type Geometry type. Choices: none, point, polygon (Default: `none`)
#' @param skip_nodata Omit NoData pixels from the result (Logical)
#' @param include_xy Include fields for cell center coordinates (Logical)
#' @param include_row_col Include columns for row and column (Logical)
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples
#' \dontrun{
#' # TODO: No examples available for gdal_raster_as_features.
#' # See GDAL documentation: https://gdal.org/programs/gdal-raster-as-features.html
#' job <- gdal_raster_as_features()
#' # gdal_job_run(job)
#' }
#' @export
gdal_raster_as_features <- function(input,
  input_format = NULL,
  output,
  output_format = NULL,
  output_open_option = NULL,
  output_layer = NULL,
  open_option = NULL,
  creation_option = NULL,
  layer_creation_option = NULL,
  overwrite = FALSE,
  update = FALSE,
  overwrite_layer = FALSE,
  append = FALSE,
  band = NULL,
  geometry_type = NULL,
  skip_nodata = FALSE,
  include_xy = FALSE,
  include_row_col = FALSE) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(output_open_option)) new_args[["output_open_option"]] <- output_open_option
  if (!missing(output_layer)) new_args[["output_layer"]] <- output_layer
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(layer_creation_option)) new_args[["layer_creation_option"]] <- layer_creation_option
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(update)) new_args[["update"]] <- update
  if (!missing(overwrite_layer)) new_args[["overwrite_layer"]] <- overwrite_layer
  if (!missing(append)) new_args[["append"]] <- append
  if (!missing(band)) new_args[["band"]] <- band
  if (!missing(geometry_type)) new_args[["geometry_type"]] <- geometry_type
  if (!missing(skip_nodata)) new_args[["skip_nodata"]] <- skip_nodata
  if (!missing(include_xy)) new_args[["include_xy"]] <- include_xy
  if (!missing(include_row_col)) new_args[["include_row_col"]] <- include_row_col

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("raster", "as-features"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    input = list(min_count = 1, max_count = 1),
    input_format = list(min_count = 0, max_count = 2147483647),
    output = list(min_count = 0, max_count = 1),
    output_format = list(min_count = 0, max_count = 1),
    output_open_option = list(min_count = 0, max_count = 2147483647),
    output_layer = list(min_count = 0, max_count = 1),
    open_option = list(min_count = 0, max_count = 2147483647),
    creation_option = list(min_count = 0, max_count = 2147483647),
    layer_creation_option = list(min_count = 0, max_count = 2147483647),
    overwrite = list(min_count = 0, max_count = 1),
    update = list(min_count = 0, max_count = 1),
    overwrite_layer = list(min_count = 0, max_count = 1),
    append = list(min_count = 0, max_count = 1),
    band = list(min_count = 0, max_count = 2147483647),
    geometry_type = list(min_count = 0, max_count = 1),
    skip_nodata = list(min_count = 0, max_count = 1),
    include_xy = list(min_count = 0, max_count = 1),
    include_row_col = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("raster", "as-features"), arguments = merged_args, arg_mapping = .arg_mapping)
}

