# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# ===================================================================

#' @title Perform raster algebra
#' @description
#' Auto-generated GDAL CLI wrapper.
#' Perform raster algebra
#' @param input GDAL argument
#' @param output_format GDAL argument
#' @param creation_option GDAL argument
#' @param overwrite GDAL argument
#' @param output_data_type GDAL argument
#' @param no_check_srs GDAL argument
#' @param no_check_extent GDAL argument
#' @param calc GDAL argument
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples
#' \dontrun{
#' gdal_raster_calc(...) |> gdal_run()
#' }

#' @export
gdal_raster_calc <- function(input,
  output_format = NULL,
  creation_option = NULL,
  overwrite = FALSE,
  output_data_type = NULL,
  no_check_srs = FALSE,
  no_check_extent = FALSE,
  calc) {
  # Collect arguments
  args <- list()
  if (!missing(input)) args[["input"]] <- input
  if (!missing(output_format)) args[["output_format"]] <- output_format
  if (!missing(creation_option)) args[["creation_option"]] <- creation_option
  if (!missing(overwrite)) args[["overwrite"]] <- overwrite
  if (!missing(output_data_type)) args[["output_data_type"]] <- output_data_type
  if (!missing(no_check_srs)) args[["no_check_srs"]] <- no_check_srs
  if (!missing(no_check_extent)) args[["no_check_extent"]] <- no_check_extent
  if (!missing(calc)) args[["calc"]] <- calc

  new_gdal_job(command_path = c("gdal", "raster", "calc"), arguments = args)
}

