# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# ===================================================================

#' @title raster: Raster commands
#' @description
#' Raster commands.
#' 
#' See \url{https://gdal.org/en/stable/programs/gdal_raster.html} for detailed GDAL documentation.
#' @param job A gdal_job object from a piped operation, or NULL
#' @param drivers Display raster driver list as JSON document (Logical)
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples
#' @export
gdal_raster <- function(job = NULL,
  drivers = FALSE) {
  new_args <- list()
  if (!missing(drivers)) new_args[["drivers"]] <- drivers
  job_input <- handle_job_input(job, new_args, c("raster"))
  if (job_input$should_extend) {
    return(extend_gdal_pipeline(job_input$job, c("raster"), new_args))
  } else {
    merged_args <- job_input$merged_args
  }

  new_gdal_job(command_path = c("raster"), arguments = merged_args)
}

