# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# ===================================================================

#' @title index: Create a vector index of raster datasets
#' @description
#' Create a vector index of raster datasets.
#' 
#' See \url{https://gdal.org/en/stable/programs/gdal_raster_index.html} for detailed GDAL documentation.
#' @param job A gdal_job object from a piped operation, or NULL
#' @param input Input raster datasets (required). `0` to `2147483647` value(s)
#' @param output Output vector dataset (Dataset path) (required)
#' @param source_crs_field_name Name of the field to store the CRS of each dataset
#' @param source_crs_format Format in which the CRS of each dataset must be written. Choices: auto, WKT, EPSG, PROJ (Default: `auto`)
#' @param output_format Output format
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s)
#' @param layer_creation_option Layer creation option (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s)
#' @param overwrite Whether overwriting existing output is allowed (Logical) (Default: `false`)
#' @param update Whether to open existing dataset in update mode (Logical) (Default: `false`)
#' @param overwrite_layer Whether overwriting existing layer is allowed (Logical) (Default: `false`)
#' @param append Whether appending to existing layer is allowed (Logical) (Default: `false`)
#' @param layer Layer name
#' @param recursive Whether input directories should be explored recursively. (Logical)
#' @param filename_filter Pattern that the filenames in input directories should follow ('*' and '?' wildcard) (Character vector). `0` to `2147483647` value(s)
#' @param min_pixel_size Minimum pixel size in term of geospatial extent per pixel (resolution) that a raster should have to be selected.. Minimum: `0`
#' @param max_pixel_size Maximum pixel size in term of geospatial extent per pixel (resolution) that a raster should have to be selected.. Minimum: `0`
#' @param location_name Name of the field with the raster path (Default: `location`)
#' @param absolute_path Whether the path to the input datasets should be stored as an absolute path (Logical)
#' @param dst_crs Destination CRS
#' @param metadata Add dataset metadata item (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s)
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples
#' @export
gdal_raster_index <- function(job = NULL,
  input,
  output,
  source_crs_field_name = NULL,
  source_crs_format = NULL,
  output_format = NULL,
  creation_option = NULL,
  layer_creation_option = NULL,
  overwrite = FALSE,
  update = FALSE,
  overwrite_layer = FALSE,
  append = FALSE,
  layer = NULL,
  recursive = FALSE,
  filename_filter = NULL,
  min_pixel_size = NULL,
  max_pixel_size = NULL,
  location_name = NULL,
  absolute_path = FALSE,
  dst_crs = NULL,
  metadata = NULL) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(source_crs_field_name)) new_args[["source_crs_field_name"]] <- source_crs_field_name
  if (!missing(source_crs_format)) new_args[["source_crs_format"]] <- source_crs_format
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(layer_creation_option)) new_args[["layer_creation_option"]] <- layer_creation_option
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(update)) new_args[["update"]] <- update
  if (!missing(overwrite_layer)) new_args[["overwrite_layer"]] <- overwrite_layer
  if (!missing(append)) new_args[["append"]] <- append
  if (!missing(layer)) new_args[["layer"]] <- layer
  if (!missing(recursive)) new_args[["recursive"]] <- recursive
  if (!missing(filename_filter)) new_args[["filename_filter"]] <- filename_filter
  if (!missing(min_pixel_size)) new_args[["min_pixel_size"]] <- min_pixel_size
  if (!missing(max_pixel_size)) new_args[["max_pixel_size"]] <- max_pixel_size
  if (!missing(location_name)) new_args[["location_name"]] <- location_name
  if (!missing(absolute_path)) new_args[["absolute_path"]] <- absolute_path
  if (!missing(dst_crs)) new_args[["dst_crs"]] <- dst_crs
  if (!missing(metadata)) new_args[["metadata"]] <- metadata
  job_input <- handle_job_input(job, new_args, c("raster", "index"))
  if (job_input$should_extend) {
    return(extend_gdal_pipeline(job_input$job, c("raster", "index"), new_args))
  } else {
    merged_args <- job_input$merged_args
  }

  new_gdal_job(command_path = c("raster", "index"), arguments = merged_args)
}

