# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.12.0
# Generation date: 2025-12-14
# ===================================================================

#' @title update: Update the destination raster with the content of the input one
#' @description
#' Update the destination raster with the content of the input one.
#' 
#' See \url{https://gdal.org/en/3.12.0/programs/gdal_raster_update.html} for detailed GDAL documentation.
#' @param input Input raster dataset (Dataset path) (required). Can also be a [gdal_job] object to extend a pipeline
#' @param input_format Input formats (Character vector). `0` to `2147483647` value(s) (Advanced)
#' @param output Output raster dataset (Dataset path) (required)
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s) (Advanced)
#' @param geometry Clipping geometry (WKT or GeoJSON)
#' @param geometry_crs CRS of clipping geometry
#' @param resampling Resampling method. Choices: nearest, bilinear, cubic, cubicspline, lanczos, ... (Default: `nearest`)
#' @param warp_option Warping option(s) (Character vector). Format: `<NAME>=<VALUE>`. `0` to `2147483647` value(s) (Advanced)
#' @param transform_option Transform option(s) (Character vector). Format: `<NAME>=<VALUE>`. `0` to `2147483647` value(s) (Advanced)
#' @param error_threshold Error threshold. Minimum: `0` (Advanced)
#' @param no_update_overviews Do not update existing overviews (Logical)
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples
#' \dontrun{
#' # TODO: No examples available for gdal_raster_update.
#' # See GDAL documentation: https://gdal.org/programs/gdal-raster-update.html
#' job <- gdal_raster_update()
#' # gdal_job_run(job)
#' }
#' @export
gdal_raster_update <- function(input,
  input_format = NULL,
  output,
  open_option = NULL,
  geometry = NULL,
  geometry_crs = NULL,
  resampling = NULL,
  warp_option = NULL,
  transform_option = NULL,
  error_threshold = NULL,
  no_update_overviews = FALSE) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(geometry)) new_args[["geometry"]] <- geometry
  if (!missing(geometry_crs)) new_args[["geometry_crs"]] <- geometry_crs
  if (!missing(resampling)) new_args[["resampling"]] <- resampling
  if (!missing(warp_option)) new_args[["warp_option"]] <- warp_option
  if (!missing(transform_option)) new_args[["transform_option"]] <- transform_option
  if (!missing(error_threshold)) new_args[["error_threshold"]] <- error_threshold
  if (!missing(no_update_overviews)) new_args[["no_update_overviews"]] <- no_update_overviews

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("raster", "update"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    input = list(min_count = 0, max_count = 1),
    input_format = list(min_count = 0, max_count = 2147483647),
    output = list(min_count = 0, max_count = 1),
    open_option = list(min_count = 0, max_count = 2147483647),
    geometry = list(min_count = 0, max_count = 1),
    geometry_crs = list(min_count = 0, max_count = 1),
    resampling = list(min_count = 0, max_count = 1),
    warp_option = list(min_count = 0, max_count = 2147483647),
    transform_option = list(min_count = 0, max_count = 2147483647),
    error_threshold = list(min_count = 0, max_count = 1),
    no_update_overviews = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("raster", "update"), arguments = merged_args, arg_mapping = .arg_mapping)
}

