# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# ===================================================================

#' @title Simplify geometries of a vector dataset.
#' @description
#' Auto-generated GDAL CLI wrapper.
#' Simplify geometries of a vector dataset.
#' 
#' See \url{https://gdal.org/en/stable/programs/gdal_vector_geom_simplify.html} for detailed GDAL documentation.
#' @param job A gdal_job object from a piped operation, or NULL
#' @param input Input vector datasets (required). Exactly `1` value(s)
#' @param input_format Input formats (Character vector). `0` to `2147483647` value(s) (Advanced)
#' @param input_layer Input layer name(s) (Character vector). `0` to `2147483647` value(s)
#' @param output Output vector dataset (Dataset path) (required)
#' @param output_format Output format ("GDALG" allowed)
#' @param output_layer Output layer name
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s) (Advanced)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s)
#' @param layer_creation_option Layer creation option (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s)
#' @param overwrite Whether overwriting existing output is allowed (Logical) (Default: `false`)
#' @param update Whether to open existing dataset in update mode (Logical) (Default: `false`)
#' @param overwrite_layer Whether overwriting existing layer is allowed (Logical) (Default: `false`)
#' @param append Whether appending to existing layer is allowed (Logical) (Default: `false`)
#' @param active_layer Set active layer (if not specified, all)
#' @param active_geometry Geometry field name to which to restrict the processing (if not specified, all)
#' @param tolerance Distance tolerance for simplification. (required). Minimum: `0`
#' @return A [gdal_job] object.
#' @family gdal_vector_utilities
#' @examples
#' # Create a GDAL job (not executed)
#' job <- gdal_vector_geom_simplify(input = "data.tif")
#' #
#' # Inspect the job (optional)
#' # print(job)

#' @export
gdal_vector_geom_simplify <- function(job = NULL,
  input,
  input_format = NULL,
  input_layer = NULL,
  output = NULL,
  output_format = NULL,
  output_layer = NULL,
  open_option = NULL,
  creation_option = NULL,
  layer_creation_option = NULL,
  overwrite = FALSE,
  update = FALSE,
  overwrite_layer = FALSE,
  append = FALSE,
  active_layer = NULL,
  active_geometry = NULL,
  tolerance = NULL) {
  # Collect function arguments
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(input_layer)) new_args[["input_layer"]] <- input_layer
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(output_layer)) new_args[["output_layer"]] <- output_layer
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(layer_creation_option)) new_args[["layer_creation_option"]] <- layer_creation_option
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(update)) new_args[["update"]] <- update
  if (!missing(overwrite_layer)) new_args[["overwrite_layer"]] <- overwrite_layer
  if (!missing(append)) new_args[["append"]] <- append
  if (!missing(active_layer)) new_args[["active_layer"]] <- active_layer
  if (!missing(active_geometry)) new_args[["active_geometry"]] <- active_geometry
  if (!missing(tolerance)) new_args[["tolerance"]] <- tolerance
  job_input <- handle_job_input(job, new_args, c("vector", "geom", "simplify"))
  if (job_input$should_extend) {
    # Extend pipeline from existing job
    return(extend_gdal_pipeline(job_input$job, c("vector", "geom", "simplify"), new_args))
  } else {
    # Create new job with merged arguments
    merged_args <- job_input$merged_args
  }

  new_gdal_job(command_path = c("vector", "geom", "simplify"), arguments = merged_args)
}

