# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# ===================================================================

#' @title delete: Deleting overviews
#' @description
#' Deleting overviews.
#' 
#' See \url{https://gdal.org/en/stable/programs/gdal_raster_overview_delete.html} for detailed GDAL documentation.
#' @param job A gdal_job object from a piped operation, or NULL
#' @param dataset Dataset (to be updated in-place, unless --read-only) (Dataset path) (required)
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s) (Advanced)
#' @param external Delete external overviews (Logical)
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples
#' # Example usage
#' job <- gdal_raster_overview_delete(dataset = "my.tif")
#' @export
gdal_raster_overview_delete <- function(job = NULL,
  dataset,
  open_option = NULL,
  external = FALSE) {
  new_args <- list()
  if (!missing(dataset)) new_args[["dataset"]] <- dataset
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(external)) new_args[["external"]] <- external
  job_input <- handle_job_input(job, new_args, c("raster", "overview", "delete"))
  if (job_input$should_extend) {
    return(extend_gdal_pipeline(job_input$job, c("raster", "overview", "delete"), new_args))
  } else {
    merged_args <- job_input$merged_args
  }

  new_gdal_job(command_path = c("raster", "overview", "delete"), arguments = merged_args)
}

