# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# ===================================================================

#' @title edit: Edit metadata of a vector dataset
#' @description
#' Edit metadata of a vector dataset.
#' 
#' See \url{https://gdal.org/en/stable/programs/gdal_vector_edit.html} for detailed GDAL documentation.
#' @param job A gdal_job object from a piped operation, or NULL
#' @param input Input vector datasets (required). Exactly `1` value(s)
#' @param output Output vector dataset (Dataset path) (required)
#' @param input_format Input formats (Character vector). `0` to `2147483647` value(s) (Advanced)
#' @param input_layer Input layer name(s) (Character vector). `0` to `2147483647` value(s)
#' @param output_format Output format ("GDALG" allowed)
#' @param output_layer Output layer name
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s) (Advanced)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s)
#' @param layer_creation_option Layer creation option (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s)
#' @param overwrite Whether overwriting existing output is allowed (Logical) (Default: `false`)
#' @param update Whether to open existing dataset in update mode (Logical) (Default: `false`)
#' @param overwrite_layer Whether overwriting existing layer is allowed (Logical) (Default: `false`)
#' @param append Whether appending to existing layer is allowed (Logical) (Default: `false`)
#' @param active_layer Set active layer (if not specified, all)
#' @param geometry_type Layer geometry type
#' @param crs Override CRS (without reprojection)
#' @param metadata Add/update dataset metadata item (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s)
#' @param unset_metadata Remove dataset metadata item (Character vector). Format: `KEY`. `0` to `2147483647` value(s)
#' @param layer_metadata Add/update layer metadata item (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s)
#' @param unset_layer_metadata Remove layer metadata item (Character vector). Format: `KEY`. `0` to `2147483647` value(s)
#' @return A [gdal_job] object.
#' @family gdal_vector_utilities
#' @examples
#' @export
gdal_vector_edit <- function(job = NULL,
  input,
  output,
  input_format = NULL,
  input_layer = NULL,
  output_format = NULL,
  output_layer = NULL,
  open_option = NULL,
  creation_option = NULL,
  layer_creation_option = NULL,
  overwrite = FALSE,
  update = FALSE,
  overwrite_layer = FALSE,
  append = FALSE,
  active_layer = NULL,
  geometry_type = NULL,
  crs = NULL,
  metadata = NULL,
  unset_metadata = NULL,
  layer_metadata = NULL,
  unset_layer_metadata = NULL) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(input_layer)) new_args[["input_layer"]] <- input_layer
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(output_layer)) new_args[["output_layer"]] <- output_layer
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(layer_creation_option)) new_args[["layer_creation_option"]] <- layer_creation_option
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(update)) new_args[["update"]] <- update
  if (!missing(overwrite_layer)) new_args[["overwrite_layer"]] <- overwrite_layer
  if (!missing(append)) new_args[["append"]] <- append
  if (!missing(active_layer)) new_args[["active_layer"]] <- active_layer
  if (!missing(geometry_type)) new_args[["geometry_type"]] <- geometry_type
  if (!missing(crs)) new_args[["crs"]] <- crs
  if (!missing(metadata)) new_args[["metadata"]] <- metadata
  if (!missing(unset_metadata)) new_args[["unset_metadata"]] <- unset_metadata
  if (!missing(layer_metadata)) new_args[["layer_metadata"]] <- layer_metadata
  if (!missing(unset_layer_metadata)) new_args[["unset_layer_metadata"]] <- unset_layer_metadata
  job_input <- handle_job_input(job, new_args, c("vector", "edit"))
  if (job_input$should_extend) {
    return(extend_gdal_pipeline(job_input$job, c("vector", "edit"), new_args))
  } else {
    merged_args <- job_input$merged_args
  }

  new_gdal_job(command_path = c("vector", "edit"), arguments = merged_args)
}

