# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# ===================================================================

#' @title Scale the values of the bands of a raster dataset.
#' @description
#' Auto-generated GDAL CLI wrapper.
#' Scale the values of the bands of a raster dataset.
#' @param input_format GDAL argument
#' @param open_option GDAL argument
#' @param input GDAL argument
#' @param output_format GDAL argument
#' @param creation_option GDAL argument
#' @param overwrite GDAL argument
#' @param output_data_type GDAL argument
#' @param band GDAL argument
#' @param src_min GDAL argument
#' @param src_max GDAL argument
#' @param dst_min GDAL argument
#' @param dst_max GDAL argument
#' @param exponent GDAL argument
#' @param no_clip GDAL argument
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples
#' \dontrun{
#' gdal_raster_scale(...) |> gdal_run()
#' }

#' @export
gdal_raster_scale <- function(input_format = NULL,
  open_option = NULL,
  input = NULL,
  output_format = NULL,
  creation_option = NULL,
  overwrite = FALSE,
  output_data_type = NULL,
  band = NULL,
  src_min = NULL,
  src_max = NULL,
  dst_min = NULL,
  dst_max = NULL,
  exponent = NULL,
  no_clip = FALSE) {
  # Collect arguments
  args <- list()
  if (!missing(input_format)) args[["input_format"]] <- input_format
  if (!missing(open_option)) args[["open_option"]] <- open_option
  if (!missing(input)) args[["input"]] <- input
  if (!missing(output_format)) args[["output_format"]] <- output_format
  if (!missing(creation_option)) args[["creation_option"]] <- creation_option
  if (!missing(overwrite)) args[["overwrite"]] <- overwrite
  if (!missing(output_data_type)) args[["output_data_type"]] <- output_data_type
  if (!missing(band)) args[["band"]] <- band
  if (!missing(src_min)) args[["src_min"]] <- src_min
  if (!missing(src_max)) args[["src_max"]] <- src_max
  if (!missing(dst_min)) args[["dst_min"]] <- dst_min
  if (!missing(dst_max)) args[["dst_max"]] <- dst_max
  if (!missing(exponent)) args[["exponent"]] <- exponent
  if (!missing(no_clip)) args[["no_clip"]] <- no_clip

  new_gdal_job(command_path = c("gdal", "raster", "scale"), arguments = args)
}

