# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.13.3
# ===================================================================

#' @title edit: Edit a raster dataset
#' @description
#' `gdal raster edit` can be used to edit a raster dataset. This subcommand is also available as a potential step of gdal_raster_pipeline
#' 
#' See \url{https://gdal.org/en/release-3.13/programs/gdal_raster_edit.html} for detailed GDAL documentation.
#' @param dataset Dataset (to be updated in-place, unless --auxiliary) (Dataset path) (required). Can also be a [gdal_job] object to extend a pipeline
#' @param quiet Quiet mode (no progress bar or warning message) (Logical) (Common)
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>` (Advanced)
#' @param auxiliary Ask for an auxiliary .aux.xml file to be edited (Logical)
#' @param band Active band (1-based index) (Integer)
#' @param crs Override CRS (without reprojection)
#' @param bbox Bounding box as xmin,ymin,xmax,ymax. Exactly `4` value(s)
#' @param nodata Assign a specified nodata value to output bands ('none', numeric value, 'nan', 'inf', '-inf')
#' @param color_interpretation Set band color interpretation (Character vector). Format: `[all|<BAND>=]<COLOR-INTEPRETATION>`
#' @param color_map Color map filename
#' @param scale Override band scale factor (Character vector). Format: `[<BAND>=]<SCALE>`
#' @param offset Override band offset constant (Character vector). Format: `[<BAND>=]<OFFSET>`
#' @param metadata Add/update dataset metadata item (Character vector). Format: `<KEY>=<VALUE>`
#' @param unset_color_table Unset color table on 1st band or the one specified with --band (Logical)
#' @param unset_metadata Remove dataset metadata item(s) (Character vector). Format: `KEY`
#' @param unset_metadata_domain Remove dataset metadata domain(s) (Character vector). Format: `DOMAIN`
#' @param gcp Add ground control point, formatted as pixel,line,easting,northing\[,elevation\], or @filename (Character vector)
#' @param stats Compute statistics, using all pixels (Logical)
#' @param approx_stats Compute statistics, using a subset of pixels (Logical)
#' @param hist Compute histogram (Logical)
#' @param ... Parameter aliases and synonyms for backward compatibility. See `?gdal_parameter_aliases` for details.
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples

#' job <- gdal_raster_edit(dataset = "my.tif", crs = "EPSG:32632")
#' \dontrun{
#'   result <- gdal_job_run(job)
#' }
#' @export
gdal_raster_edit <- function(dataset,
  quiet = FALSE,
  open_option = NULL,
  auxiliary = FALSE,
  band = NULL,
  crs = NULL,
  bbox = NULL,
  nodata = NULL,
  color_interpretation = NULL,
  color_map = NULL,
  scale = NULL,
  offset = NULL,
  metadata = NULL,
  unset_color_table = FALSE,
  unset_metadata = NULL,
  unset_metadata_domain = NULL,
  gcp = NULL,
  stats = FALSE,
  approx_stats = FALSE,
  hist = FALSE,
  ...) {
  new_args <- list()
  if (!missing(dataset)) new_args[["dataset"]] <- dataset
  if (!missing(quiet)) new_args[["quiet"]] <- quiet
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(auxiliary)) new_args[["auxiliary"]] <- auxiliary
  if (!missing(band)) new_args[["band"]] <- band
  if (!missing(crs)) new_args[["crs"]] <- crs
  if (!missing(bbox)) new_args[["bbox"]] <- bbox
  if (!missing(nodata)) new_args[["nodata"]] <- nodata
  if (!missing(color_interpretation)) new_args[["color_interpretation"]] <- color_interpretation
  if (!missing(color_map)) new_args[["color_map"]] <- color_map
  if (!missing(scale)) new_args[["scale"]] <- scale
  if (!missing(offset)) new_args[["offset"]] <- offset
  if (!missing(metadata)) new_args[["metadata"]] <- metadata
  if (!missing(unset_color_table)) new_args[["unset_color_table"]] <- unset_color_table
  if (!missing(unset_metadata)) new_args[["unset_metadata"]] <- unset_metadata
  if (!missing(unset_metadata_domain)) new_args[["unset_metadata_domain"]] <- unset_metadata_domain
  if (!missing(gcp)) new_args[["gcp"]] <- gcp
  if (!missing(stats)) new_args[["stats"]] <- stats
  if (!missing(approx_stats)) new_args[["approx_stats"]] <- approx_stats
  if (!missing(hist)) new_args[["hist"]] <- hist


  if (!missing(dataset) && inherits(dataset, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- dataset
    new_args[["dataset"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("raster", "edit"), new_args))
  }


  merged_args <- .merge_alias_parameters(list(...), new_args)
  .update_intent_mapping <- list(dataset = list(by_default = TRUE, unless_any_of = "auxiliary"))
  .update_intent <- infer_update_intent("gdal_raster_edit", merged_args, .update_intent_mapping)

  .arg_mapping <- list(
    dataset = list(min_count = 0, max_count = 1),
    quiet = list(min_count = 0, max_count = 1),
    open_option = list(min_count = 0, max_count = 2147483647),
    auxiliary = list(min_count = 0, max_count = 1),
    band = list(min_count = 0, max_count = 1),
    crs = list(min_count = 0, max_count = 1),
    bbox = list(min_count = 4, max_count = 4),
    nodata = list(min_count = 0, max_count = 1),
    color_interpretation = list(min_count = 0, max_count = 2147483647),
    color_map = list(min_count = 0, max_count = 1),
    scale = list(min_count = 0, max_count = 2147483647),
    offset = list(min_count = 0, max_count = 2147483647),
    metadata = list(min_count = 0, max_count = 2147483647),
    unset_color_table = list(min_count = 0, max_count = 1),
    unset_metadata = list(min_count = 0, max_count = 2147483647),
    unset_metadata_domain = list(min_count = 0, max_count = 2147483647),
    gcp = list(min_count = 0, max_count = 2147483647),
    stats = list(min_count = 0, max_count = 1),
    approx_stats = list(min_count = 0, max_count = 1),
    hist = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("raster", "edit"), arguments = merged_args, arg_mapping = .arg_mapping, update_intent = .update_intent)
}

