# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# ===================================================================

#' @title validate: Validate a ZIP file, possibly using SOZIP optimization
#' @description
#' The gdal vsi sozip utility can be used to:
#' 
#' See \url{https://gdal.org/en/stable/programs/gdal_vsi_sozip_validate.html} for detailed GDAL documentation.
#' @param job A gdal_job object from a piped operation, or NULL
#' @param input Input ZIP filename (required)
#' @param stdout Directly output on stdout. If enabled, output-string will be empty (Logical)
#' @return A [gdal_job] object.
#' @family gdal_vsi_utilities
#' @examples
#' @export
gdal_vsi_sozip_validate <- function(job = NULL,
  input,
  stdout = FALSE) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(stdout)) new_args[["stdout"]] <- stdout
  job_input <- handle_job_input(job, new_args, c("vsi", "sozip", "validate"))
  if (job_input$should_extend) {
    return(extend_gdal_pipeline(job_input$job, c("vsi", "sozip", "validate"), new_args))
  } else {
    merged_args <- job_input$merged_args
  }

  new_gdal_job(command_path = c("vsi", "sozip", "validate"), arguments = merged_args)
}

