# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.12.2
# Generation date: 2026-05-09
# ===================================================================

#' @title mosaic: Build a mosaic, either virtual (VRT) or materialized
#' @description
#' This program builds a mosaic of a list of input GDAL datasets, that can be either a virtual mosaic in the VRT (Virtual Dataset) <raster.vrt> format, or in a more conventional raster format such as GeoTIFF. Wildcards '*', '?' or '\['\] of :cppVSIGlob can be used for input dataset names, even on files located on network file systems such as /vsis3/, /vsigs/, /vsiaz/, etc. Alternatively if a input dataset name is prefixed by the `@` character, it will be assumed to contain the list of actual dataset names (one per line) to use as input datasets. gdal raster mosaic does some checks to ensure that all files that will be put in the resulting file have similar characteristics: number of bands, projection, color interpretation, etc. If not, files that do not match the common characteristics will be skipped. Starting with GDAL 3.12, a function (e.g., ``min``, ``mean``, ``median``) can be specified (--pixel-function) to calculate pixel values from overlapping inputs. If no function is specified, or in earlier versions, the order of the input list is used to determine priority. Files that are listed at the end are the ones from which the content will be fetched. Note that nodata will be taken into account to potentially fetch data from lower-priority datasets, but currently, alpha channel is not taken into account to do alpha compositing (so a source with alpha=0 appearing on top of another source will override its content). This might be changed in later versions. Stating with GDAL 3.12, this command can also be used as the first step of gdal_raster_pipeline.
#' 
#' See \url{https://gdal.org/en/release-3.12/programs/gdal_raster_mosaic.html} for detailed GDAL documentation.
#' @param input Input raster datasets (or specify a @<filename> to point to a file containing filenames) (required). `1` to `2147483647` value(s). Can also be a [gdal_job] object to extend a pipeline
#' @param input_format Input formats (Character vector) (Advanced)
#' @param output Output raster dataset (Dataset path) (required)
#' @param output_format Output format ("GDALG" allowed)
#' @param target_aligned_pixels Round target extent to target resolution (Logical)
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>` (Advanced)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`
#' @param overwrite Whether overwriting existing output is allowed (Logical) (Default: `false`)
#' @param append Append as a subdataset to existing output (Logical) (Default: `false`)
#' @param band Input band(s) (1-based index) (Integer vector)
#' @param absolute_path Whether the path to the input datasets should be stored as an absolute path (Logical)
#' @param resolution Target resolution (in destination CRS units). Format: `<xres>,<yres>|same|average|common|highest|lowest` (Default: `same`)
#' @param bbox Target bounding box as xmin,ymin,xmax,ymax (in destination CRS units). Exactly `4` value(s)
#' @param src_nodata Set nodata values for input bands.. `1` to `2147483647` value(s)
#' @param dst_nodata Set nodata values at the destination band level.. `1` to `2147483647` value(s)
#' @param hide_nodata Makes the destination band not report the NoData. (Logical)
#' @param add_alpha Adds an alpha mask band to the destination when the source raster have none. (Logical)
#' @param pixel_function Specify a pixel function to calculate output value from overlapping inputs. Choices: "argmax", "argmin", "cmul", "complex", "conj", ...
#' @param pixel_function_arg Specify argument(s) to pass to the pixel function (Character vector). Format: `<NAME>=<VALUE>`
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples

#' job <- gdal_raster_mosaic(input = "doq/*.tif", output = "doq_index.vrt", 
#'     hide_nodata = TRUE, dst_nodata = "0,0,255")
#' \dontrun{
#'   result <- gdal_job_run(job)
#' }
#' @export
gdal_raster_mosaic <- function(input,
  input_format = NULL,
  output,
  output_format = NULL,
  target_aligned_pixels = FALSE,
  open_option = NULL,
  creation_option = NULL,
  overwrite = FALSE,
  append = FALSE,
  band = NULL,
  absolute_path = FALSE,
  resolution = NULL,
  bbox = NULL,
  src_nodata = NULL,
  dst_nodata = NULL,
  hide_nodata = FALSE,
  add_alpha = FALSE,
  pixel_function = NULL,
  pixel_function_arg = NULL) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(target_aligned_pixels)) new_args[["target_aligned_pixels"]] <- target_aligned_pixels
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(append)) new_args[["append"]] <- append
  if (!missing(band)) new_args[["band"]] <- band
  if (!missing(absolute_path)) new_args[["absolute_path"]] <- absolute_path
  if (!missing(resolution)) new_args[["resolution"]] <- resolution
  if (!missing(bbox)) new_args[["bbox"]] <- bbox
  if (!missing(src_nodata)) new_args[["src_nodata"]] <- src_nodata
  if (!missing(dst_nodata)) new_args[["dst_nodata"]] <- dst_nodata
  if (!missing(hide_nodata)) new_args[["hide_nodata"]] <- hide_nodata
  if (!missing(add_alpha)) new_args[["add_alpha"]] <- add_alpha
  if (!missing(pixel_function)) new_args[["pixel_function"]] <- pixel_function
  if (!missing(pixel_function_arg)) new_args[["pixel_function_arg"]] <- pixel_function_arg

  # Check if first argument is a piped gdal_job or actual data
  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("raster", "mosaic"), new_args))
  }

  # First argument is actual data or missing - create new job
  merged_args <- new_args

  .arg_mapping <- list(
    input = list(min_count = 1, max_count = 2147483647),
    input_format = list(min_count = 0, max_count = 2147483647),
    output = list(min_count = 0, max_count = 1),
    output_format = list(min_count = 0, max_count = 1),
    target_aligned_pixels = list(min_count = 0, max_count = 1),
    open_option = list(min_count = 0, max_count = 2147483647),
    creation_option = list(min_count = 0, max_count = 2147483647),
    overwrite = list(min_count = 0, max_count = 1),
    append = list(min_count = 0, max_count = 1),
    band = list(min_count = 0, max_count = 2147483647),
    absolute_path = list(min_count = 0, max_count = 1),
    resolution = list(min_count = 0, max_count = 1),
    bbox = list(min_count = 4, max_count = 4),
    src_nodata = list(min_count = 1, max_count = 2147483647),
    dst_nodata = list(min_count = 1, max_count = 2147483647),
    hide_nodata = list(min_count = 0, max_count = 1),
    add_alpha = list(min_count = 0, max_count = 1),
    pixel_function = list(min_count = 0, max_count = 1),
    pixel_function_arg = list(min_count = 0, max_count = 2147483647)
  )

  new_gdal_job(command_path = c("raster", "mosaic"), arguments = merged_args, arg_mapping = .arg_mapping)
}

