# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# ===================================================================

#' @title Generate a slope map
#' @description
#' Auto-generated GDAL CLI wrapper.
#' Generate a slope map
#' @param input_format GDAL argument
#' @param open_option GDAL argument
#' @param input GDAL argument
#' @param output_format GDAL argument
#' @param creation_option GDAL argument
#' @param overwrite GDAL argument
#' @param band GDAL argument
#' @param unit GDAL argument
#' @param xscale GDAL argument
#' @param yscale GDAL argument
#' @param gradient_alg GDAL argument
#' @param no_edges GDAL argument
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples
#' \dontrun{
#' gdal_raster_slope(...) |> gdal_run()
#' }

#' @export
gdal_raster_slope <- function(input_format = NULL,
  open_option = NULL,
  input = NULL,
  output_format = NULL,
  creation_option = NULL,
  overwrite = FALSE,
  band = NULL,
  unit = NULL,
  xscale = NULL,
  yscale = NULL,
  gradient_alg = NULL,
  no_edges = FALSE) {
  # Collect arguments
  args <- list()
  if (!missing(input_format)) args[["input_format"]] <- input_format
  if (!missing(open_option)) args[["open_option"]] <- open_option
  if (!missing(input)) args[["input"]] <- input
  if (!missing(output_format)) args[["output_format"]] <- output_format
  if (!missing(creation_option)) args[["creation_option"]] <- creation_option
  if (!missing(overwrite)) args[["overwrite"]] <- overwrite
  if (!missing(band)) args[["band"]] <- band
  if (!missing(unit)) args[["unit"]] <- unit
  if (!missing(xscale)) args[["xscale"]] <- xscale
  if (!missing(yscale)) args[["yscale"]] <- yscale
  if (!missing(gradient_alg)) args[["gradient_alg"]] <- gradient_alg
  if (!missing(no_edges)) args[["no_edges"]] <- no_edges

  new_gdal_job(command_path = c("gdal", "raster", "slope"), arguments = args)
}

