# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# ===================================================================

#' @title Process a raster dataset.
#' @description
#' Auto-generated GDAL CLI wrapper.
#' Process a raster dataset.
#' @param input_format GDAL argument
#' @param open_option GDAL argument
#' @param input GDAL argument
#' @param pipeline GDAL argument
#' @param output_format GDAL argument
#' @param creation_option GDAL argument
#' @param overwrite GDAL argument
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples
#' \dontrun{
#' gdal_raster_pipeline(...) |> gdal_run()
#' }

#' @export
gdal_raster_pipeline <- function(input_format = NULL,
  open_option = NULL,
  input = NULL,
  pipeline = NULL,
  output_format = NULL,
  creation_option = NULL,
  overwrite = FALSE) {
  # Collect arguments
  args <- list()
  if (!missing(input_format)) args[["input_format"]] <- input_format
  if (!missing(open_option)) args[["open_option"]] <- open_option
  if (!missing(input)) args[["input"]] <- input
  if (!missing(pipeline)) args[["pipeline"]] <- pipeline
  if (!missing(output_format)) args[["output_format"]] <- output_format
  if (!missing(creation_option)) args[["creation_option"]] <- creation_option
  if (!missing(overwrite)) args[["overwrite"]] <- overwrite

  new_gdal_job(command_path = c("gdal", "raster", "pipeline"), arguments = args)
}

