# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.13.3
# ===================================================================

#' @title delete: Delete files located on GDAL Virtual System Interface (VSI)
#' @description
#' `gdal vsi delete` delete files and directories located on virtual_file_systems. This is the equivalent of the UNIX ``rm`` command, and ``gdal vsi rm`` is an alias for ``gdal vsi delete``.
#' 
#' See \url{https://gdal.org/en/release-3.13/programs/gdal_vsi_delete.html} for detailed GDAL documentation.
#' @param filename File or directory name to delete (required). Can also be a [gdal_job] object to extend a pipeline
#' @param recursive Delete directories recursively (Logical)
#' @param ... Parameter aliases and synonyms for backward compatibility. See `?gdal_parameter_aliases` for details.
#' @return A [gdal_job] object.
#' @family gdal_vsi_utilities
#' @examples
#' \dontrun{
#' # TODO: No examples available for gdal_vsi_delete.
#' # See GDAL documentation at:
#' https://gdal.org/en/release-3.13/programs/gdal_vsi_delete.html
#' job <- gdal_vsi_delete()
#' # gdal_job_run(job)
#' }
#' @export
gdal_vsi_delete <- function(filename,
  recursive = FALSE,
  ...) {
  new_args <- list()
  if (!missing(filename)) new_args[["filename"]] <- filename
  if (!missing(recursive)) new_args[["recursive"]] <- recursive


  if (!missing(filename) && inherits(filename, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- filename
    new_args[["filename"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("vsi", "delete"), new_args))
  }


  merged_args <- .merge_alias_parameters(list(...), new_args)
  .update_intent_mapping <- NULL
  .update_intent <- infer_update_intent("gdal_vsi_delete", merged_args, .update_intent_mapping)

  .arg_mapping <- list(
    filename = list(min_count = 0, max_count = 1),
    recursive = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("vsi", "delete"), arguments = merged_args, arg_mapping = .arg_mapping, update_intent = .update_intent)
}

