# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# ===================================================================

#' @title Reproject a raster dataset.
#' @description
#' Auto-generated GDAL CLI wrapper.
#' Reproject a raster dataset.
#' @param input_format GDAL argument
#' @param open_option GDAL argument
#' @param input GDAL argument
#' @param output_format GDAL argument
#' @param creation_option GDAL argument
#' @param overwrite GDAL argument
#' @param src_crs GDAL argument
#' @param dst_crs GDAL argument
#' @param resampling GDAL argument
#' @param resolution GDAL argument
#' @param size GDAL argument
#' @param bbox GDAL argument
#' @param bbox_crs GDAL argument
#' @param target_aligned_pixels GDAL argument
#' @param src_nodata GDAL argument
#' @param dst_nodata GDAL argument
#' @param add_alpha GDAL argument
#' @param warp_option GDAL argument
#' @param transform_option GDAL argument
#' @param error_threshold GDAL argument
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples
#' \dontrun{
#' gdal_raster_reproject(...) |> gdal_run()
#' }

#' @export
gdal_raster_reproject <- function(input_format = NULL,
  open_option = NULL,
  input = NULL,
  output_format = NULL,
  creation_option = NULL,
  overwrite = FALSE,
  src_crs = NULL,
  dst_crs = NULL,
  resampling = NULL,
  resolution,
  size,
  bbox,
  bbox_crs = NULL,
  target_aligned_pixels = FALSE,
  src_nodata,
  dst_nodata,
  add_alpha = FALSE,
  warp_option = NULL,
  transform_option = NULL,
  error_threshold = NULL) {
  # Collect arguments
  args <- list()
  if (!missing(input_format)) args[["input_format"]] <- input_format
  if (!missing(open_option)) args[["open_option"]] <- open_option
  if (!missing(input)) args[["input"]] <- input
  if (!missing(output_format)) args[["output_format"]] <- output_format
  if (!missing(creation_option)) args[["creation_option"]] <- creation_option
  if (!missing(overwrite)) args[["overwrite"]] <- overwrite
  if (!missing(src_crs)) args[["src_crs"]] <- src_crs
  if (!missing(dst_crs)) args[["dst_crs"]] <- dst_crs
  if (!missing(resampling)) args[["resampling"]] <- resampling
  if (!missing(resolution)) args[["resolution"]] <- resolution
  if (!missing(size)) args[["size"]] <- size
  if (!missing(bbox)) args[["bbox"]] <- bbox
  if (!missing(bbox_crs)) args[["bbox_crs"]] <- bbox_crs
  if (!missing(target_aligned_pixels)) args[["target_aligned_pixels"]] <- target_aligned_pixels
  if (!missing(src_nodata)) args[["src_nodata"]] <- src_nodata
  if (!missing(dst_nodata)) args[["dst_nodata"]] <- dst_nodata
  if (!missing(add_alpha)) args[["add_alpha"]] <- add_alpha
  if (!missing(warp_option)) args[["warp_option"]] <- warp_option
  if (!missing(transform_option)) args[["transform_option"]] <- transform_option
  if (!missing(error_threshold)) args[["error_threshold"]] <- error_threshold

  new_gdal_job(command_path = c("gdal", "raster", "reproject"), arguments = args)
}

