# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# ===================================================================

#' @title Return information on a multidimensional dataset.
#' @description
#' Auto-generated GDAL CLI wrapper.
#' Return information on a multidimensional dataset.
#' @param open_option GDAL argument
#' @param input_format GDAL argument
#' @param input GDAL argument
#' @param detailed GDAL argument
#' @param array GDAL argument
#' @param limit GDAL argument
#' @param array_option GDAL argument
#' @param stats GDAL argument
#' @param stdout GDAL argument
#' @return A [gdal_job] object.
#' @family gdal_mdim_utilities
#' @examples
#' \dontrun{
#' gdal_mdim_info(...) |> gdal_run()
#' }

#' @export
gdal_mdim_info <- function(open_option = NULL,
  input_format = NULL,
  input = NULL,
  detailed = FALSE,
  array = NULL,
  limit = NULL,
  array_option = NULL,
  stats = FALSE,
  stdout = FALSE) {
  # Collect arguments
  args <- list()
  if (!missing(open_option)) args[["open_option"]] <- open_option
  if (!missing(input_format)) args[["input_format"]] <- input_format
  if (!missing(input)) args[["input"]] <- input
  if (!missing(detailed)) args[["detailed"]] <- detailed
  if (!missing(array)) args[["array"]] <- array
  if (!missing(limit)) args[["limit"]] <- limit
  if (!missing(array_option)) args[["array_option"]] <- array_option
  if (!missing(stats)) args[["stats"]] <- stats
  if (!missing(stdout)) args[["stdout"]] <- stdout

  new_gdal_job(command_path = c("gdal", "mdim", "info"), arguments = args)
}

