# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# ===================================================================

#' @title concat: Concatenate vector datasets
#' @description
#' Concatenate vector datasets.
#' 
#' See \url{https://gdal.org/en/stable/programs/gdal_vector_concat.html} for detailed GDAL documentation.
#' @param job A gdal_job object from a piped operation, or NULL
#' @param input Input vector datasets (required). `1` to `2147483647` value(s)
#' @param output Output vector dataset (Dataset path) (required)
#' @param input_format Input formats (Character vector). `0` to `2147483647` value(s) (Advanced)
#' @param input_layer Input layer name(s) (Character vector). `0` to `2147483647` value(s)
#' @param source_layer_field_name Name of the new field to add to contain identificoncation of the source layer, with value determined from 'source-layer-field-content'
#' @param source_layer_field_content A string, possibly using \{AUTO_NAME\}, \{DS_NAME\}, \{DS_BASENAME\}, \{DS_INDEX\}, \{LAYER_NAME\}, \{LAYER_INDEX\}
#' @param output_format Output format ("GDALG" allowed)
#' @param output_layer Name of the output vector layer (single mode), or template to name the output vector layers (stack mode)
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s) (Advanced)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s)
#' @param layer_creation_option Layer creation option (Character vector). Format: `<KEY>=<VALUE>`. `0` to `2147483647` value(s)
#' @param overwrite Whether overwriting existing output is allowed (Logical) (Default: `false`)
#' @param update Whether to open existing dataset in update mode (Logical) (Default: `false`)
#' @param overwrite_layer Whether overwriting existing layer is allowed (Logical) (Default: `false`)
#' @param append Whether appending to existing layer is allowed (Logical) (Default: `false`)
#' @param mode Determine the strategy to create output layers from source layers . Choices: merge-per-layer-name, stack, single (Default: `merge-per-layer-name`)
#' @param field_strategy How to determine target fields from source fields. Choices: union, intersection (Default: `union`)
#' @param src_crs Source CRS
#' @param dst_crs Destination CRS
#' @return A [gdal_job] object.
#' @family gdal_vector_utilities
#' @examples
#' @export
gdal_vector_concat <- function(job = NULL,
  input,
  output,
  input_format = NULL,
  input_layer = NULL,
  source_layer_field_name = NULL,
  source_layer_field_content = NULL,
  output_format = NULL,
  output_layer = NULL,
  open_option = NULL,
  creation_option = NULL,
  layer_creation_option = NULL,
  overwrite = FALSE,
  update = FALSE,
  overwrite_layer = FALSE,
  append = FALSE,
  mode = NULL,
  field_strategy = NULL,
  src_crs = NULL,
  dst_crs = NULL) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(input_layer)) new_args[["input_layer"]] <- input_layer
  if (!missing(source_layer_field_name)) new_args[["source_layer_field_name"]] <- source_layer_field_name
  if (!missing(source_layer_field_content)) new_args[["source_layer_field_content"]] <- source_layer_field_content
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(output_layer)) new_args[["output_layer"]] <- output_layer
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(layer_creation_option)) new_args[["layer_creation_option"]] <- layer_creation_option
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(update)) new_args[["update"]] <- update
  if (!missing(overwrite_layer)) new_args[["overwrite_layer"]] <- overwrite_layer
  if (!missing(append)) new_args[["append"]] <- append
  if (!missing(mode)) new_args[["mode"]] <- mode
  if (!missing(field_strategy)) new_args[["field_strategy"]] <- field_strategy
  if (!missing(src_crs)) new_args[["src_crs"]] <- src_crs
  if (!missing(dst_crs)) new_args[["dst_crs"]] <- dst_crs
  job_input <- handle_job_input(job, new_args, c("vector", "concat"))
  if (job_input$should_extend) {
    return(extend_gdal_pipeline(job_input$job, c("vector", "concat"), new_args))
  } else {
    merged_args <- job_input$merged_args
  }

  new_gdal_job(command_path = c("vector", "concat"), arguments = merged_args)
}

