# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.13.0
# ===================================================================

#' @title check-geometry: Check a dataset for invalid geometries
#' @description
#' `gdal vector check-geometry` checks that individual elements of a dataset are valid and simple according to the OGC Simple Features standard. For each invalid or non-simple feature, it will output a description and, in most cases, a point location of the error. The following checks are performed, depending on the input geometry type: - Polygons and MultiPolygons are checked for validity. A single point error point will be reported even if there are multiple causes of invalidity. - LineStrings and MultiLineStrings are checked for simplicity. All self-intersection locations will be reported if GDAL is built using version 3.14 or later of the GEOS library. With earlier versions, self-intersection locations are not reported. - GeometryCollections are checked that their individual elements are valid / simple. A single error point will be reported even if there are multiple causes of invalidity. - Other geometry types are not checked. Validity/simplicity checking is performed by the GEOS library and should be consistent with results of software such as PostGIS, QGIS, and shapely that also use that library. GEOS does not consider repeated points to be a cause of invalidity or non-simplicity. For more information about validity testing performed by gdal vector check-geometry, and examples of reported errors, see geometry_validity.
#' 
#' See \url{https://gdal.org/en/release-3.13/programs/gdal_vector_check-geometry.html} for detailed GDAL documentation.
#' @param input Input vector datasets (required). Exactly `1` value(s). Can also be a [gdal_job] object to extend a pipeline
#' @param input_format Input formats (Character vector) (Advanced)
#' @param input_layer Input layer name(s) (Character vector)
#' @param output Output vector dataset (Dataset path) (required)
#' @param output_format Output format ("GDALG" allowed)
#' @param output_open_option Output open options (Character vector). Format: `<KEY>=<VALUE>` (Advanced)
#' @param output_layer Output layer name
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>` (Advanced)
#' @param quiet Quiet mode (no progress bar or warning message) (Logical) (Common)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`
#' @param layer_creation_option Layer creation option (Character vector). Format: `<KEY>=<VALUE>`
#' @param overwrite Whether overwriting existing output dataset is allowed (Logical) (Default: `false`)
#' @param update Whether to open existing dataset in update mode (Logical) (Default: `false`)
#' @param overwrite_layer Whether overwriting existing output layer is allowed (Logical) (Default: `false`)
#' @param append Whether appending to existing layer is allowed (Logical) (Default: `false`)
#' @param upsert Upsert features (implies 'append') (Logical) (Advanced)
#' @param skip_errors Skip errors when writing features (Logical)
#' @param no_create_empty_layers Avoid creating layers to which no features will be written (Logical)
#' @param include_field Fields from input layer to include in output (special values: ALL and NONE) (Character vector) (Default: `NONE`)
#' @param include_valid Include valid inputs in output, with empty geometry (Logical)
#' @param geometry_field Name of geometry field to check
#' @param ... Parameter aliases and synonyms for backward compatibility. See `?gdal_parameter_aliases` for details.
#' @return A [gdal_job] object.
#' @family gdal_vector_utilities
#' @examples
#' \dontrun{
#' # TODO: No examples available for gdal_vector_check_geometry.
#' # See GDAL documentation at:
#' https://gdal.org/en/release-3.13/programs/gdal_vector_check-geometry.html
#' job <- gdal_vector_check_geometry()
#' # gdal_job_run(job)
#' }
#' @export
gdal_vector_check_geometry <- function(input,
  input_format = NULL,
  input_layer = NULL,
  output,
  output_format = NULL,
  output_open_option = NULL,
  output_layer = NULL,
  open_option = NULL,
  quiet = FALSE,
  creation_option = NULL,
  layer_creation_option = NULL,
  overwrite = FALSE,
  update = FALSE,
  overwrite_layer = FALSE,
  append = FALSE,
  upsert = FALSE,
  skip_errors = FALSE,
  no_create_empty_layers = FALSE,
  include_field = NULL,
  include_valid = FALSE,
  geometry_field = NULL,
  ...) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(input_layer)) new_args[["input_layer"]] <- input_layer
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(output_open_option)) new_args[["output_open_option"]] <- output_open_option
  if (!missing(output_layer)) new_args[["output_layer"]] <- output_layer
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(quiet)) new_args[["quiet"]] <- quiet
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(layer_creation_option)) new_args[["layer_creation_option"]] <- layer_creation_option
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(update)) new_args[["update"]] <- update
  if (!missing(overwrite_layer)) new_args[["overwrite_layer"]] <- overwrite_layer
  if (!missing(append)) new_args[["append"]] <- append
  if (!missing(upsert)) new_args[["upsert"]] <- upsert
  if (!missing(skip_errors)) new_args[["skip_errors"]] <- skip_errors
  if (!missing(no_create_empty_layers)) new_args[["no_create_empty_layers"]] <- no_create_empty_layers
  if (!missing(include_field)) new_args[["include_field"]] <- include_field
  if (!missing(include_valid)) new_args[["include_valid"]] <- include_valid
  if (!missing(geometry_field)) new_args[["geometry_field"]] <- geometry_field


  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("vector", "check-geometry"), new_args))
  }


  merged_args <- .merge_alias_parameters(list(...), new_args)
  .update_intent_mapping <- NULL
  .update_intent <- infer_update_intent("gdal_vector_check_geometry", merged_args, .update_intent_mapping)

  .arg_mapping <- list(
    input = list(min_count = 1, max_count = 1),
    input_format = list(min_count = 0, max_count = 2147483647),
    input_layer = list(min_count = 0, max_count = 2147483647),
    output = list(min_count = 0, max_count = 1),
    output_format = list(min_count = 0, max_count = 1),
    output_open_option = list(min_count = 0, max_count = 2147483647),
    output_layer = list(min_count = 0, max_count = 1),
    open_option = list(min_count = 0, max_count = 2147483647),
    quiet = list(min_count = 0, max_count = 1),
    creation_option = list(min_count = 0, max_count = 2147483647),
    layer_creation_option = list(min_count = 0, max_count = 2147483647),
    overwrite = list(min_count = 0, max_count = 1),
    update = list(min_count = 0, max_count = 1),
    overwrite_layer = list(min_count = 0, max_count = 1),
    append = list(min_count = 0, max_count = 1),
    upsert = list(min_count = 0, max_count = 1),
    skip_errors = list(min_count = 0, max_count = 1),
    no_create_empty_layers = list(min_count = 0, max_count = 1),
    include_field = list(min_count = 0, max_count = 2147483647),
    include_valid = list(min_count = 0, max_count = 1),
    geometry_field = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("vector", "check-geometry"), arguments = merged_args, arg_mapping = .arg_mapping, update_intent = .update_intent)
}

