# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# ===================================================================

#' @title List content of a ZIP file, with SOZIP related information.
#' @description
#' Auto-generated GDAL CLI wrapper.
#' List content of a ZIP file, with SOZIP related information.
#' @param input GDAL argument
#' @return A [gdal_job] object.
#' @family gdal_vsi_utilities
#' @examples
#' \dontrun{
#' gdal_vsi_sozip_list(...) |> gdal_run()
#' }

#' @export
gdal_vsi_sozip_list <- function(input = NULL) {
  # Collect arguments
  args <- list()
  if (!missing(input)) args[["input"]] <- input

  new_gdal_job(command_path = c("gdal", "vsi", "sozip", "list"), arguments = args)
}

