# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# ===================================================================

#' @title Return information on a pixel of a raster dataset.
#' @description
#' Auto-generated GDAL CLI wrapper.
#' Return information on a pixel of a raster dataset.
#' @param output_format GDAL argument
#' @param open_option GDAL argument
#' @param input_format GDAL argument
#' @param input GDAL argument
#' @param band GDAL argument
#' @param overview GDAL argument
#' @param position GDAL argument
#' @param position_crs GDAL argument
#' @param resampling GDAL argument
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples
#' \dontrun{
#' gdal_raster_pixel_info(...) |> gdal_run()
#' }

#' @export
gdal_raster_pixel_info <- function(output_format = NULL,
  open_option = NULL,
  input_format = NULL,
  input = NULL,
  band = NULL,
  overview = NULL,
  position = NULL,
  position_crs = NULL,
  resampling = NULL) {
  # Collect arguments
  args <- list()
  if (!missing(output_format)) args[["output_format"]] <- output_format
  if (!missing(open_option)) args[["open_option"]] <- open_option
  if (!missing(input_format)) args[["input_format"]] <- input_format
  if (!missing(input)) args[["input"]] <- input
  if (!missing(band)) args[["band"]] <- band
  if (!missing(overview)) args[["overview"]] <- overview
  if (!missing(position)) args[["position"]] <- position
  if (!missing(position_crs)) args[["position_crs"]] <- position_crs
  if (!missing(resampling)) args[["resampling"]] <- resampling

  new_gdal_job(command_path = c("gdal", "raster", "pixel-info"), arguments = args)
}

