# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.13.3
# ===================================================================

#' @title pixel-info: Return information on a pixel of a raster dataset
#' @description
#' `gdal raster pixel-info` provide a mechanism to query information about a pixel given its location in one of a variety of coordinate systems. The following items will be reported (when known): - Input coordinates - Input coordinates converted to column, line - Pixel value per selected band(s), with unscaled value - For VRT files, which file(s) contribute to the pixel value (only for GeoJSON output) There are 3 possible ways of providing input location(s): - from input stream, with a "X Y" pair per line, potentially followed by other text. - though the --position argument. - through a GDAL vector dataset through the --position-dataset argument. There are 2 possibilities of outputting pixel information: - either on the output stream as CSV or GeoJSON (default to GeoJSON) - or as a GDAL vector dataset whose name is specified with the --output argument. Since GDAL 3.13, this algorithm can be part of a gdal_pipeline. In that case, only reading coordinates from a GDAL vector dataset and outputting results to one is supported.
#' 
#' See \url{https://gdal.org/en/release-3.13/programs/gdal_raster_pixel-info.html} for detailed GDAL documentation.
#' @param input Input raster datasets (required). Exactly `1` value(s). Can also be a [gdal_job] object to extend a pipeline
#' @param input_format Input formats (Character vector) (Advanced)
#' @param input_layer Input layer name (Character vector). `0` to `1` value(s)
#' @param output Output vector dataset (Dataset path)
#' @param output_format Output format (default is 'GeoJSON' if 'position-dataset' not specified)
#' @param open_option Open options (Character vector). Format: `<KEY>=<VALUE>` (Advanced)
#' @param position_dataset Vector dataset with coordinates (Dataset path)
#' @param creation_option Creation option (Character vector). Format: `<KEY>=<VALUE>`
#' @param layer_creation_option Layer creation option (Character vector). Format: `<KEY>=<VALUE>`
#' @param overwrite Whether overwriting existing output dataset is allowed (Logical) (Default: `false`)
#' @param band Input band(s) (1-based index) (Integer vector)
#' @param overview Which overview level of source file must be used (Integer). Minimum: `0`
#' @param position Pixel position. Format: `<column,line> or <X,Y>`
#' @param position_crs CRS of position (default is 'pixel' if 'position-dataset' not specified)
#' @param resampling Resampling algorithm for interpolation. Choices: "nearest", "bilinear", "cubic", "cubicspline" (Default: `nearest`)
#' @param promote_pixel_value_to_z Whether to set the pixel value as Z component of GeoJSON geometry (Logical)
#' @param include_field Fields from coordinate dataset to include in output (special values: ALL and NONE) (Character vector) (Default: `ALL`)
#' @param ... Parameter aliases and synonyms for backward compatibility. See `?gdal_parameter_aliases` for details.
#' @return A [gdal_job] object.
#' @family gdal_raster_utilities
#' @examples
#' \dontrun{
#' # TODO: No examples available for gdal_raster_pixel_info.
#' # See GDAL documentation at:
#' https://gdal.org/en/release-3.13/programs/gdal_raster_pixel-info.html
#' job <- gdal_raster_pixel_info()
#' # gdal_job_run(job)
#' }
#' @export
gdal_raster_pixel_info <- function(input,
  input_format = NULL,
  input_layer = NULL,
  output = NULL,
  output_format = NULL,
  open_option = NULL,
  position_dataset = NULL,
  creation_option = NULL,
  layer_creation_option = NULL,
  overwrite = FALSE,
  band = NULL,
  overview = NULL,
  position = NULL,
  position_crs = NULL,
  resampling = NULL,
  promote_pixel_value_to_z = FALSE,
  include_field = NULL,
  ...) {
  new_args <- list()
  if (!missing(input)) new_args[["input"]] <- input
  if (!missing(input_format)) new_args[["input_format"]] <- input_format
  if (!missing(input_layer)) new_args[["input_layer"]] <- input_layer
  if (!missing(output)) new_args[["output"]] <- output
  if (!missing(output_format)) new_args[["output_format"]] <- output_format
  if (!missing(open_option)) new_args[["open_option"]] <- open_option
  if (!missing(position_dataset)) new_args[["position_dataset"]] <- position_dataset
  if (!missing(creation_option)) new_args[["creation_option"]] <- creation_option
  if (!missing(layer_creation_option)) new_args[["layer_creation_option"]] <- layer_creation_option
  if (!missing(overwrite)) new_args[["overwrite"]] <- overwrite
  if (!missing(band)) new_args[["band"]] <- band
  if (!missing(overview)) new_args[["overview"]] <- overview
  if (!missing(position)) new_args[["position"]] <- position
  if (!missing(position_crs)) new_args[["position_crs"]] <- position_crs
  if (!missing(resampling)) new_args[["resampling"]] <- resampling
  if (!missing(promote_pixel_value_to_z)) new_args[["promote_pixel_value_to_z"]] <- promote_pixel_value_to_z
  if (!missing(include_field)) new_args[["include_field"]] <- include_field


  if (!missing(input) && inherits(input, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- input
    new_args[["input"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("raster", "pixel-info"), new_args))
  }


  merged_args <- .merge_alias_parameters(list(...), new_args)
  .update_intent_mapping <- NULL
  .update_intent <- infer_update_intent("gdal_raster_pixel_info", merged_args, .update_intent_mapping)

  .arg_mapping <- list(
    input = list(min_count = 1, max_count = 1),
    input_format = list(min_count = 0, max_count = 2147483647),
    input_layer = list(min_count = 0, max_count = 1),
    output = list(min_count = 0, max_count = 1),
    output_format = list(min_count = 0, max_count = 1),
    open_option = list(min_count = 0, max_count = 2147483647),
    position_dataset = list(min_count = 0, max_count = 1),
    creation_option = list(min_count = 0, max_count = 2147483647),
    layer_creation_option = list(min_count = 0, max_count = 2147483647),
    overwrite = list(min_count = 0, max_count = 1),
    band = list(min_count = 0, max_count = 2147483647),
    overview = list(min_count = 0, max_count = 1),
    position = list(min_count = 0, max_count = 2147483647),
    position_crs = list(min_count = 0, max_count = 1),
    resampling = list(min_count = 0, max_count = 1),
    promote_pixel_value_to_z = list(min_count = 0, max_count = 1),
    include_field = list(min_count = 0, max_count = 2147483647)
  )

  new_gdal_job(command_path = c("raster", "pixel-info"), arguments = merged_args, arg_mapping = .arg_mapping, update_intent = .update_intent)
}

