# ===================================================================
# This file is AUTO-GENERATED by build/generate_gdal_api.R
# Do not edit directly. Changes will be overwritten on regeneration.
# Generated for GDAL 3.13.2
# ===================================================================

#' @title vector: Vector commands
#' @description
#' Entry point for vector commands
#' 
#' See \url{https://gdal.org/en/release-3.13/programs/gdal_vector.html} for detailed GDAL documentation.
#' @param drivers Display vector driver list as JSON document and exit (Logical). Can also be a [gdal_job] object to extend a pipeline
#' @param ... Parameter aliases and synonyms for backward compatibility. See `?gdal_parameter_aliases` for details.
#' @return A [gdal_job] object.
#' @family gdal_vector_utilities
#' @examples
#' \dontrun{
#' # TODO: No examples available for gdal_vector.
#' # See GDAL documentation at:
#' https://gdal.org/en/release-3.13/programs/gdal_vector.html
#' job <- gdal_vector()
#' # gdal_job_run(job)
#' }
#' @export
gdal_vector <- function(drivers = FALSE,
  ...) {
  new_args <- list()
  if (!missing(drivers)) new_args[["drivers"]] <- drivers


  if (!missing(drivers) && inherits(drivers, 'gdal_job')) {
    # First argument is a piped job - extend the pipeline
    # Remove first_arg from new_args since it's the job, not data
    piped_job <- drivers
    new_args[["drivers"]] <- NULL
    new_args <- Filter(Negate(is.null), new_args)
    return(extend_gdal_pipeline(piped_job, c("vector"), new_args))
  }


  merged_args <- .merge_alias_parameters(list(...), new_args)
  .update_intent_mapping <- NULL
  .update_intent <- infer_update_intent("gdal_vector", merged_args, .update_intent_mapping)

  .arg_mapping <- list(
    drivers = list(min_count = 0, max_count = 1)
  )

  new_gdal_job(command_path = c("vector"), arguments = merged_args, arg_mapping = .arg_mapping, update_intent = .update_intent)
}

